# Importing Libraries

In [1]:
import pandas as pd

# Reading dataset

In [2]:
store_details = pd.read_csv('../Project/Datasets/store_details.csv')
store_details.head()

   store_id              store_name       phone                        email
0         1      FreshMart Downtown  6175551001       downtown@freshmart.com
1         2     FreshMart Riverside  6175551002      riverside@freshmart.com
2         3      GreenBasket Market  6175551003  hello@greenbasketmarket.com
3         4  UrbanGrocers South End  6175551004    southend@urbangrocers.com
4         5     QuickCart Brookline  6175551005      brookline@quickcart.com

In [3]:
store_address = pd.read_csv('../Project/Datasets/store_address.csv')
store_address.head()

            street        city          state country  zip_code  store_id
0      101 Main St      Boston  Massachusetts     USA      2108         1
1      22 River Rd   Cambridge  Massachusetts     USA      2139         2
2    15 Beacon Ave  Somerville  Massachusetts     USA      2143         3
3  88 Harrison Ave      Boston  Massachusetts     USA      2118         4
4       200 Elm St   Brookline  Massachusetts     USA      2445         5

In [4]:
store_staff = pd.read_csv('../Project/Datasets/store_staff.csv')
store_staff.head()

   emp_id       username password  store_id     role availability_status
0       1  olivia.parker  pass123         1  manager                 yes
1       2   chloe.martin  pass123         1   packer                 yes
2       3   jacob.turner  pass123         1   packer                 yes
3       4     grace.ward  pass123         1   packer                 yes
4       5  daniel.murphy  pass123         2  manager                 yes

In [5]:
store_mapping = pd.read_csv('../Project/Datasets/stores_mapping.csv')
store_mapping.head()

   store_id  inventory_id  product_id
0         1             1           1
1         1             2           2
2         1             3           3
3         1             4           4
4         1             5           5

In [6]:
category = pd.read_csv('../Project/Datasets/category.csv')
category.head()

   category_id   category_name                        category_description
0            1          Fruits                       Fresh seasonal fruits
1            2      Vegetables              Fresh produce and leafy greens
2            3           Dairy      Milk, yogurt, eggs, cheese, and butter
3            4          Bakery  Fresh breads, rolls, muffins, and pastries
4            5  Meat & Seafood                 White meat and seafood only

In [7]:
inventory = pd.read_csv('../Project/Datasets/inventory.csv')
inventory.head()

   inventory_id  quantity_available  reorder_level last_updated
0             1                   5              4   2026-03-29
1             2                  36              4   2026-03-29
2             3                  33              4   2026-03-29
3             4                  30              4   2026-03-29
4             5                  24              4   2026-03-29

In [8]:
product_images = pd.read_csv('../Project/Datasets/product_images.csv')
product_images.head()

,product_id,image_url,image_description
0,1,cdn.local/products/banana-bunch.jpg,Banana Bunch product image
1,2,cdn.local/products/gala-apples-3-lb.jpg,Gala Apples 3 lb product image
2,3,cdn.local/products/fuji-apples-3-lb.jpg,Fuji Apples 3 lb product image
3,4,cdn.local/products/navel-oranges-4-lb.jpg,Navel Oranges 4 lb product image
4,5,cdn.local/products/red-seedless-grapes-2-lb.jpg,Red Seedless Grapes 2 lb product image

In [9]:
product = pd.read_csv('../Project/Datasets/product.csv')
product.head()

,product_id,product_name,product_barcode,product_description,category_id
0,1,Banana Bunch,100000000001,Fresh yellow bananas,1
1,2,Gala Apples 3 lb,100000000002,Sweet gala apples bag,1
2,3,Fuji Apples 3 lb,100000000003,Crisp fuji apples bag,1
3,4,Navel Oranges 4 lb,100000000004,Juicy navel oranges bag,1
4,5,Red Seedless Grapes 2 lb,100000000005,Seedless red grapes,1

In [10]:
card_details = pd.read_csv('../Project/Datasets/card_details.csv')
card_details.head()

   card_id       card_name  last_4_digits    exp_date  customer_id
0        1     Emma Parker           6212  2031-06-01            1
1        2     Liam Murphy           3621  2031-08-01            2
2        3  Olivia Collins            320  2031-11-01            3
3        4       Noah Reed           9652  2029-11-01            4
4        5     Ava Bennett           6040  2031-05-01            5

In [11]:
customer = pd.read_csv('../Project/Datasets/customer.csv')
customer.head()

,customer_id,name,email,password,date_of_birth
0,1,Emma Parker,emma.parker1@gmail.com,emma@123,1983-02-01
1,2,Liam Murphy,liam.murphy2@outlook.com,liam@123,1973-12-07
2,3,Olivia Collins,olivia.collins3@yahoo.com,olivia@123,1966-02-03
3,4,Noah Reed,noah.reed4@icloud.com,noah@123,1992-06-25
4,5,Ava Bennett,ava.bennett5@gmail.com,ava@123,1976-10-07

In [12]:
customer_address = pd.read_csv('../Project/Datasets/customer_address.csv')
customer_address.head()

            street    city          state country  zip_code  customer_id
0    616 Beacon St  Quincy  Massachusetts     USA      2169            1
1  283 Pleasant St  Boston  Massachusetts     USA      2108            2
2    737 Summer St  Quincy  Massachusetts     USA      2169            3
3   68 Chestnut St  Boston  Massachusetts     USA      2108            4
4     762 Park Ave  Malden  Massachusetts     USA      2148            5

In [13]:
order_confirmation = pd.read_csv('../Project/Datasets/order_confirmation.csv')
order_confirmation.head()

   order_id  payment_id  delivery_id confirmation_status
0         1           1          NaN           confirmed
1         2           2          NaN           confirmed
2         3           3          NaN       not confirmed
3         4           4          NaN           confirmed
4         5           5          NaN       not confirmed

In [14]:
order_items = pd.read_csv('../Project/Datasets/order_items.csv')
order_items.head()

   quantity  price_at_purchase  order_id  product_id
0         1               1.07         1          36
1         1               4.18         2         188
2         4               0.90         2         115
3         2               6.57         2         135
4         3               4.95         2         106

In [15]:
orders = pd.read_csv('../Project/Datasets/orders.csv')
orders.head()

,order_id,order_type,order_time,order_date,order_status,customer_id,store_id
0,1,Delivery,2026-02-12 05:54:29,2026-02-12,Confirmed,2,8
1,2,Delivery,2026-02-04 13:09:54,2026-02-04,Confirmed,18,3
2,3,Delivery,2026-02-07 03:56:00,2026-02-07,Cancelled,75,9
3,4,Delivery,2026-03-05 10:27:24,2026-03-05,Confirmed,48,4
4,5,Delivery,2026-02-22 00:41:26,2026-02-22,Failed,62,6

In [16]:
payment = pd.read_csv('../Project/Datasets/payments.csv')
payment.head()

,payment_id,payment_method,payment_status,total_amount,payment_date,card_id
0,1,paypal,Success,1.07,2026-02-12,NaN
1,2,credit card,Success,48.45,2026-02-04,18.0
2,3,debit card,Failed,50.12,2026-02-07,75.0
3,4,debit card,Success,20.85,2026-03-05,48.0
4,5,credit card,Failed,35.21,2026-02-22,62.0

In [17]:
product_price = pd.read_csv('../Project/Datasets/product_price.csv')
product_price.head()

,price_id,market_price,current_retail_price,discounted_price,is_discounted,last_update_date,product_id
0,1,4.12,3.78,NaN,no,2026-03-29,1
1,2,6.48,6.21,NaN,no,2026-03-29,2
2,3,5.65,5.12,NaN,no,2026-03-29,3
3,4,2.21,1.55,1.37,yes,2026-03-29,4
4,5,4.91,4.65,NaN,no,2026-03-29,5

In [18]:
delivery_address = pd.read_csv('../Project/Datasets/delivery_address.csv')
delivery_address.head()

            street       city          state country  zip_code  delivery_id
0     474 Broadway    Medford  Massachusetts     USA      2155            1
1       640 Oak St     Quincy  Massachusetts     USA      2169            2
2     990 Cedar St     Boston  Massachusetts     USA      2108            3
3  751 Franklin St     Boston  Massachusetts     USA      2108            4
4     447 River St  Brookline  Massachusetts     USA      2445            5

In [19]:
delivery_details = pd.read_csv('../Project/Datasets/delivery_details.csv')
delivery_details.head()

   delivery_id delivery_status delivery_date
0            1   not delivered    2026-02-15
1            2   not delivered    2026-02-06
2            3   not delivered    2026-02-08
3            4       delivered    2026-03-07
4            5   not delivered    2026-02-25

In [20]:
order_assignment = pd.read_csv('../Project/Datasets/order_assignment.csv')
order_assignment.head()

   assignment_id   assignment_status  manager_id  packer_id  order_id
0              1           confirmed          29         31         1
1              2  Ready for delivery           9         11         2
2              3           confirmed          33         36         3
3              4           delivered          13         15         4
4              5           confirmed          21         23         5

# database connection

In [21]:
import mysql.connector

In [22]:
database = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = 'Bubllo@0299',
    database = 'supermarket'
)

In [23]:
if database.is_connected():
    print("Connected to MySQL database")
else:
    print("Failed to connect to MySQL database")

Connected to MySQL database

## creating cursor to navigate

In [24]:
cursor = database.cursor()

## Display all table

In [25]:
cursor.execute("SHOW TABLES")

In [26]:
for i in cursor:
    print(i)

('card_details',)
('category',)
('customer',)
('customer_address',)
('customer_order',)
('delivery_address',)
('delivery_details',)
('inventory',)
('order_assignment',)
('order_confirmation',)
('order_items',)
('payment',)
('product',)
('product_images',)
('product_price',)
('store_address',)
('store_details',)
('store_manager',)
('store_staff',)
('store_staff_packer',)
('stores',)

## Inserting stores details

In [27]:
store_details

,store_id,store_name,phone,email
0,1,FreshMart Downtown,6175551001,downtown@freshmart.com
1,2,FreshMart Riverside,6175551002,riverside@freshmart.com
2,3,GreenBasket Market,6175551003,hello@greenbasketmarket.com
3,4,UrbanGrocers South End,6175551004,southend@urbangrocers.com
4,5,QuickCart Brookline,6175551005,brookline@quickcart.com
5,6,CityFresh Salem,6175551006,salem@cityfresh.com
6,7,ValueMart Medford,6175551007,medford@valuemart.com
7,8,Neighborhood Market Quincy,6175551008,quincy@neighborhoodmarket.com
8,9,FamilyGrocers Newton,6175551009,newton@familygrocers.com
9,10,SuperSaver Revere,6175551010,revere@supersaver.com

In [28]:
query = "INSERT INTO store_details (store_id, store_name, phone, email) VALUES (%s,%s,%s,%s)"
data = list(store_details.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM store_details")
for i in cursor:
    print(i)

(1, 'FreshMart Downtown', '6175551001', 'downtown@freshmart.com')
(2, 'FreshMart Riverside', '6175551002', 'riverside@freshmart.com')
(3, 'GreenBasket Market', '6175551003', 'hello@greenbasketmarket.com')
(4, 'UrbanGrocers South End', '6175551004', 'southend@urbangrocers.com')
(5, 'QuickCart Brookline', '6175551005', 'brookline@quickcart.com')
(6, 'CityFresh Salem', '6175551006', 'salem@cityfresh.com')
(7, 'ValueMart Medford', '6175551007', 'medford@valuemart.com')
(8, 'Neighborhood Market Quincy', '6175551008', 'quincy@neighborhoodmarket.com')
(9, 'FamilyGrocers Newton', '6175551009', 'newton@familygrocers.com')
(10, 'SuperSaver Revere', '6175551010', 'revere@supersaver.com')

## Store Address

In [29]:
store_address

            street        city          state country  zip_code  store_id
0      101 Main St      Boston  Massachusetts     USA      2108         1
1      22 River Rd   Cambridge  Massachusetts     USA      2139         2
2    15 Beacon Ave  Somerville  Massachusetts     USA      2143         3
3  88 Harrison Ave      Boston  Massachusetts     USA      2118         4
4       200 Elm St   Brookline  Massachusetts     USA      2445         5
5      43 Union St       Salem  Massachusetts     USA      1970         6
6        77 Oak St     Medford  Massachusetts     USA      2155         7
7    19 Walnut Ave      Quincy  Massachusetts     USA      2169         8
8    305 Centre St      Newton  Massachusetts     USA      2458         9
9    12 Harbor Way      Revere  Massachusetts     USA      2151        10

In [30]:
query = "INSERT INTO store_address (Street, City, State, Country, zip_code, store_id) VALUES (%s,%s,%s,%s,%s, %s)"
data = list(store_address.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM store_address")
for i in cursor:
    print(i)

('101 Main St', 'Boston', 'Massachusetts', 'USA', '2108', 1)
('22 River Rd', 'Cambridge', 'Massachusetts', 'USA', '2139', 2)
('15 Beacon Ave', 'Somerville', 'Massachusetts', 'USA', '2143', 3)
('88 Harrison Ave', 'Boston', 'Massachusetts', 'USA', '2118', 4)
('200 Elm St', 'Brookline', 'Massachusetts', 'USA', '2445', 5)
('43 Union St', 'Salem', 'Massachusetts', 'USA', '1970', 6)
('77 Oak St', 'Medford', 'Massachusetts', 'USA', '2155', 7)
('19 Walnut Ave', 'Quincy', 'Massachusetts', 'USA', '2169', 8)
('305 Centre St', 'Newton', 'Massachusetts', 'USA', '2458', 9)
('12 Harbor Way', 'Revere', 'Massachusetts', 'USA', '2151', 10)

In [31]:
inventory

      inventory_id  quantity_available  reorder_level last_updated
0                1                   5              4   2026-03-29
1                2                  36              4   2026-03-29
2                3                  33              4   2026-03-29
3                4                  30              4   2026-03-29
4                5                  24              4   2026-03-29
...            ...                 ...            ...          ...
2395          2396                  48              1   2026-03-29
2396          2397                  26              1   2026-03-29
2397          2398                  34              2   2026-03-29
2398          2399                  49              1   2026-03-29
2399          2400                  59              2   2026-03-29

[2400 rows x 4 columns]

In [32]:
query = "INSERT INTO inventory (inventory_id, quantity_available, reorder_level, last_updated) VALUES (%s,%s,%s,%s)"
data = list(inventory.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM inventory")
for i in cursor:
    print(i)

(1, 5, 4, datetime.date(2026, 3, 29))
(2, 36, 4, datetime.date(2026, 3, 29))
(3, 33, 4, datetime.date(2026, 3, 29))
(4, 30, 4, datetime.date(2026, 3, 29))
(5, 24, 4, datetime.date(2026, 3, 29))
(6, 14, 4, datetime.date(2026, 3, 29))
(7, 31, 4, datetime.date(2026, 3, 29))
(8, 27, 4, datetime.date(2026, 3, 29))
(9, 29, 4, datetime.date(2026, 3, 29))
(10, 25, 4, datetime.date(2026, 3, 29))
(11, 12, 4, datetime.date(2026, 3, 29))
(12, 26, 4, datetime.date(2026, 3, 29))
(13, 5, 4, datetime.date(2026, 3, 29))
(14, 25, 4, datetime.date(2026, 3, 29))
(15, 26, 4, datetime.date(2026, 3, 29))
(16, 30, 4, datetime.date(2026, 3, 29))
(17, 12, 4, datetime.date(2026, 3, 29))
(18, 17, 4, datetime.date(2026, 3, 29))
(19, 5, 4, datetime.date(2026, 3, 29))
(20, 23, 4, datetime.date(2026, 3, 29))
(21, 21, 4, datetime.date(2026, 3, 29))
(22, 28, 4, datetime.date(2026, 3, 29))
(23, 9, 4, datetime.date(2026, 3, 29))
(24, 30, 4, datetime.date(2026, 3, 29))
(25, 29, 4, datetime.date(2026, 3, 29))
(26, 9, 4, datetime.date(2026, 3, 29))
(27, 28, 4, datetime.date(2026, 3, 29))
(28, 32, 4, datetime.date(2026, 3, 29))
(29, 22, 4, datetime.date(2026, 3, 29))
(30, 8, 4, datetime.date(2026, 3, 29))
(31, 22, 4, datetime.date(2026, 3, 29))
(32, 11, 4, datetime.date(2026, 3, 29))
(33, 8, 4, datetime.date(2026, 3, 29))
(34, 23, 4, datetime.date(2026, 3, 29))
(35, 14, 4, datetime.date(2026, 3, 29))
(36, 20, 4, datetime.date(2026, 3, 29))
(37, 22, 4, datetime.date(2026, 3, 29))
(38, 32, 4, datetime.date(2026, 3, 29))
(39, 37, 4, datetime.date(2026, 3, 29))
(40, 25, 4, datetime.date(2026, 3, 29))
(41, 17, 4, datetime.date(2026, 3, 29))
(42, 28, 4, datetime.date(2026, 3, 29))
(43, 32, 4, datetime.date(2026, 3, 29))
(44, 6, 4, datetime.date(2026, 3, 29))
(45, 30, 4, datetime.date(2026, 3, 29))
(46, 18, 4, datetime.date(2026, 3, 29))
(47, 10, 4, datetime.date(2026, 3, 29))
(48, 8, 4, datetime.date(2026, 3, 29))
(49, 31, 4, datetime.date(2026, 3, 29))
(50, 33, 4, datetime.date(2026, 3, 29))
(51, 13, 4, datetime.date(2026, 3, 29))
(52, 23, 4, datetime.date(2026, 3, 29))
(53, 36, 4, datetime.date(2026, 3, 29))
(54, 8, 4, datetime.date(2026, 3, 29))
(55, 13, 4, datetime.date(2026, 3, 29))
(56, 15, 4, datetime.date(2026, 3, 29))
(57, 35, 4, datetime.date(2026, 3, 29))
(58, 31, 4, datetime.date(2026, 3, 29))
(59, 26, 4, datetime.date(2026, 3, 29))
(60, 23, 4, datetime.date(2026, 3, 29))
(61, 2, 4, datetime.date(2026, 3, 29))
(62, 21, 4, datetime.date(2026, 3, 29))
(63, 30, 4, datetime.date(2026, 3, 29))
(64, 20, 4, datetime.date(2026, 3, 29))
(65, 24, 4, datetime.date(2026, 3, 29))
(66, 35, 4, datetime.date(2026, 3, 29))
(67, 30, 4, datetime.date(2026, 3, 29))
(68, 12, 4, datetime.date(2026, 3, 29))
(69, 15, 4, datetime.date(2026, 3, 29))
(70, 15, 4, datetime.date(2026, 3, 29))
(71, 9, 4, datetime.date(2026, 3, 29))
(72, 18, 4, datetime.date(2026, 3, 29))
(73, 37, 4, datetime.date(2026, 3, 29))
(74, 36, 4, datetime.date(2026, 3, 29))
(75, 19, 4, datetime.date(2026, 3, 29))
(76, 33, 4, datetime.date(2026, 3, 29))
(77, 26, 4, datetime.date(2026, 3, 29))
(78, 33, 4, datetime.date(2026, 3, 29))
(79, 32, 4, datetime.date(2026, 3, 29))
(80, 13, 4, datetime.date(2026, 3, 29))
(81, 17, 4, datetime.date(2026, 3, 29))
(82, 20, 4, datetime.date(2026, 3, 29))
(83, 10, 4, datetime.date(2026, 3, 29))
(84, 16, 4, datetime.date(2026, 3, 29))
(85, 26, 4, datetime.date(2026, 3, 29))
(86, 10, 4, datetime.date(2026, 3, 29))
(87, 25, 4, datetime.date(2026, 3, 29))
(88, 20, 4, datetime.date(2026, 3, 29))
(89, 28, 4, datetime.date(2026, 3, 29))
(90, 21, 4, datetime.date(2026, 3, 29))
(91, 17, 4, datetime.date(2026, 3, 29))
(92, 6, 4, datetime.date(2026, 3, 29))
(93, 31, 4, datetime.date(2026, 3, 29))
(94, 29, 4, datetime.date(2026, 3, 29))
(95, 31, 4, datetime.date(2026, 3, 29))
(96, 38, 4, datetime.date(2026, 3, 29))
(97, 18, 4, datetime.date(2026, 3, 29))
(98, 29, 4, datetime.date(2026, 3, 29))
(99, 22, 4, datetime.date(2026, 3, 29))
(100, 26, 4, datetime.date(2026, 3, 29))
(101, 56, 1, datetime.date(2026, 3, 29))
(102, 39, 2, datetime.date(2026, 3, 29))
(103, 44, 2, datetime.date(2026, 3, 29))
(104, 16, 1, datetime.date(2026, 3, 29))
(105, 13, 2, datetime.date(2026, 3, 29))
(106, 65, 1, datetime.date(2026, 3, 29))
(107, 32, 2, datetime.date(2026, 3, 29))
(108, 49, 2, datetime.date(2026, 3, 29))
(109, 35, 2, datetime.date(2026, 3, 29))
(110, 62, 1, datetime.date(2026, 3, 29))
(111, 16, 1, datetime.date(2026, 3, 29))
(112, 35, 2, datetime.date(2026, 3, 29))
(113, 45, 2, datetime.date(2026, 3, 29))
(114, 8, 1, datetime.date(2026, 3, 29))
(115, 33, 2, datetime.date(2026, 3, 29))
(116, 36, 1, datetime.date(2026, 3, 29))
(117, 58, 1, datetime.date(2026, 3, 29))
(118, 22, 1, datetime.date(2026, 3, 29))
(119, 17, 1, datetime.date(2026, 3, 29))
(120, 60, 2, datetime.date(2026, 3, 29))
(121, 13, 1, datetime.date(2026, 3, 29))
(122, 0, 1, datetime.date(2026, 3, 29))
(123, 44, 1, datetime.date(2026, 3, 29))
(124, 49, 2, datetime.date(2026, 3, 29))
(125, 16, 2, datetime.date(2026, 3, 29))
(126, 41, 2, datetime.date(2026, 3, 29))
(127, 52, 1, datetime.date(2026, 3, 29))
(128, 14, 1, datetime.date(2026, 3, 29))
(129, 27, 1, datetime.date(2026, 3, 29))
(130, 32, 2, datetime.date(2026, 3, 29))
(131, 22, 1, datetime.date(2026, 3, 29))
(132, 8, 2, datetime.date(2026, 3, 29))
(133, 37, 2, datetime.date(2026, 3, 29))
(134, 28, 1, datetime.date(2026, 3, 29))
(135, 38, 1, datetime.date(2026, 3, 29))
(136, 43, 1, datetime.date(2026, 3, 29))
(137, 9, 2, datetime.date(2026, 3, 29))
(138, 53, 2, datetime.date(2026, 3, 29))
(139, 11, 1, datetime.date(2026, 3, 29))
(140, 20, 2, datetime.date(2026, 3, 29))
(141, 31, 4, datetime.date(2026, 3, 29))
(142, 10, 4, datetime.date(2026, 3, 29))
(143, 21, 4, datetime.date(2026, 3, 29))
(144, 19, 4, datetime.date(2026, 3, 29))
(145, 32, 4, datetime.date(2026, 3, 29))
(146, 28, 4, datetime.date(2026, 3, 29))
(147, 19, 4, datetime.date(2026, 3, 29))
(148, 36, 4, datetime.date(2026, 3, 29))
(149, 7, 4, datetime.date(2026, 3, 29))
(150, 26, 4, datetime.date(2026, 3, 29))
(151, 31, 4, datetime.date(2026, 3, 29))
(152, 28, 4, datetime.date(2026, 3, 29))
(153, 30, 4, datetime.date(2026, 3, 29))
(154, 17, 4, datetime.date(2026, 3, 29))
(155, 5, 4, datetime.date(2026, 3, 29))
(156, 23, 4, datetime.date(2026, 3, 29))
(157, 37, 4, datetime.date(2026, 3, 29))
(158, 9, 4, datetime.date(2026, 3, 29))
(159, 18, 4, datetime.date(2026, 3, 29))
(160, 36, 4, datetime.date(2026, 3, 29))
(161, 20, 2, datetime.date(2026, 3, 29))
(162, 57, 1, datetime.date(2026, 3, 29))
(163, 22, 2, datetime.date(2026, 3, 29))
(164, 22, 2, datetime.date(2026, 3, 29))
(165, 56, 2, datetime.date(2026, 3, 29))
(166, 14, 2, datetime.date(2026, 3, 29))
(167, 47, 1, datetime.date(2026, 3, 29))
(168, 65, 1, datetime.date(2026, 3, 29))
(169, 39, 2, datetime.date(2026, 3, 29))
(170, 50, 1, datetime.date(2026, 3, 29))
(171, 46, 1, datetime.date(2026, 3, 29))
(172, 33, 1, datetime.date(2026, 3, 29))
(173, 21, 1, datetime.date(2026, 3, 29))
(174, 46, 1, datetime.date(2026, 3, 29))
(175, 34, 1, datetime.date(2026, 3, 29))
(176, 53, 1, datetime.date(2026, 3, 29))
(177, 19, 2, datetime.date(2026, 3, 29))
(178, 36, 2, datetime.date(2026, 3, 29))
(179, 54, 1, datetime.date(2026, 3, 29))
(180, 13, 1, datetime.date(2026, 3, 29))
(181, 29, 1, datetime.date(2026, 3, 29))
(182, 19, 2, datetime.date(2026, 3, 29))
(183, 1, 2, datetime.date(2026, 3, 29))
(184, 61, 2, datetime.date(2026, 3, 29))
(185, 29, 2, datetime.date(2026, 3, 29))
(186, 18, 1, datetime.date(2026, 3, 29))
(187, 8, 1, datetime.date(2026, 3, 29))
(188, 25, 1, datetime.date(2026, 3, 29))
(189, 30, 2, datetime.date(2026, 3, 29))
(190, 64, 1, datetime.date(2026, 3, 29))
(191, 43, 1, datetime.date(2026, 3, 29))
(192, 32, 2, datetime.date(2026, 3, 29))
(193, 57, 2, datetime.date(2026, 3, 29))
(194, 60, 2, datetime.date(2026, 3, 29))
(195, 13, 1, datetime.date(2026, 3, 29))
(196, 53, 2, datetime.date(2026, 3, 29))
(197, 20, 2, datetime.date(2026, 3, 29))
(198, 42, 2, datetime.date(2026, 3, 29))
(199, 20, 2, datetime.date(2026, 3, 29))
(200, 31, 2, datetime.date(2026, 3, 29))
(201, 9, 2, datetime.date(2026, 3, 29))
(202, 23, 2, datetime.date(2026, 3, 29))
(203, 10, 2, datetime.date(2026, 3, 29))
(204, 10, 2, datetime.date(2026, 3, 29))
(205, 12, 1, datetime.date(2026, 3, 29))
(206, 24, 1, datetime.date(2026, 3, 29))
(207, 55, 1, datetime.date(2026, 3, 29))
(208, 65, 2, datetime.date(2026, 3, 29))
(209, 31, 2, datetime.date(2026, 3, 29))
(210, 29, 1, datetime.date(2026, 3, 29))
(211, 24, 2, datetime.date(2026, 3, 29))
(212, 25, 2, datetime.date(2026, 3, 29))
(213, 8, 1, datetime.date(2026, 3, 29))
(214, 9, 1, datetime.date(2026, 3, 29))
(215, 14, 2, datetime.date(2026, 3, 29))
(216, 53, 2, datetime.date(2026, 3, 29))
(217, 57, 2, datetime.date(2026, 3, 29))
(218, 58, 2, datetime.date(2026, 3, 29))
(219, 35, 2, datetime.date(2026, 3, 29))
(220, 16, 2, datetime.date(2026, 3, 29))
(221, 19, 1, datetime.date(2026, 3, 29))
(222, 59, 2, datetime.date(2026, 3, 29))
(223, 60, 1, datetime.date(2026, 3, 29))
(224, 46, 1, datetime.date(2026, 3, 29))
(225, 28, 2, datetime.date(2026, 3, 29))
(226, 37, 2, datetime.date(2026, 3, 29))
(227, 58, 1, datetime.date(2026, 3, 29))
(228, 40, 1, datetime.date(2026, 3, 29))
(229, 33, 1, datetime.date(2026, 3, 29))
(230, 23, 2, datetime.date(2026, 3, 29))
(231, 12, 1, datetime.date(2026, 3, 29))
(232, 38, 2, datetime.date(2026, 3, 29))
(233, 18, 2, datetime.date(2026, 3, 29))
(234, 64, 1, datetime.date(2026, 3, 29))
(235, 12, 2, datetime.date(2026, 3, 29))
(236, 47, 1, datetime.date(2026, 3, 29))
(237, 21, 1, datetime.date(2026, 3, 29))
(238, 34, 2, datetime.date(2026, 3, 29))
(239, 53, 2, datetime.date(2026, 3, 29))
(240, 19, 1, datetime.date(2026, 3, 29))
(241, 13, 4, datetime.date(2026, 3, 29))
(242, 31, 4, datetime.date(2026, 3, 29))
(243, 34, 4, datetime.date(2026, 3, 29))
(244, 20, 4, datetime.date(2026, 3, 29))
(245, 12, 4, datetime.date(2026, 3, 29))
(246, 23, 4, datetime.date(2026, 3, 29))
(247, 23, 4, datetime.date(2026, 3, 29))
(248, 22, 4, datetime.date(2026, 3, 29))
(249, 22, 4, datetime.date(2026, 3, 29))
(250, 28, 4, datetime.date(2026, 3, 29))
(251, 21, 4, datetime.date(2026, 3, 29))
(252, 21, 4, datetime.date(2026, 3, 29))
(253, 17, 4, datetime.date(2026, 3, 29))
(254, 33, 4, datetime.date(2026, 3, 29))
(255, 20, 4, datetime.date(2026, 3, 29))
(256, 16, 4, datetime.date(2026, 3, 29))
(257, 20, 4, datetime.date(2026, 3, 29))
(258, 20, 4, datetime.date(2026, 3, 29))
(259, 14, 4, datetime.date(2026, 3, 29))
(260, 23, 4, datetime.date(2026, 3, 29))
(261, 17, 4, datetime.date(2026, 3, 29))
(262, 25, 4, datetime.date(2026, 3, 29))
(263, 9, 4, datetime.date(2026, 3, 29))
(264, 30, 4, datetime.date(2026, 3, 29))
(265, 21, 4, datetime.date(2026, 3, 29))
(266, 20, 4, datetime.date(2026, 3, 29))
(267, 37, 4, datetime.date(2026, 3, 29))
(268, 38, 4, datetime.date(2026, 3, 29))
(269, 19, 4, datetime.date(2026, 3, 29))
(270, 11, 4, datetime.date(2026, 3, 29))
(271, 34, 4, datetime.date(2026, 3, 29))
(272, 7, 4, datetime.date(2026, 3, 29))
(273, 11, 4, datetime.date(2026, 3, 29))
(274, 5, 4, datetime.date(2026, 3, 29))
(275, 35, 4, datetime.date(2026, 3, 29))
(276, 19, 4, datetime.date(2026, 3, 29))
(277, 33, 4, datetime.date(2026, 3, 29))
(278, 28, 4, datetime.date(2026, 3, 29))
(279, 7, 4, datetime.date(2026, 3, 29))
(280, 23, 4, datetime.date(2026, 3, 29))
(281, 19, 4, datetime.date(2026, 3, 29))
(282, 12, 4, datetime.date(2026, 3, 29))
(283, 8, 4, datetime.date(2026, 3, 29))
(284, 17, 4, datetime.date(2026, 3, 29))
(285, 17, 4, datetime.date(2026, 3, 29))
(286, 9, 4, datetime.date(2026, 3, 29))
(287, 28, 4, datetime.date(2026, 3, 29))
(288, 37, 4, datetime.date(2026, 3, 29))
(289, 16, 4, datetime.date(2026, 3, 29))
(290, 33, 4, datetime.date(2026, 3, 29))
(291, 21, 4, datetime.date(2026, 3, 29))
(292, 5, 4, datetime.date(2026, 3, 29))
(293, 11, 4, datetime.date(2026, 3, 29))
(294, 27, 4, datetime.date(2026, 3, 29))
(295, 18, 4, datetime.date(2026, 3, 29))
(296, 7, 4, datetime.date(2026, 3, 29))
(297, 28, 4, datetime.date(2026, 3, 29))
(298, 26, 4, datetime.date(2026, 3, 29))
(299, 14, 4, datetime.date(2026, 3, 29))
(300, 7, 4, datetime.date(2026, 3, 29))
(301, 2, 4, datetime.date(2026, 3, 29))
(302, 7, 4, datetime.date(2026, 3, 29))
(303, 18, 4, datetime.date(2026, 3, 29))
(304, 5, 4, datetime.date(2026, 3, 29))
(305, 25, 4, datetime.date(2026, 3, 29))
(306, 31, 4, datetime.date(2026, 3, 29))
(307, 28, 4, datetime.date(2026, 3, 29))
(308, 16, 4, datetime.date(2026, 3, 29))
(309, 24, 4, datetime.date(2026, 3, 29))
(310, 9, 4, datetime.date(2026, 3, 29))
(311, 18, 4, datetime.date(2026, 3, 29))
(312, 7, 4, datetime.date(2026, 3, 29))
(313, 36, 4, datetime.date(2026, 3, 29))
(314, 35, 4, datetime.date(2026, 3, 29))
(315, 9, 4, datetime.date(2026, 3, 29))
(316, 31, 4, datetime.date(2026, 3, 29))
(317, 11, 4, datetime.date(2026, 3, 29))
(318, 30, 4, datetime.date(2026, 3, 29))
(319, 14, 4, datetime.date(2026, 3, 29))
(320, 10, 4, datetime.date(2026, 3, 29))
(321, 15, 4, datetime.date(2026, 3, 29))
(322, 30, 4, datetime.date(2026, 3, 29))
(323, 22, 4, datetime.date(2026, 3, 29))
(324, 31, 4, datetime.date(2026, 3, 29))
(325, 23, 4, datetime.date(2026, 3, 29))
(326, 24, 4, datetime.date(2026, 3, 29))
(327, 31, 4, datetime.date(2026, 3, 29))
(328, 8, 4, datetime.date(2026, 3, 29))
(329, 24, 4, datetime.date(2026, 3, 29))
(330, 27, 4, datetime.date(2026, 3, 29))
(331, 31, 4, datetime.date(2026, 3, 29))
(332, 31, 4, datetime.date(2026, 3, 29))
(333, 6, 4, datetime.date(2026, 3, 29))
(334, 28, 4, datetime.date(2026, 3, 29))
(335, 17, 4, datetime.date(2026, 3, 29))
(336, 30, 4, datetime.date(2026, 3, 29))
(337, 30, 4, datetime.date(2026, 3, 29))
(338, 18, 4, datetime.date(2026, 3, 29))
(339, 5, 4, datetime.date(2026, 3, 29))
(340, 32, 4, datetime.date(2026, 3, 29))
(341, 65, 1, datetime.date(2026, 3, 29))
(342, 35, 1, datetime.date(2026, 3, 29))
(343, 60, 1, datetime.date(2026, 3, 29))
(344, 33, 2, datetime.date(2026, 3, 29))
(345, 37, 1, datetime.date(2026, 3, 29))
(346, 16, 1, datetime.date(2026, 3, 29))
(347, 11, 1, datetime.date(2026, 3, 29))
(348, 49, 2, datetime.date(2026, 3, 29))
(349, 13, 2, datetime.date(2026, 3, 29))
(350, 55, 1, datetime.date(2026, 3, 29))
(351, 17, 2, datetime.date(2026, 3, 29))
(352, 26, 1, datetime.date(2026, 3, 29))
(353, 41, 1, datetime.date(2026, 3, 29))
(354, 12, 1, datetime.date(2026, 3, 29))
(355, 32, 2, datetime.date(2026, 3, 29))
(356, 56, 1, datetime.date(2026, 3, 29))
(357, 27, 1, datetime.date(2026, 3, 29))
(358, 61, 1, datetime.date(2026, 3, 29))
(359, 38, 2, datetime.date(2026, 3, 29))
(360, 11, 2, datetime.date(2026, 3, 29))
(361, 13, 1, datetime.date(2026, 3, 29))
(362, 1, 1, datetime.date(2026, 3, 29))
(363, 47, 1, datetime.date(2026, 3, 29))
(364, 61, 2, datetime.date(2026, 3, 29))
(365, 19, 1, datetime.date(2026, 3, 29))
(366, 10, 2, datetime.date(2026, 3, 29))
(367, 41, 1, datetime.date(2026, 3, 29))
(368, 32, 2, datetime.date(2026, 3, 29))
(369, 15, 1, datetime.date(2026, 3, 29))
(370, 23, 1, datetime.date(2026, 3, 29))
(371, 10, 1, datetime.date(2026, 3, 29))
(372, 50, 2, datetime.date(2026, 3, 29))
(373, 15, 2, datetime.date(2026, 3, 29))
(374, 46, 2, datetime.date(2026, 3, 29))
(375, 43, 2, datetime.date(2026, 3, 29))
(376, 49, 2, datetime.date(2026, 3, 29))
(377, 27, 1, datetime.date(2026, 3, 29))
(378, 35, 2, datetime.date(2026, 3, 29))
(379, 50, 2, datetime.date(2026, 3, 29))
(380, 36, 2, datetime.date(2026, 3, 29))
(381, 16, 4, datetime.date(2026, 3, 29))
(382, 6, 4, datetime.date(2026, 3, 29))
(383, 5, 4, datetime.date(2026, 3, 29))
(384, 36, 4, datetime.date(2026, 3, 29))
(385, 34, 4, datetime.date(2026, 3, 29))
(386, 20, 4, datetime.date(2026, 3, 29))
(387, 33, 4, datetime.date(2026, 3, 29))
(388, 34, 4, datetime.date(2026, 3, 29))
(389, 16, 4, datetime.date(2026, 3, 29))
(390, 35, 4, datetime.date(2026, 3, 29))
(391, 30, 4, datetime.date(2026, 3, 29))
(392, 11, 4, datetime.date(2026, 3, 29))
(393, 9, 4, datetime.date(2026, 3, 29))
(394, 13, 4, datetime.date(2026, 3, 29))
(395, 27, 4, datetime.date(2026, 3, 29))
(396, 32, 4, datetime.date(2026, 3, 29))
(397, 28, 4, datetime.date(2026, 3, 29))
(398, 10, 4, datetime.date(2026, 3, 29))
(399, 33, 4, datetime.date(2026, 3, 29))
(400, 37, 4, datetime.date(2026, 3, 29))
(401, 40, 1, datetime.date(2026, 3, 29))
(402, 10, 1, datetime.date(2026, 3, 29))
(403, 13, 2, datetime.date(2026, 3, 29))
(404, 57, 1, datetime.date(2026, 3, 29))
(405, 11, 2, datetime.date(2026, 3, 29))
(406, 49, 1, datetime.date(2026, 3, 29))
(407, 9, 1, datetime.date(2026, 3, 29))
(408, 47, 1, datetime.date(2026, 3, 29))
(409, 20, 1, datetime.date(2026, 3, 29))
(410, 64, 2, datetime.date(2026, 3, 29))
(411, 26, 1, datetime.date(2026, 3, 29))
(412, 51, 1, datetime.date(2026, 3, 29))
(413, 12, 2, datetime.date(2026, 3, 29))
(414, 47, 2, datetime.date(2026, 3, 29))
(415, 18, 2, datetime.date(2026, 3, 29))
(416, 65, 2, datetime.date(2026, 3, 29))
(417, 65, 2, datetime.date(2026, 3, 29))
(418, 17, 2, datetime.date(2026, 3, 29))
(419, 40, 2, datetime.date(2026, 3, 29))
(420, 21, 2, datetime.date(2026, 3, 29))
(421, 47, 1, datetime.date(2026, 3, 29))
(422, 28, 2, datetime.date(2026, 3, 29))
(423, 0, 1, datetime.date(2026, 3, 29))
(424, 33, 1, datetime.date(2026, 3, 29))
(425, 48, 2, datetime.date(2026, 3, 29))
(426, 51, 2, datetime.date(2026, 3, 29))
(427, 65, 2, datetime.date(2026, 3, 29))
(428, 18, 2, datetime.date(2026, 3, 29))
(429, 15, 1, datetime.date(2026, 3, 29))
(430, 48, 2, datetime.date(2026, 3, 29))
(431, 63, 2, datetime.date(2026, 3, 29))
(432, 43, 1, datetime.date(2026, 3, 29))
(433, 24, 2, datetime.date(2026, 3, 29))
(434, 55, 2, datetime.date(2026, 3, 29))
(435, 24, 2, datetime.date(2026, 3, 29))
(436, 31, 1, datetime.date(2026, 3, 29))
(437, 31, 2, datetime.date(2026, 3, 29))
(438, 56, 1, datetime.date(2026, 3, 29))
(439, 36, 1, datetime.date(2026, 3, 29))
(440, 19, 1, datetime.date(2026, 3, 29))
(441, 26, 2, datetime.date(2026, 3, 29))
(442, 27, 2, datetime.date(2026, 3, 29))
(443, 54, 1, datetime.date(2026, 3, 29))
(444, 55, 1, datetime.date(2026, 3, 29))
(445, 22, 1, datetime.date(2026, 3, 29))
(446, 26, 2, datetime.date(2026, 3, 29))
(447, 34, 2, datetime.date(2026, 3, 29))
(448, 65, 1, datetime.date(2026, 3, 29))
(449, 16, 2, datetime.date(2026, 3, 29))
(450, 22, 1, datetime.date(2026, 3, 29))
(451, 9, 1, datetime.date(2026, 3, 29))
(452, 8, 2, datetime.date(2026, 3, 29))
(453, 27, 1, datetime.date(2026, 3, 29))
(454, 41, 2, datetime.date(2026, 3, 29))
(455, 42, 1, datetime.date(2026, 3, 29))
(456, 34, 2, datetime.date(2026, 3, 29))
(457, 45, 1, datetime.date(2026, 3, 29))
(458, 21, 2, datetime.date(2026, 3, 29))
(459, 47, 2, datetime.date(2026, 3, 29))
(460, 18, 1, datetime.date(2026, 3, 29))
(461, 8, 1, datetime.date(2026, 3, 29))
(462, 53, 1, datetime.date(2026, 3, 29))
(463, 36, 1, datetime.date(2026, 3, 29))
(464, 12, 1, datetime.date(2026, 3, 29))
(465, 63, 2, datetime.date(2026, 3, 29))
(466, 33, 2, datetime.date(2026, 3, 29))
(467, 8, 1, datetime.date(2026, 3, 29))
(468, 49, 2, datetime.date(2026, 3, 29))
(469, 46, 2, datetime.date(2026, 3, 29))
(470, 46, 2, datetime.date(2026, 3, 29))
(471, 23, 1, datetime.date(2026, 3, 29))
(472, 65, 1, datetime.date(2026, 3, 29))
(473, 10, 1, datetime.date(2026, 3, 29))
(474, 42, 1, datetime.date(2026, 3, 29))
(475, 33, 1, datetime.date(2026, 3, 29))
(476, 23, 1, datetime.date(2026, 3, 29))
(477, 11, 1, datetime.date(2026, 3, 29))
(478, 8, 1, datetime.date(2026, 3, 29))
(479, 17, 2, datetime.date(2026, 3, 29))
(480, 20, 2, datetime.date(2026, 3, 29))
(481, 16, 4, datetime.date(2026, 3, 29))
(482, 37, 4, datetime.date(2026, 3, 29))
(483, 24, 4, datetime.date(2026, 3, 29))
(484, 9, 4, datetime.date(2026, 3, 29))
(485, 24, 4, datetime.date(2026, 3, 29))
(486, 8, 4, datetime.date(2026, 3, 29))
(487, 35, 4, datetime.date(2026, 3, 29))
(488, 5, 4, datetime.date(2026, 3, 29))
(489, 29, 4, datetime.date(2026, 3, 29))
(490, 32, 4, datetime.date(2026, 3, 29))
(491, 34, 4, datetime.date(2026, 3, 29))

In [33]:
product

,product_id,product_name,product_barcode,product_description,category_id
0,1,Banana Bunch,100000000001,Fresh yellow bananas,1
1,2,Gala Apples 3 lb,100000000002,Sweet gala apples bag,1
2,3,Fuji Apples 3 lb,100000000003,Crisp fuji apples bag,1
3,4,Navel Oranges 4 lb,100000000004,Juicy navel oranges bag,1
4,5,Red Seedless Grapes 2 lb,100000000005,Seedless red grapes,1
...,...,...,...,...,...
235,236,Bran Crunch Cereal 16 oz,100000000236,Bran cereal,12
236,237,Cinnamon Bagel Chips 7 oz,100000000237,Crunchy bagel chips,12
237,238,Honey Breakfast Biscuits 5 ct,100000000238,Breakfast biscuits,12
238,239,Chia Oat Cups 4 ct,100000000239,Ready breakfast cups,12
239,240,Protein Pancake Mix 20 oz,100000000240,Protein pancake mix,12

## categories

In [34]:
category

,category_id,category_name,category_description
0,1,Fruits,Fresh seasonal fruits
1,2,Vegetables,Fresh produce and leafy greens
2,3,Dairy,"Milk, yogurt, eggs, cheese, and butter"
3,4,Bakery,"Fresh breads, rolls, muffins, and pastries"
4,5,Meat & Seafood,White meat and seafood only
5,6,Beverages,"Juices, water, coffee, tea, and soft drinks"
6,7,Snacks,"Chips, crackers, bars, cookies, and treats"
7,8,Frozen Foods,"Frozen meals, vegetables, desserts, and breakf..."
8,9,Household,Cleaning supplies and home essentials
9,10,Personal Care,Daily hygiene and health essentials
10,11,Pantry Staples,"Cooking oils, grains, canned goods, and spreads"
11,12,Breakfast & Cereals,"Cereal, oats, syrups, and breakfast pantry items"

In [35]:
query = "INSERT INTO category(category_id, category_name, category_description) VALUES (%s,%s,%s)"
data = list(category.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM category")
for i in cursor:
    print(i)

(1, 'Fruits', 'Fresh seasonal fruits')
(2, 'Vegetables', 'Fresh produce and leafy greens')
(3, 'Dairy', 'Milk, yogurt, eggs, cheese, and butter')
(4, 'Bakery', 'Fresh breads, rolls, muffins, and pastries')
(5, 'Meat & Seafood', 'White meat and seafood only')
(6, 'Beverages', 'Juices, water, coffee, tea, and soft drinks')
(7, 'Snacks', 'Chips, crackers, bars, cookies, and treats')
(8, 'Frozen Foods', 'Frozen meals, vegetables, desserts, and breakfast items')
(9, 'Household', 'Cleaning supplies and home essentials')
(10, 'Personal Care', 'Daily hygiene and health essentials')
(11, 'Pantry Staples', 'Cooking oils, grains, canned goods, and spreads')
(12, 'Breakfast & Cereals', 'Cereal, oats, syrups, and breakfast pantry items')

## Product

In [36]:
query = "INSERT INTO product (product_id, product_name, product_barcode, product_description, category_id) VALUES (%s,%s,%s,%s,%s)"
data = list(product.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM product")
for i in cursor:
    print(i)

(1, 'Banana Bunch', '100000000001', 'Fresh yellow bananas', 1)
(2, 'Gala Apples 3 lb', '100000000002', 'Sweet gala apples bag', 1)
(3, 'Fuji Apples 3 lb', '100000000003', 'Crisp fuji apples bag', 1)
(4, 'Navel Oranges 4 lb', '100000000004', 'Juicy navel oranges bag', 1)
(5, 'Red Seedless Grapes 2 lb', '100000000005', 'Seedless red grapes', 1)
(6, 'Green Seedless Grapes 2 lb', '100000000006', 'Seedless green grapes', 1)
(7, 'Strawberries 1 lb', '100000000007', 'Fresh strawberries', 1)
(8, 'Blueberries 1 pint', '100000000008', 'Fresh blueberries', 1)
(9, 'Raspberries 6 oz', '100000000009', 'Fresh raspberries', 1)
(10, 'Blackberries 6 oz', '100000000010', 'Fresh blackberries', 1)
(11, 'Ataulfo Mango', '100000000011', 'Sweet ripe mango', 1)
(12, 'Pineapple Whole', '100000000012', 'Whole ripe pineapple', 1)
(13, 'Mini Watermelon', '100000000013', 'Seedless mini watermelon', 1)
(14, 'Cantaloupe Whole', '100000000014', 'Fresh cantaloupe', 1)
(15, 'Honeydew Melon', '100000000015', 'Sweet honeydew melon', 1)
(16, 'Bartlett Pears 2 lb', '100000000016', 'Fresh bartlett pears', 1)
(17, 'Yellow Peaches 2 lb', '100000000017', 'Juicy yellow peaches', 1)
(18, 'Black Plums 2 lb', '100000000018', 'Sweet black plums', 1)
(19, 'Kiwi 4 ct', '100000000019', 'Kiwi fruit pack', 1)
(20, 'Lemons 2 lb', '100000000020', 'Fresh lemons bag', 1)
(21, 'Roma Tomatoes 1 lb', '100000000021', 'Fresh roma tomatoes', 2)
(22, 'Vine Tomatoes 1 lb', '100000000022', 'Fresh vine-ripened tomatoes', 2)
(23, 'Baby Spinach 5 oz', '100000000023', 'Washed baby spinach', 2)
(24, 'Romaine Hearts 3 ct', '100000000024', 'Fresh romaine hearts', 2)
(25, 'Broccoli Crowns', '100000000025', 'Fresh broccoli crowns', 2)
(26, 'Cauliflower Head', '100000000026', 'Fresh cauliflower head', 2)
(27, 'Carrots 2 lb', '100000000027', 'Whole carrots bag', 2)
(28, 'Celery Bunch', '100000000028', 'Fresh celery bunch', 2)
(29, 'English Cucumber', '100000000029', 'Long seedless cucumber', 2)
(30, 'Red Bell Pepper', '100000000030', 'Fresh red bell pepper', 2)
(31, 'Green Bell Pepper', '100000000031', 'Fresh green bell pepper', 2)
(32, 'Yellow Onions 3 lb', '100000000032', 'Yellow onions bag', 2)
(33, 'Garlic Bulb', '100000000033', 'Whole garlic bulb', 2)
(34, 'Russet Potatoes 5 lb', '100000000034', 'Russet potatoes bag', 2)
(35, 'Sweet Potatoes 3 lb', '100000000035', 'Sweet potatoes bag', 2)
(36, 'Zucchini 1 lb', '100000000036', 'Fresh zucchini squash', 2)
(37, 'White Mushrooms 8 oz', '100000000037', 'Sliced white mushrooms', 2)
(38, 'Green Beans 12 oz', '100000000038', 'Fresh green beans', 2)
(39, 'Sweet Corn 4 ct', '100000000039', 'Fresh sweet corn', 2)
(40, 'Green Cabbage', '100000000040', 'Whole green cabbage', 2)
(41, 'Whole Milk 1 gal', '100000000041', 'Whole milk gallon jug', 3)
(42, '2% Milk 1 gal', '100000000042', 'Reduced fat milk gallon jug', 3)
(43, 'Skim Milk 1 gal', '100000000043', 'Fat free milk gallon jug', 3)
(44, 'Plain Greek Yogurt 32 oz', '100000000044', 'Plain greek yogurt tub', 3)
(45, 'Vanilla Greek Yogurt 32 oz', '100000000045', 'Vanilla greek yogurt tub', 3)
(46, 'Sharp Cheddar Block 8 oz', '100000000046', 'Sharp cheddar cheese', 3)
(47, 'Shredded Mozzarella 8 oz', '100000000047', 'Mozzarella cheese shreds', 3)
(48, 'Grated Parmesan 8 oz', '100000000048', 'Grated parmesan cheese', 3)
(49, 'Salted Butter 16 oz', '100000000049', 'Salted butter sticks', 3)
(50, 'Unsalted Butter 16 oz', '100000000050', 'Unsalted butter sticks', 3)
(51, 'Large Eggs 12 ct', '100000000051', 'Grade A large eggs', 3)
(52, 'Egg Whites 16 oz', '100000000052', 'Liquid egg whites', 3)
(53, 'Sour Cream 16 oz', '100000000053', 'Cultured sour cream', 3)
(54, 'Cream Cheese 8 oz', '100000000054', 'Original cream cheese', 3)
(55, 'Heavy Whipping Cream 16 oz', '100000000055', 'Heavy cream', 3)
(56, 'Half & Half 32 oz', '100000000056', 'Half and half carton', 3)
(57, 'Low Fat Cottage Cheese 24 oz', '100000000057', 'Low fat cottage cheese', 3)
(58, 'Fruit Yogurt 4 ct', '100000000058', 'Assorted yogurt cups', 3)
(59, 'Chocolate Milk 1 qt', '100000000059', 'Chocolate milk carton', 3)
(60, 'String Cheese 12 ct', '100000000060', 'Mozzarella string cheese', 3)
(61, 'Whole Wheat Bread Loaf', '100000000061', 'Fresh whole wheat bread', 4)
(62, 'White Sandwich Bread', '100000000062', 'Classic sandwich loaf', 4)
(63, 'Sourdough Bread', '100000000063', 'Artisan sourdough loaf', 4)
(64, 'Multigrain Bread', '100000000064', 'Fresh multigrain loaf', 4)
(65, 'Plain Bagels 6 ct', '100000000065', 'Soft plain bagels', 4)
(66, 'Sesame Bagels 6 ct', '100000000066', 'Sesame bagels', 4)
(67, 'Butter Croissants 4 ct', '100000000067', 'Bakery croissants', 4)
(68, 'Blueberry Muffins 4 ct', '100000000068', 'Blueberry muffins', 4)
(69, 'Chocolate Muffins 4 ct', '100000000069', 'Chocolate chip muffins', 4)
(70, 'Cinnamon Rolls 4 ct', '100000000070', 'Fresh cinnamon rolls', 4)
(71, 'Chocolate Cake Slice', '100000000071', 'Chocolate cake slice', 4)
(72, 'Vanilla Cupcakes 6 ct', '100000000072', 'Vanilla cupcakes', 4)
(73, 'Dinner Rolls 12 ct', '100000000073', 'Soft dinner rolls', 4)
(74, 'Hamburger Buns 8 ct', '100000000074', 'Burger buns', 4)
(75, 'Hot Dog Buns 8 ct', '100000000075', 'Hot dog buns', 4)
(76, 'Pita Bread 6 ct', '100000000076', 'Soft pita bread', 4)
(77, 'Flour Tortillas 10 ct', '100000000077', 'Soft flour tortillas', 4)
(78, 'Corn Tortillas 20 ct', '100000000078', 'Corn tortillas', 4)
(79, 'Assorted Donuts 6 ct', '100000000079', 'Assorted donuts', 4)
(80, 'Brownie Tray 4 ct', '100000000080', 'Chocolate brownies', 4)
(81, 'Boneless Chicken Breast 1 lb', '100000000081', 'Fresh boneless chicken breast', 5)
(82, 'Boneless Chicken Thighs 1 lb', '100000000082', 'Fresh boneless chicken thighs', 5)
(83, 'Chicken Wings Family Pack', '100000000083', 'Fresh chicken wings', 5)
(84, 'Whole Chicken', '100000000084', 'Whole roasting chicken', 5)
(85, 'Ground Turkey 93% Lean 1 lb', '100000000085', 'Lean ground turkey', 5)
(86, 'Turkey Breast Cutlets 1 lb', '100000000086', 'Fresh turkey breast cutlets', 5)
(87, 'Turkey Breast Deli 8 oz', '100000000087', 'Sliced turkey breast', 5)
(88, 'Chicken Sausage Mild 12 oz', '100000000088', 'Mild chicken sausage', 5)
(89, 'Turkey Sausage Links 12 oz', '100000000089', 'Turkey sausage links', 5)
(90, 'Atlantic Salmon Fillet 1 lb', '100000000090', 'Fresh atlantic salmon fillet', 5)
(91, 'Tilapia Fillets 1 lb', '100000000091', 'Fresh tilapia fillets', 5)
(92, 'Cod Fillets 1 lb', '100000000092', 'Fresh cod fillets', 5)
(93, 'Raw Shrimp 1 lb', '100000000093', 'Peeled raw shrimp', 5)
(94, 'Cooked Shrimp 1 lb', '100000000094', 'Cooked shrimp', 5)
(95, 'Sea Scallops 12 oz', '100000000095', 'Fresh sea scallops', 5)
(96, 'Mussels 1 lb', '100000000096', 'Fresh mussels', 5)
(97, 'Crab Cakes 2 ct', '100000000097', 'Prepared crab cakes', 5)
(98, 'Smoked Salmon 4 oz', '100000000098', 'Smoked salmon pack', 5)
(99, 'Lobster Tails 2 ct', '100000000099', 'Cold water lobster tails', 5)
(100, 'Breaded Fish Fillets 16 oz', '100000000100', 'Breaded white fish fillets', 5)
(101, 'Orange Juice 52 oz', '100000000101', 'No pulp orange juice', 6)
(102, 'Apple Juice 64 oz', '100000000102', '100 percent apple juice', 6)
(103, 'Lime Sparkling Water 8 pk', '100000000103', 'Lime sparkling water', 6)
(104, 'Berry Sparkling Water 8 pk', '100000000104', 'Berry sparkling water', 6)
(105, 'Cola 12 pk', '100000000105', 'Classic cola cans', 6)
(106, 'Diet Cola 12 pk', '100000000106', 'Diet cola cans', 6)
(107, 'Lemonade 59 oz', '100000000107', 'Classic lemonade bottle', 6)
(108, 'Lemon Iced Tea 64 oz', '100000000108', 'Lemon iced tea', 6)
(109, 'Cold Brew Coffee 48 oz', '100000000109', 'Ready to drink cold brew', 6)
(110, 'Medium Roast Ground Coffee 12 oz', '100000000110', 'Medium roast ground coffee', 6)
(111, 'Breakfast Blend Coffee Pods 12 ct', '100000000111', 'Single serve coffee pods', 6)
(112, 'Black Tea Bags 40 ct', '100000000112', 'Black tea bags', 6)
(113, 'Green Tea Bags 40 ct', '100000000113', 'Green tea bags', 6)
(114, 'Blue Sports Drink 8 pk', '100000000114', 'Blue raspberry sports drink', 6)
(115, 'Citrus Energy Drink 4 pk', '100000000115', 'Citrus energy drink', 6)
(116, 'Coconut Water 1 L', '100000000116', 'Pure coconut water', 6)
(117, 'Purified Water 24 pk', '100000000117', 'Bottled water case', 6)
(118, 'Unsweetened Almond Milk 64 oz', '100000000118', 'Unsweetened almond milk', 6)
(119, 'Original Oat Milk 64 oz', '100000000119', 'Original oat milk', 6)
(120, 'Hot Chocolate Mix 10 ct', '100000000120', 'Hot chocolate mix packets', 6)
(121, 'Classic Potato Chips 8 oz', '100000000121', 'Salted potato chips', 7)
(122, 'Barbecue Potato Chips 8 oz', '100000000122', 'Barbecue potato chips', 7)
(123, 'Restaurant Style Tortilla Chips 13 oz', '100000000123', 'Tortilla chips', 7)
(124, 'Pretzel Twists 16 oz', '100000000124', 'Crunchy pretzel twists', 7)
(125, 'Chocolate Chip Cookies 13 oz', '100000000125', 'Chocolate chip cookies', 7)
(126, 'Oatmeal Raisin Cookies 13 oz', '100000000126', 'Oatmeal raisin cookies', 7)
(127, 'Milk Chocolate Bar 1.55 oz', '100000000127', 'Milk chocolate candy bar', 7)
(128, 'Dark Chocolate Bar 3.5 oz', '100000000128', 'Dark chocolate bar', 7)
(129, 'Deluxe Trail Mix 14 oz', '100000000129', 'Nut and fruit trail mix', 7)
(130, 'Roasted Mixed Nuts 10 oz', '100000000130', 'Roasted mixed nuts', 7)
(131, 'Butter Popcorn 6 ct', '100000000131', 'Microwave butter popcorn', 7)
(132, 'Peanut Protein Bars 5 ct', '100000000132', 'Peanut protein bars', 7)
(133, 'Variety Granola Bars 6 ct', '100000000133', 'Variety granola bars', 7)
(134, 'Original Crackers 13.7 oz', '100000000134', 'Original snack crackers', 7)
(135, 'Baked Cheese Crackers 12.4 oz', '100000000135', 'Cheddar baked crackers', 7)
(136, 'Fruit Snacks 10 ct', '100000000136', 'Assorted fruit snacks', 7)
(137, 'Sea Salt Rice Cakes 4.47 oz', '100000000137', 'Sea salt rice cakes', 7)
(138, 'Plant Based Jerky 2.5 oz', '100000000138', 'Plant based jerky', 7)
(139, 'Gummy Bears 8 oz', '100000000139', 'Gummy bears candy', 7)
(140, 'Peanut Butter Sandwich Crackers 8 ct', '100000000140', 'Peanut butter cracker packs', 7)
(141, 'Margherita Frozen Pizza 14 oz', '100000000141', 'Frozen margherita pizza', 8)
(142, 'Pepperoni Frozen Pizza 15 oz', '100000000142', 'Frozen pepperoni pizza', 8)
(143, 'Frozen Mixed Vegetables 12 oz', '100000000143', 'Frozen mixed vegetables', 8)
(144, 'Frozen Broccoli Florets 12 oz', '100000000144', 'Frozen broccoli florets', 8)
(145, 'Frozen French Fries 28 oz', '100000000145', 'Crispy frozen fries', 8)
(146, 'Frozen Chicken Nuggets 32 oz', '100000000146', 'Breaded chicken nuggets', 8)
(147, 'Frozen Waffles 10 ct', '100000000147', 'Frozen waffles', 8)
(148, 'Frozen Pancakes 12 ct', '100000000148', 'Frozen pancakes', 8)
(149, 'Vanilla Ice Cream 48 oz', '100000000149', 'Vanilla ice cream', 8)
(150, 'Chocolate Ice Cream 48 oz', '100000000150', 'Chocolate ice cream', 8)
(151, 'Frozen Berry Blend 16 oz', '100000000151', 'Mixed berries', 8)
(152, 'Frozen Mango Chunks 16 oz', '100000000152', 'Mango chunks', 8)
(153, 'Family Size Frozen Lasagna 38 oz', '100000000153', 'Frozen lasagna', 8)
(154, 'Frozen Mac & Cheese 12 oz', '100000000154', 'Frozen macaroni and cheese', 8)
(155, 'Frozen Fish Sticks 24 oz', '100000000155', 'Breaded frozen fish sticks', 8)
(156, 'Frozen Shrimp Tempura 9.2 oz', '100000000156', 'Shrimp tempura', 8)
(157, 'Frozen Pie Crusts 2 ct', '100000000157', 'Ready to bake pie crusts', 8)
(158, 'Frozen Garlic Bread 16 oz', '100000000158', 'Frozen garlic bread', 8)
(159, 'Frozen Turkey Meatballs 20 oz', '100000000159', 'Turkey meatballs', 8)
(160, 'Frozen Cheesecake Slices 16 oz', '100000000160', 'Frozen cheesecake slices', 8)
(161, 'Lemon Dish Soap 19.4 oz', '100000000161', 'Lemon dishwashing liquid', 9)
(162, 'Free & Clear Dish Soap 19.4 oz', '100000000162', 'Fragrance free dish soap', 9)
(163, 'Laundry Detergent 64 oz', '100000000163', 'Concentrated laundry detergent', 9)
(164, 'Fabric Softener 50 oz', '100000000164', 'Liquid fabric softener', 9)
(165, 'Paper Towels 6 ct', '100000000165', 'Absorbent paper towels', 9)
(166, 'Toilet Paper 12 ct', '100000000166', 'Soft bath tissue', 9)
(167, 'Kitchen Trash Bags 30 ct', '100000000167', 'Tall kitchen trash bags', 9)
(168, 'Heavy Duty Aluminum Foil 75 ft', '100000000168', 'Aluminum foil roll', 9)
(169, 'Plastic Wrap 200 ft', '100000000169', 'Cling wrap roll', 9)
(170, 'Cleaning Sponges 6 ct', '100000000170', 'Multi-use sponges', 9)
(171, 'Glass Cleaner 32 oz', '100000000171', 'Streak free glass cleaner', 9)
(172, 'Disinfecting Wipes 75 ct', '100000000172', 'Disinfecting wipes', 9)
(173, 'All Purpose Cleaner 32 oz', '100000000173', 'Multi-surface cleaner', 9)
(174, 'Household Bleach 81 oz', '100000000174', 'Household bleach', 9)
(175, 'Indoor Broom', '100000000175', 'Indoor broom', 9)
(176, 'Mop Refill Head', '100000000176', 'Replacement mop head', 9)
(177, 'Sandwich Zipper Bags 100 ct', '100000000177', 'Sandwich storage bags', 9)
(178, 'Freezer Zipper Bags 40 ct', '100000000178', 'Freezer storage bags', 9)
(179, 'Linen Air Freshener 8 oz', '100000000179', 'Air freshener spray', 9)
(180, 'AA Batteries 8 ct', '100000000180', 'Alkaline AA batteries', 9)
(181, 'Herbal Shampoo 12 oz', '100000000181', 'Herbal daily shampoo', 10)
(182, 'Herbal Conditioner 12 oz', '100000000182', 'Herbal daily conditioner', 10)
(183, 'Mint Toothpaste 5.8 oz', '100000000183', 'Fluoride toothpaste', 10)
(184, 'Soft Toothbrushes 2 ct', '100000000184', 'Soft bristle toothbrush pack', 10)
(185, 'Fresh Body Wash 18 oz', '100000000185', 'Fresh scent body wash', 10)
(186, 'Moisturizing Bar Soap 6 ct', '100000000186', 'Bar soap pack', 10)
(187, 'Aloe Hand Soap 12.5 oz', '100000000187', 'Aloe hand soap', 10)
(188, 'Gentle Face Wash 8 oz', '100000000188', 'Daily gentle face wash', 10)
(189, 'Fresh Deodorant 2.6 oz', '100000000189', 'Fresh scent deodorant', 10)
(190, 'Unscented Body Lotion 16 oz', '100000000190', 'Unscented body lotion', 10)
(191, 'Sensitive Shaving Cream 11 oz', '100000000191', 'Sensitive shaving cream', 10)
(192, 'Disposable Razors 4 ct', '100000000192', 'Disposable razors', 10)
(193, 'Cotton Swabs 300 ct', '100000000193', 'Cotton swabs', 10)
(194, 'Cotton Balls 200 ct', '100000000194', 'Cotton balls', 10)
(195, 'Facial Tissues 4 ct', '100000000195', 'Facial tissue box pack', 10)
(196, 'Cool Mint Mouthwash 1 L', '100000000196', 'Cool mint mouthwash', 10)
(197, 'Waxed Dental Floss 2 pk', '100000000197', 'Waxed dental floss', 10)
(198, 'Hand Sanitizer 8 oz', '100000000198', 'Alcohol hand sanitizer', 10)
(199, 'Original Lip Balm 0.15 oz', '100000000199', 'Lip balm', 10)
(200, 'Sunscreen SPF 50 6 oz', '100000000200', 'Broad spectrum sunscreen', 10)
(201, 'Basmati Rice 5 lb', '100000000201', 'Long grain basmati rice', 11)
(202, 'Jasmine Rice 5 lb', '100000000202', 'Fragrant jasmine rice', 11)
(203, 'Penne Pasta 16 oz', '100000000203', 'Durum wheat penne pasta', 11)
(204, 'Spaghetti Pasta 16 oz', '100000000204', 'Classic spaghetti pasta', 11)
(205, 'Extra Virgin Olive Oil 1 L', '100000000205', 'Olive oil', 11)
(206, 'Canola Oil 48 oz', '100000000206', 'Pure canola oil', 11)
(207, 'All Purpose Flour 5 lb', '100000000207', 'All purpose flour', 11)
(208, 'Granulated Sugar 4 lb', '100000000208', 'White granulated sugar', 11)
(209, 'Light Brown Sugar 2 lb', '100000000209', 'Light brown sugar', 11)
(210, 'Iodized Salt 26 oz', '100000000210', 'Table salt', 11)
(211, 'Ground Black Pepper 4 oz', '100000000211', 'Ground black pepper', 11)
(212, 'Canned Black Beans 15 oz', '100000000212', 'Black beans', 11)
(213, 'Canned Chickpeas 15 oz', '100000000213', 'Chickpeas', 11)
(214, 'Canned Corn 15.25 oz', '100000000214', 'Sweet corn', 11)
(215, 'Tomato Sauce 24 oz', '100000000215', 'Classic tomato sauce', 11)
(216, 'Creamy Peanut Butter 16 oz', '100000000216', 'Creamy peanut butter', 11)
(217, 'Strawberry Jam 18 oz', '100000000217', 'Fruit jam', 11)
(218, 'Chicken Broth 32 oz', '100000000218', 'Cooking broth', 11)
(219, 'Chunk Light Tuna 5 oz', '100000000219', 'Tuna in water', 11)
(220, 'Pure Maple Syrup 12 oz', '100000000220', 'Maple syrup', 11)
(221, 'Corn Flakes 18 oz', '100000000221', 'Classic corn flakes cereal', 12)
(222, 'Rolled Oats 42 oz', '100000000222', 'Old fashioned rolled oats', 12)
(223, 'Honey Oat Cereal 18 oz', '100000000223', 'Honey oat cereal', 12)
(224, 'Granola Crunch 16 oz', '100000000224', 'Crunchy granola', 12)
(225, 'Apple Cinnamon Oatmeal 8 ct', '100000000225', 'Instant oatmeal', 12)
(226, 'Maple Brown Sugar Oatmeal 8 ct', '100000000226', 'Instant oatmeal', 12)
(227, 'Pancake Mix 32 oz', '100000000227', 'Classic pancake mix', 12)
(228, 'Waffle Mix 32 oz', '100000000228', 'Homestyle waffle mix', 12)
(229, 'Breakfast Syrup 24 oz', '100000000229', 'Maple flavored syrup', 12)
(230, 'Creamy Peanut Butter 16 oz Breakfast', '100000000230', 'Peanut butter for toast', 12)
(231, 'Chocolate Hazelnut Spread 13 oz', '100000000231', 'Hazelnut spread', 12)
(232, 'Oat Breakfast Bars 6 ct', '100000000232', 'Oat breakfast bars', 12)
(233, 'Strawberry Toaster Pastries 8 ct', '100000000233', 'Toaster pastries', 12)
(234, 'Brown Sugar Toaster Pastries 8 ct', '100000000234', 'Toaster pastries', 12)
(235, 'Fruit & Nut Muesli 14 oz', '100000000235', 'Muesli cereal', 12)
(236, 'Bran Crunch Cereal 16 oz', '100000000236', 'Bran cereal', 12)
(237, 'Cinnamon Bagel Chips 7 oz', '100000000237', 'Crunchy bagel chips', 12)
(238, 'Honey Breakfast Biscuits 5 ct', '100000000238', 'Breakfast biscuits', 12)
(239, 'Chia Oat Cups 4 ct', '100000000239', 'Ready breakfast cups', 12)
(240, 'Protein Pancake Mix 20 oz', '100000000240', 'Protein pancake mix', 12)

# stores

In [37]:
store_mapping

      store_id  inventory_id  product_id
0            1             1           1
1            1             2           2
2            1             3           3
3            1             4           4
4            1             5           5
...        ...           ...         ...
2395        10          2396         236
2396        10          2397         237
2397        10          2398         238
2398        10          2399         239
2399        10          2400         240

[2400 rows x 3 columns]

In [38]:
query = "INSERT INTO stores(store_id,inventory_id, product_id) VALUES (%s,%s,%s)"
data = list(store_mapping.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM stores")
for i in cursor:
    print(i)

(1, 1, 1)
(1, 2, 2)
(1, 3, 3)
(1, 4, 4)
(1, 5, 5)
(1, 6, 6)
(1, 7, 7)
(1, 8, 8)
(1, 9, 9)
(1, 10, 10)
(1, 11, 11)
(1, 12, 12)
(1, 13, 13)
(1, 14, 14)
(1, 15, 15)
(1, 16, 16)
(1, 17, 17)
(1, 18, 18)
(1, 19, 19)
(1, 20, 20)
(1, 21, 21)
(1, 22, 22)
(1, 23, 23)
(1, 24, 24)
(1, 25, 25)
(1, 26, 26)
(1, 27, 27)
(1, 28, 28)
(1, 29, 29)
(1, 30, 30)
(1, 31, 31)
(1, 32, 32)
(1, 33, 33)
(1, 34, 34)
(1, 35, 35)
(1, 36, 36)
(1, 37, 37)
(1, 38, 38)
(1, 39, 39)
(1, 40, 40)
(1, 41, 41)
(1, 42, 42)
(1, 43, 43)
(1, 44, 44)
(1, 45, 45)
(1, 46, 46)
(1, 47, 47)
(1, 48, 48)
(1, 49, 49)
(1, 50, 50)
(1, 51, 51)
(1, 52, 52)
(1, 53, 53)
(1, 54, 54)
(1, 55, 55)
(1, 56, 56)
(1, 57, 57)
(1, 58, 58)
(1, 59, 59)
(1, 60, 60)
(1, 61, 61)
(1, 62, 62)
(1, 63, 63)
(1, 64, 64)
(1, 65, 65)
(1, 66, 66)
(1, 67, 67)
(1, 68, 68)
(1, 69, 69)
(1, 70, 70)
(1, 71, 71)
(1, 72, 72)
(1, 73, 73)
(1, 74, 74)
(1, 75, 75)
(1, 76, 76)
(1, 77, 77)
(1, 78, 78)
(1, 79, 79)
(1, 80, 80)
(1, 81, 81)
(1, 82, 82)
(1, 83, 83)
(1, 84, 84)
(1, 85, 85)
(1, 86, 86)
(1, 87, 87)
(1, 88, 88)
(1, 89, 89)
(1, 90, 90)
(1, 91, 91)
(1, 92, 92)
(1, 93, 93)
(1, 94, 94)
(1, 95, 95)
(1, 96, 96)
(1, 97, 97)
(1, 98, 98)
(1, 99, 99)
(1, 100, 100)
(1, 101, 101)
(1, 102, 102)
(1, 103, 103)
(1, 104, 104)
(1, 105, 105)
(1, 106, 106)
(1, 107, 107)
(1, 108, 108)
(1, 109, 109)
(1, 110, 110)
(1, 111, 111)
(1, 112, 112)
(1, 113, 113)
(1, 114, 114)
(1, 115, 115)
(1, 116, 116)
(1, 117, 117)
(1, 118, 118)
(1, 119, 119)
(1, 120, 120)
(1, 121, 121)
(1, 122, 122)
(1, 123, 123)
(1, 124, 124)
(1, 125, 125)
(1, 126, 126)
(1, 127, 127)
(1, 128, 128)
(1, 129, 129)
(1, 130, 130)
(1, 131, 131)
(1, 132, 132)
(1, 133, 133)
(1, 134, 134)
(1, 135, 135)
(1, 136, 136)
(1, 137, 137)
(1, 138, 138)
(1, 139, 139)
(1, 140, 140)
(1, 141, 141)
(1, 142, 142)
(1, 143, 143)
(1, 144, 144)
(1, 145, 145)
(1, 146, 146)
(1, 147, 147)
(1, 148, 148)
(1, 149, 149)
(1, 150, 150)
(1, 151, 151)
(1, 152, 152)
(1, 153, 153)
(1, 154, 154)
(1, 155, 155)
(1, 156, 156)
(1, 157, 157)
(1, 158, 158)
(1, 159, 159)
(1, 160, 160)
(1, 161, 161)
(1, 162, 162)
(1, 163, 163)
(1, 164, 164)
(1, 165, 165)
(1, 166, 166)
(1, 167, 167)
(1, 168, 168)
(1, 169, 169)
(1, 170, 170)
(1, 171, 171)
(1, 172, 172)
(1, 173, 173)
(1, 174, 174)
(1, 175, 175)
(1, 176, 176)
(1, 177, 177)
(1, 178, 178)
(1, 179, 179)
(1, 180, 180)
(1, 181, 181)
(1, 182, 182)
(1, 183, 183)
(1, 184, 184)
(1, 185, 185)
(1, 186, 186)
(1, 187, 187)
(1, 188, 188)
(1, 189, 189)
(1, 190, 190)
(1, 191, 191)
(1, 192, 192)
(1, 193, 193)
(1, 194, 194)
(1, 195, 195)
(1, 196, 196)
(1, 197, 197)
(1, 198, 198)
(1, 199, 199)
(1, 200, 200)
(1, 201, 201)
(1, 202, 202)
(1, 203, 203)
(1, 204, 204)
(1, 205, 205)
(1, 206, 206)
(1, 207, 207)
(1, 208, 208)
(1, 209, 209)
(1, 210, 210)
(1, 211, 211)
(1, 212, 212)
(1, 213, 213)
(1, 214, 214)
(1, 215, 215)
(1, 216, 216)
(1, 217, 217)
(1, 218, 218)
(1, 219, 219)
(1, 220, 220)
(1, 221, 221)
(1, 222, 222)
(1, 223, 223)
(1, 224, 224)
(1, 225, 225)
(1, 226, 226)
(1, 227, 227)
(1, 228, 228)
(1, 229, 229)
(1, 230, 230)
(1, 231, 231)
(1, 232, 232)
(1, 233, 233)
(1, 234, 234)
(1, 235, 235)
(1, 236, 236)
(1, 237, 237)
(1, 238, 238)
(1, 239, 239)
(1, 240, 240)
(2, 241, 1)
(2, 242, 2)
(2, 243, 3)
(2, 244, 4)
(2, 245, 5)
(2, 246, 6)
(2, 247, 7)
(2, 248, 8)
(2, 249, 9)
(2, 250, 10)
(2, 251, 11)
(2, 252, 12)
(2, 253, 13)
(2, 254, 14)
(2, 255, 15)
(2, 256, 16)
(2, 257, 17)
(2, 258, 18)
(2, 259, 19)
(2, 260, 20)
(2, 261, 21)
(2, 262, 22)
(2, 263, 23)
(2, 264, 24)
(2, 265, 25)
(2, 266, 26)
(2, 267, 27)
(2, 268, 28)
(2, 269, 29)
(2, 270, 30)
(2, 271, 31)
(2, 272, 32)
(2, 273, 33)
(2, 274, 34)
(2, 275, 35)
(2, 276, 36)
(2, 277, 37)
(2, 278, 38)
(2, 279, 39)
(2, 280, 40)
(2, 281, 41)
(2, 282, 42)
(2, 283, 43)
(2, 284, 44)
(2, 285, 45)
(2, 286, 46)
(2, 287, 47)
(2, 288, 48)
(2, 289, 49)
(2, 290, 50)
(2, 291, 51)
(2, 292, 52)
(2, 293, 53)
(2, 294, 54)
(2, 295, 55)
(2, 296, 56)
(2, 297, 57)
(2, 298, 58)
(2, 299, 59)
(2, 300, 60)
(2, 301, 61)
(2, 302, 62)
(2, 303, 63)
(2, 304, 64)
(2, 305, 65)
(2, 306, 66)
(2, 307, 67)
(2, 308, 68)
(2, 309, 69)
(2, 310, 70)
(2, 311, 71)
(2, 312, 72)
(2, 313, 73)
(2, 314, 74)
(2, 315, 75)
(2, 316, 76)
(2, 317, 77)
(2, 318, 78)
(2, 319, 79)
(2, 320, 80)
(2, 321, 81)
(2, 322, 82)
(2, 323, 83)
(2, 324, 84)
(2, 325, 85)
(2, 326, 86)
(2, 327, 87)
(2, 328, 88)
(2, 329, 89)
(2, 330, 90)
(2, 331, 91)
(2, 332, 92)
(2, 333, 93)
(2, 334, 94)
(2, 335, 95)
(2, 336, 96)
(2, 337, 97)
(2, 338, 98)
(2, 339, 99)
(2, 340, 100)
(2, 341, 101)
(2, 342, 102)
(2, 343, 103)
(2, 344, 104)
(2, 345, 105)
(2, 346, 106)
(2, 347, 107)
(2, 348, 108)
(2, 349, 109)
(2, 350, 110)
(2, 351, 111)
(2, 352, 112)
(2, 353, 113)
(2, 354, 114)
(2, 355, 115)
(2, 356, 116)
(2, 357, 117)
(2, 358, 118)
(2, 359, 119)
(2, 360, 120)
(2, 361, 121)
(2, 362, 122)
(2, 363, 123)
(2, 364, 124)
(2, 365, 125)
(2, 366, 126)
(2, 367, 127)
(2, 368, 128)
(2, 369, 129)
(2, 370, 130)
(2, 371, 131)
(2, 372, 132)
(2, 373, 133)
(2, 374, 134)
(2, 375, 135)
(2, 376, 136)
(2, 377, 137)
(2, 378, 138)
(2, 379, 139)
(2, 380, 140)
(2, 381, 141)
(2, 382, 142)
(2, 383, 143)
(2, 384, 144)
(2, 385, 145)
(2, 386, 146)
(2, 387, 147)
(2, 388, 148)
(2, 389, 149)
(2, 390, 150)
(2, 391, 151)
(2, 392, 152)
(2, 393, 153)
(2, 394, 154)
(2, 395, 155)
(2, 396, 156)
(2, 397, 157)
(2, 398, 158)
(2, 399, 159)
(2, 400, 160)
(2, 401, 161)
(2, 402, 162)
(2, 403, 163)
(2, 404, 164)
(2, 405, 165)
(2, 406, 166)
(2, 407, 167)
(2, 408, 168)
(2, 409, 169)
(2, 410, 170)
(2, 411, 171)
(2, 412, 172)
(2, 413, 173)
(2, 414, 174)
(2, 415, 175)
(2, 416, 176)
(2, 417, 177)
(2, 418, 178)
(2, 419, 179)
(2, 420, 180)
(2, 421, 181)
(2, 422, 182)
(2, 423, 183)
(2, 424, 184)
(2, 425, 185)
(2, 426, 186)
(2, 427, 187)
(2, 428, 188)
(2, 429, 189)
(2, 430, 190)
(2, 431, 191)
(2, 432, 192)
(2, 433, 193)
(2, 434, 194)
(2, 435, 195)
(2, 436, 196)
(2, 437, 197)
(2, 438, 198)
(2, 439, 199)
(2, 440, 200)
(2, 441, 201)
(2, 442, 202)
(2, 443, 203)
(2, 444, 204)
(2, 445, 205)
(2, 446, 206)
(2, 447, 207)
(2, 448, 208)
(2, 449, 209)
(2, 450, 210)
(2, 451, 211)
(2, 452, 212)
(2, 453, 213)
(2, 454, 214)
(2, 455, 215)
(2, 456, 216)
(2, 457, 217)
(2, 458, 218)
(2, 459, 219)
(2, 460, 220)
(2, 461, 221)
(2, 462, 222)
(2, 463, 223)
(2, 464, 224)
(2, 465, 225)
(2, 466, 226)
(2, 467, 227)
(2, 468, 228)
(2, 469, 229)
(2, 470, 230)
(2, 471, 231)
(2, 472, 232)
(2, 473, 233)
(2, 474, 234)
(2, 475, 235)
(2, 476, 236)
(2, 477, 237)
(2, 478, 238)
(2, 479, 239)
(2, 480, 240)
(3, 481, 1)
(3, 482, 2)
(3, 483, 3)
(3, 484, 4)
(3, 485, 5)
(3, 486, 6)
(3, 487, 7)
(3, 488, 8)
(3, 489, 9)
(3, 490, 10)
(3, 491, 11)
(3, 492, 12)
(3, 493, 13)
(3, 494, 14)
(3, 495, 15)
(3, 496, 16)
(3, 497, 17)
(3, 498, 18)
(3, 499, 19)
(3, 500, 20)
(3, 501, 21)
(3, 502, 22)
(3, 503, 23)
(3, 504, 24)
(3, 505, 25)
(3, 506, 26)
(3, 507, 27)
(3, 508, 28)
(3, 509, 29)
(3, 510, 30)
(3, 511, 31)
(3, 512, 32)
(3, 513, 33)
(3, 514, 34)
(3, 515, 35)
(3, 516, 36)
(3, 517, 37)
(3, 518, 38)
(3, 519, 39)
(3, 520, 40)
(3, 521, 41)
(3, 522, 42)
(3, 523, 43)
(3, 524, 44)
(3, 525, 45)
(3, 526, 46)
(3, 527, 47)
(3, 528, 48)
(3, 529, 49)
(3, 530, 50)
(3, 531, 51)
(3, 532, 52)
(3, 533, 53)
(3, 534, 54)
(3, 535, 55)
(3, 536, 56)
(3, 537, 57)
(3, 538, 58)
(3, 539, 59)
(3, 540, 60)
(3, 541, 61)
(3, 542, 62)
(3, 543, 63)
(3, 544, 64)
(3, 545, 65)
(3, 546, 66)
(3, 547, 67)
(3, 548, 68)
(3, 549, 69)
(3, 550, 70)
(3, 551, 71)
(3, 552, 72)
(3, 553, 73)
(3, 554, 74)
(3, 555, 75)
(3, 556, 76)
(3, 557, 77)
(3, 558, 78)
(3, 559, 79)
(3, 560, 80)
(3, 561, 81)
(3, 562, 82)
(3, 563, 83)
(3, 564, 84)
(3, 565, 85)
(3, 566, 86)
(3, 567, 87)
(3, 568, 88)
(3, 569, 89)
(3, 570, 90)
(3, 571, 91)
(3, 572, 92)
(3, 573, 93)
(3, 574, 94)
(3, 575, 95)
(3, 576, 96)
(3, 577, 97)
(3, 578, 98)
(3, 579, 99)
(3, 580, 100)
(3, 581, 101)
(3, 582, 102)
(3, 583, 103)
(3, 584, 104)
(3, 585, 105)
(3, 586, 106)
(3, 587, 107)
(3, 588, 108)
(3, 589, 109)
(3, 590, 110)
(3, 591, 111)
(3, 592, 112)
(3, 593, 113)
(3, 594, 114)
(3, 595, 115)
(3, 596, 116)
(3, 597, 117)
(3, 598, 118)
(3, 599, 119)
(3, 600, 120)
(3, 601, 121)
(3, 602, 122)
(3, 603, 123)
(3, 604, 124)
(3, 605, 125)
(3, 606, 126)
(3, 607, 127)
(3, 608, 128)
(3, 609, 129)
(3, 610, 130)
(3, 611, 131)
(3, 612, 132)
(3, 613, 133)
(3, 614, 134)
(3, 615, 135)
(3, 616, 136)
(3, 617, 137)
(3, 618, 138)
(3, 619, 139)
(3, 620, 140)
(3, 621, 141)
(3, 622, 142)
(3, 623, 143)
(3, 624, 144)
(3, 625, 145)
(3, 626, 146)
(3, 627, 147)
(3, 628, 148)
(3, 629, 149)
(3, 630, 150)
(3, 631, 151)
(3, 632, 152)
(3, 633, 153)
(3, 634, 154)
(3, 635, 155)
(3, 636, 156)
(3, 637, 157)
(3, 638, 158)
(3, 639, 159)
(3, 640, 160)
(3, 641, 161)
(3, 642, 162)
(3, 643, 163)
(3, 644, 164)
(3, 645, 165)
(3, 646, 166)
(3, 647, 167)
(3, 648, 168)
(3, 649, 169)
(3, 650, 170)
(3, 651, 171)
(3, 652, 172)
(3, 653, 173)
(3, 654, 174)
(3, 655, 175)
(3, 656, 176)
(3, 657, 177)
(3, 658, 178)
(3, 659, 179)
(3, 660, 180)
(3, 661, 181)
(3, 662, 182)
(3, 663, 183)
(3, 664, 184)
(3, 665, 185)
(3, 666, 186)
(3, 667, 187)
(3, 668, 188)
(3, 669, 189)
(3, 670, 190)
(3, 671, 191)
(3, 672, 192)
(3, 673, 193)
(3, 674, 194)
(3, 675, 195)
(3, 676, 196)
(3, 677, 197)
(3, 678, 198)
(3, 679, 199)
(3, 680, 200)
(3, 681, 201)
(3, 682, 202)
(3, 683, 203)
(3, 684, 204)
(3, 685, 205)
(3, 686, 206)
(3, 687, 207)
(3, 688, 208)
(3, 689, 209)
(3, 690, 210)
(3, 691, 211)
(3, 692, 212)
(3, 693, 213)
(3, 694, 214)
(3, 695, 215)
(3, 696, 216)
(3, 697, 217)
(3, 698, 218)
(3, 699, 219)
(3, 700, 220)
(3, 701, 221)
(3, 702, 222)
(3, 703, 223)
(3, 704, 224)
(3, 705, 225)
(3, 706, 226)
(3, 707, 227)
(3, 708, 228)
(3, 709, 229)
(3, 710, 230)
(3, 711, 231)
(3, 712, 232)
(3, 713, 233)
(3, 714, 234)
(3, 715, 235)
(3, 716, 236)
(3, 717, 237)
(3, 718, 238)
(3, 719, 239)
(3, 720, 240)
(4, 721, 1)
(4, 722, 2)
(4, 723, 3)
(4, 724, 4)
(4, 725, 5)
(4, 726, 6)
(4, 727, 7)
(4, 728, 8)
(4, 729, 9)
(4, 730, 10)
(4, 731, 11)
(4, 732, 12)
(4, 733, 13)
(4, 734, 14)
(4, 735, 15)
(4, 736, 16)
(4, 737, 17)
(4, 738, 18)
(4, 739, 19)
(4, 740, 20)
(4, 741, 21)
(4, 742, 22)
(4, 743, 23)
(4, 744, 24)
(4, 745, 25)
(4, 746, 26)
(4, 747, 27)
(4, 748, 28)
(4, 749, 29)
(4, 750, 30)
(4, 751, 31)
(4, 752, 32)
(4, 753, 33)
(4, 754, 34)
(4, 755, 35)
(4, 756, 36)
(4, 757, 37)
(4, 758, 38)
(4, 759, 39)
(4, 760, 40)
(4, 761, 41)
(4, 762, 42)
(4, 763, 43)
(4, 764, 44)
(4, 765, 45)
(4, 766, 46)
(4, 767, 47)
(4, 768, 48)
(4, 769, 49)
(4, 770, 50)
(4, 771, 51)
(4, 772, 52)
(4, 773, 53)
(4, 774, 54)
(4, 775, 55)
(4, 776, 56)
(4, 777, 57)
(4, 778, 58)
(4, 779, 59)
(4, 780, 60)
(4, 781, 61)
(4, 782, 62)
(4, 783, 63)
(4, 784, 64)
(4, 785, 65)
(4, 786, 66)
(4, 787, 67)
(4, 788, 68)
(4, 789, 69)
(4, 790, 70)
(4, 791, 71)
(4, 792, 72)
(4, 793, 73)
(4, 794, 74)
(4, 795, 75)
(4, 796, 76)
(4, 797, 77)
(4, 798, 78)
(4, 799, 79)
(4, 800, 80)
(4, 801, 81)
(4, 802, 82)
(4, 803, 83)
(4, 804, 84)
(4, 805, 85)
(4, 806, 86)
(4, 807, 87)
(4, 808, 88)
(4, 809, 89)
(4, 810, 90)
(4, 811, 91)
(4, 812, 92)
(4, 813, 93)
(4, 814, 94)
(4, 815, 95)
(4, 816, 96)
(4, 817, 97)
(4, 818, 98)
(4, 819, 99)
(4, 820, 100)
(4, 821, 101)
(4, 822, 102)
(4, 823, 103)
(4, 824, 104)
(4, 825, 105)
(4, 826, 106)
(4, 827, 107)
(4, 828, 108)
(4, 829, 109)
(4, 830, 110)
(4, 831, 111)
(4, 832, 112)
(4, 833, 113)
(4, 834, 114)
(4, 835, 115)
(4, 836, 116)
(4, 837, 117)
(4, 838, 118)
(4, 839, 119)
(4, 840, 120)
(4, 841, 121)
(4, 842, 122)
(4, 843, 123)
(4, 844, 124)
(4, 845, 125)
(4, 846, 126)
(4, 847, 127)
(4, 848, 128)
(4, 849, 129)
(4, 850, 130)
(4, 851, 131)
(4, 852, 132)
(4, 853, 133)
(4, 854, 134)
(4, 855, 135)
(4, 856, 136)
(4, 857, 137)
(4, 858, 138)
(4, 859, 139)
(4, 860, 140)
(4, 861, 141)
(4, 862, 142)
(4, 863, 143)
(4, 864, 144)
(4, 865, 145)
(4, 866, 146)
(4, 867, 147)
(4, 868, 148)
(4, 869, 149)
(4, 870, 150)
(4, 871, 151)
(4, 872, 152)
(4, 873, 153)
(4, 874, 154)
(4, 875, 155)
(4, 876, 156)
(4, 877, 157)
(4, 878, 158)
(4, 879, 159)
(4, 880, 160)
(4, 881, 161)
(4, 882, 162)
(4, 883, 163)
(4, 884, 164)
(4, 885, 165)
(4, 886, 166)
(4, 887, 167)
(4, 888, 168)
(4, 889, 169)
(4, 890, 170)
(4, 891, 171)
(4, 892, 172)
(4, 893, 173)
(4, 894, 174)
(4, 895, 175)
(4, 896, 176)
(4, 897, 177)
(4, 898, 178)
(4, 899, 179)
(4, 900, 180)
(4, 901, 181)
(4, 902, 182)
(4, 903, 183)
(4, 904, 184)
(4, 905, 185)
(4, 906, 186)
(4, 907, 187)
(4, 908, 188)
(4, 909, 189)
(4, 910, 190)
(4, 911, 191)
(4, 912, 192)
(4, 913, 193)
(4, 914, 194)
(4, 915, 195)
(4, 916, 196)
(4, 917, 197)
(4, 918, 198)
(4, 919, 199)
(4, 920, 200)
(4, 921, 201)
(4, 922, 202)
(4, 923, 203)
(4, 924, 204)
(4, 925, 205)
(4, 926, 206)
(4, 927, 207)
(4, 928, 208)
(4, 929, 209)
(4, 930, 210)
(4, 931, 211)
(4, 932, 212)
(4, 933, 213)
(4, 934, 214)
(4, 935, 215)
(4, 936, 216)
(4, 937, 217)
(4, 938, 218)
(4, 939, 219)
(4, 940, 220)
(4, 941, 221)
(4, 942, 222)
(4, 943, 223)
(4, 944, 224)
(4, 945, 225)
(4, 946, 226)
(4, 947, 227)
(4, 948, 228)
(4, 949, 229)
(4, 950, 230)
(4, 951, 231)
(4, 952, 232)
(4, 953, 233)
(4, 954, 234)
(4, 955, 235)
(4, 956, 236)
(4, 957, 237)
(4, 958, 238)
(4, 959, 239)
(4, 960, 240)
(5, 961, 1)
(5, 962, 2)
(5, 963, 3)
(5, 964, 4)
(5, 965, 5)
(5, 966, 6)
(5, 967, 7)
(5, 968, 8)
(5, 969, 9)
(5, 970, 10)
(5, 971, 11)
(5, 972, 12)
(5, 973, 13)
(5, 974, 14)
(5, 975, 15)
(5, 976, 16)
(5, 977, 17)
(5, 978, 18)
(5, 979, 19)
(5, 980, 20)
(5, 981, 21)
(5, 982, 22)
(5, 983, 23)
(5, 984, 24)
(5, 985, 25)
(5, 986, 26)
(5, 987, 27)
(5, 988, 28)
(5, 989, 29)
(5, 990, 30)
(5, 991, 31)
(5, 992, 32)
(5, 993, 33)
(5, 994, 34)
(5, 995, 35)
(5, 996, 36)
(5, 997, 37)
(5, 998, 38)
(5, 999, 39)
(5, 1000, 40)
(5, 1001, 41)
(5, 1002, 42)
(5, 1003, 43)
(5, 1004, 44)
(5, 1005, 45)
(5, 1006, 46)
(5, 1007, 47)
(5, 1008, 48)
(5, 1009, 49)
(5, 1010, 50)
(5, 1011, 51)
(5, 1012, 52)
(5, 1013, 53)
(5, 1014, 54)
(5, 1015, 55)
(5, 1016, 56)
(5, 1017, 57)
(5, 1018, 58)
(5, 1019, 59)
(5, 1020, 60)
(5, 1021, 61)
(5, 1022, 62)
(5, 1023, 63)
(5, 1024, 64)
(5, 1025, 65)
(5, 1026, 66)
(5, 1027, 67)
(5, 1028, 68)
(5, 1029, 69)
(5, 1030, 70)
(5, 1031, 71)
(5, 1032, 72)
(5, 1033, 73)
(5, 1034, 74)
(5, 1035, 75)
(5, 1036, 76)
(5, 1037, 77)
(5, 1038, 78)
(5, 1039, 79)
(5, 1040, 80)
(5, 1041, 81)
(5, 1042, 82)
(5, 1043, 83)
(5, 1044, 84)
(5, 1045, 85)
(5, 1046, 86)
(5, 1047, 87)
(5, 1048, 88)
(5, 1049, 89)
(5, 1050, 90)
(5, 1051, 91)
(5, 1052, 92)
(5, 1053, 93)
(5, 1054, 94)
(5, 1055, 95)
(5, 1056, 96)
(5, 1057, 97)
(5, 1058, 98)
(5, 1059, 99)
(5, 1060, 100)
(5, 1061, 101)
(5, 1062, 102)
(5, 1063, 103)
(5, 1064, 104)
(5, 1065, 105)
(5, 1066, 106)
(5, 1067, 107)
(5, 1068, 108)
(5, 1069, 109)
(5, 1070, 110)
(5, 1071, 111)
(5, 1072, 112)
(5, 1073, 113)
(5, 1074, 114)
(5, 1075, 115)
(5, 1076, 116)
(5, 1077, 117)
(5, 1078, 118)
(5, 1079, 119)
(5, 1080, 120)
(5, 1081, 121)
(5, 1082, 122)
(5, 1083, 123)
(5, 1084, 124)
(5, 1085, 125)
(5, 1086, 126)
(5, 1087, 127)
(5, 1088, 128)
(5, 1089, 129)
(5, 1090, 130)
(5, 1091, 131)
(5, 1092, 132)
(5, 1093, 133)
(5, 1094, 134)
(5, 1095, 135)
(5, 1096, 136)
(5, 1097, 137)
(5, 1098, 138)
(5, 1099, 139)
(5, 1100, 140)
(5, 1101, 141)
(5, 1102, 142)
(5, 1103, 143)
(5, 1104, 144)
(5, 1105, 145)
(5, 1106, 146)
(5, 1107, 147)
(5, 1108, 148)
(5, 1109, 149)
(5, 1110, 150)
(5, 1111, 151)
(5, 1112, 152)
(5, 1113, 153)
(5, 1114, 154)
(5, 1115, 155)
(5, 1116, 156)
(5, 1117, 157)
(5, 1118, 158)
(5, 1119, 159)
(5, 1120, 160)
(5, 1121, 161)
(5, 1122, 162)
(5, 1123, 163)
(5, 1124, 164)
(5, 1125, 165)
(5, 1126, 166)
(5, 1127, 167)
(5, 1128, 168)
(5, 1129, 169)
(5, 1130, 170)
(5, 1131, 171)
(5, 1132, 172)
(5, 1133, 173)
(5, 1134, 174)
(5, 1135, 175)
(5, 1136, 176)
(5, 1137, 177)
(5, 1138, 178)
(5, 1139, 179)
(5, 1140, 180)
(5, 1141, 181)
(5, 1142, 182)
(5, 1143, 183)
(5, 1144, 184)
(5, 1145, 185)
(5, 1146, 186)
(5, 1147, 187)
(5, 1148, 188)
(5, 1149, 189)
(5, 1150, 190)
(5, 1151, 191)
(5, 1152, 192)
(5, 1153, 193)
(5, 1154, 194)
(5, 1155, 195)
(5, 1156, 196)
(5, 1157, 197)
(5, 1158, 198)
(5, 1159, 199)
(5, 1160, 200)
(5, 1161, 201)
(5, 1162, 202)
(5, 1163, 203)
(5, 1164, 204)
(5, 1165, 205)
(5, 1166, 206)
(5, 1167, 207)
(5, 1168, 208)
(5, 1169, 209)
(5, 1170, 210)
(5, 1171, 211)
(5, 1172, 212)
(5, 1173, 213)
(5, 1174, 214)
(5, 1175, 215)
(5, 1176, 216)
(5, 1177, 217)
(5, 1178, 218)
(5, 1179, 219)
(5, 1180, 220)
(5, 1181, 221)
(5, 1182, 222)
(5, 1183, 223)
(5, 1184, 224)
(5, 1185, 225)
(5, 1186, 226)
(5, 1187, 227)
(5, 1188, 228)
(5, 1189, 229)
(5, 1190, 230)
(5, 1191, 231)
(5, 1192, 232)
(5, 1193, 233)
(5, 1194, 234)
(5, 1195, 235)
(5, 1196, 236)
(5, 1197, 237)
(5, 1198, 238)
(5, 1199, 239)
(5, 1200, 240)
(6, 1201, 1)
(6, 1202, 2)
(6, 1203, 3)
(6, 1204, 4)
(6, 1205, 5)
(6, 1206, 6)
(6, 1207, 7)
(6, 1208, 8)
(6, 1209, 9)
(6, 1210, 10)
(6, 1211, 11)
(6, 1212, 12)
(6, 1213, 13)
(6, 1214, 14)
(6, 1215, 15)
(6, 1216, 16)
(6, 1217, 17)
(6, 1218, 18)
(6, 1219, 19)
(6, 1220, 20)
(6, 1221, 21)
(6, 1222, 22)
(6, 1223, 23)
(6, 1224, 24)
(6, 1225, 25)
(6, 1226, 26)
(6, 1227, 27)
(6, 1228, 28)
(6, 1229, 29)
(6, 1230, 30)
(6, 1231, 31)
(6, 1232, 32)
(6, 1233, 33)
(6, 1234, 34)
(6, 1235, 35)
(6, 1236, 36)
(6, 1237, 37)
(6, 1238, 38)
(6, 1239, 39)
(6, 1240, 40)
(6, 1241, 41)
(6, 1242, 42)
(6, 1243, 43)
(6, 1244, 44)
(6, 1245, 45)
(6, 1246, 46)
(6, 1247, 47)
(6, 1248, 48)
(6, 1249, 49)
(6, 1250, 50)
(6, 1251, 51)
(6, 1252, 52)
(6, 1253, 53)
(6, 1254, 54)
(6, 1255, 55)
(6, 1256, 56)
(6, 1257, 57)
(6, 1258, 58)
(6, 1259, 59)
(6, 1260, 60)
(6, 1261, 61)
(6, 1262, 62)
(6, 1263, 63)
(6, 1264, 64)
(6, 1265, 65)
(6, 1266, 66)
(6, 1267, 67)
(6, 1268, 68)
(6, 1269, 69)
(6, 1270, 70)
(6, 1271, 71)
(6, 1272, 72)
(6, 1273, 73)
(6, 1274, 74)
(6, 1275, 75)
(6, 1276, 76)
(6, 1277, 77)
(6, 1278, 78)
(6, 1279, 79)
(6, 1280, 80)
(6, 1281, 81)
(6, 1282, 82)
(6, 1283, 83)
(6, 1284, 84)
(6, 1285, 85)
(6, 1286, 86)
(6, 1287, 87)
(6, 1288, 88)
(6, 1289, 89)
(6, 1290, 90)
(6, 1291, 91)
(6, 1292, 92)
(6, 1293, 93)
(6, 1294, 94)
(6, 1295, 95)
(6, 1296, 96)
(6, 1297, 97)
(6, 1298, 98)
(6, 1299, 99)
(6, 1300, 100)
(6, 1301, 101)
(6, 1302, 102)
(6, 1303, 103)
(6, 1304, 104)
(6, 1305, 105)
(6, 1306, 106)
(6, 1307, 107)
(6, 1308, 108)
(6, 1309, 109)
(6, 1310, 110)
(6, 1311, 111)
(6, 1312, 112)
(6, 1313, 113)
(6, 1314, 114)
(6, 1315, 115)
(6, 1316, 116)
(6, 1317, 117)
(6, 1318, 118)
(6, 1319, 119)
(6, 1320, 120)
(6, 1321, 121)
(6, 1322, 122)
(6, 1323, 123)
(6, 1324, 124)
(6, 1325, 125)
(6, 1326, 126)
(6, 1327, 127)
(6, 1328, 128)
(6, 1329, 129)
(6, 1330, 130)
(6, 1331, 131)
(6, 1332, 132)
(6, 1333, 133)
(6, 1334, 134)
(6, 1335, 135)
(6, 1336, 136)
(6, 1337, 137)
(6, 1338, 138)
(6, 1339, 139)
(6, 1340, 140)
(6, 1341, 141)
(6, 1342, 142)
(6, 1343, 143)
(6, 1344, 144)
(6, 1345, 145)
(6, 1346, 146)
(6, 1347, 147)
(6, 1348, 148)
(6, 1349, 149)
(6, 1350, 150)
(6, 1351, 151)
(6, 1352, 152)
(6, 1353, 153)
(6, 1354, 154)
(6, 1355, 155)
(6, 1356, 156)
(6, 1357, 157)
(6, 1358, 158)
(6, 1359, 159)
(6, 1360, 160)
(6, 1361, 161)
(6, 1362, 162)
(6, 1363, 163)
(6, 1364, 164)
(6, 1365, 165)
(6, 1366, 166)
(6, 1367, 167)
(6, 1368, 168)
(6, 1369, 169)
(6, 1370, 170)
(6, 1371, 171)
(6, 1372, 172)
(6, 1373, 173)
(6, 1374, 174)
(6, 1375, 175)
(6, 1376, 176)
(6, 1377, 177)
(6, 1378, 178)
(6, 1379, 179)
(6, 1380, 180)
(6, 1381, 181)
(6, 1382, 182)
(6, 1383, 183)
(6, 1384, 184)
(6, 1385, 185)
(6, 1386, 186)
(6, 1387, 187)
(6, 1388, 188)
(6, 1389, 189)
(6, 1390, 190)
(6, 1391, 191)
(6, 1392, 192)
(6, 1393, 193)
(6, 1394, 194)
(6, 1395, 195)
(6, 1396, 196)
(6, 1397, 197)
(6, 1398, 198)
(6, 1399, 199)
(6, 1400, 200)
(6, 1401, 201)
(6, 1402, 202)
(6, 1403, 203)
(6, 1404, 204)
(6, 1405, 205)
(6, 1406, 206)
(6, 1407, 207)
(6, 1408, 208)
(6, 1409, 209)
(6, 1410, 210)
(6, 1411, 211)
(6, 1412, 212)
(6, 1413, 213)
(6, 1414, 214)
(6, 1415, 215)
(6, 1416, 216)
(6, 1417, 217)
(6, 1418, 218)
(6, 1419, 219)
(6, 1420, 220)
(6, 1421, 221)
(6, 1422, 222)
(6, 1423, 223)
(6, 1424, 224)
(6, 1425, 225)
(6, 1426, 226)
(6, 1427, 227)
(6, 1428, 228)
(6, 1429, 229)
(6, 1430, 230)
(6, 1431, 231)
(6, 1432, 232)
(6, 1433, 233)
(6, 1434, 234)
(6, 1435, 235)
(6, 1436, 236)
(6, 1437, 237)
(6, 1438, 238)
(6, 1439, 239)
(6, 1440, 240)
(7, 1441, 1)
(7, 1442, 2)
(7, 1443, 3)
(7, 1444, 4)
(7, 1445, 5)
(7, 1446, 6)
(7, 1447, 7)
(7, 1448, 8)
(7, 1449, 9)
(7, 1450, 10)
(7, 1451, 11)

## Product price

In [39]:
product_price

,price_id,market_price,current_retail_price,discounted_price,is_discounted,last_update_date,product_id
0,1,4.12,3.78,NaN,no,2026-03-29,1
1,2,6.48,6.21,NaN,no,2026-03-29,2
2,3,5.65,5.12,NaN,no,2026-03-29,3
3,4,2.21,1.55,1.37,yes,2026-03-29,4
4,5,4.91,4.65,NaN,no,2026-03-29,5
...,...,...,...,...,...,...,...
235,236,3.52,2.64,1.20,yes,2026-03-29,236
236,237,3.44,2.17,NaN,no,2026-03-29,237
237,238,6.72,5.37,NaN,no,2026-03-29,238
238,239,8.41,7.91,NaN,no,2026-03-29,239
239,240,10.10,9.27,9.09,yes,2026-03-29,240

In [40]:
import numpy as np

product_price = product_price.replace({np.nan: None, "": None})

In [41]:
query = "INSERT INTO product_price(price_id,market_price, current_retail_price, discounted_price, is_discounted, last_update_date, product_id) VALUES (%s,%s,%s,%s,%s,%s,%s)"
data = list(product_price.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM product_price")
for i in cursor:
    print(i)

(1, Decimal('4.12'), Decimal('3.78'), None, 'no', datetime.date(2026, 3, 29), 1)
(2, Decimal('6.48'), Decimal('6.21'), None, 'no', datetime.date(2026, 3, 29), 2)
(3, Decimal('5.65'), Decimal('5.12'), None, 'no', datetime.date(2026, 3, 29), 3)
(4, Decimal('2.21'), Decimal('1.55'), Decimal('1.37'), 'yes', datetime.date(2026, 3, 29), 4)
(5, Decimal('4.91'), Decimal('4.65'), None, 'no', datetime.date(2026, 3, 29), 5)
(6, Decimal('2.44'), Decimal('1.86'), None, 'no', datetime.date(2026, 3, 29), 6)
(7, Decimal('7.74'), Decimal('7.43'), None, 'no', datetime.date(2026, 3, 29), 7)
(8, Decimal('3.40'), Decimal('2.64'), Decimal('1.21'), 'yes', datetime.date(2026, 3, 29), 8)
(9, Decimal('5.95'), Decimal('5.39'), None, 'no', datetime.date(2026, 3, 29), 9)
(10, Decimal('8.82'), Decimal('8.58'), None, 'no', datetime.date(2026, 3, 29), 10)
(11, Decimal('7.97'), Decimal('7.51'), None, 'no', datetime.date(2026, 3, 29), 11)
(12, Decimal('2.83'), Decimal('2.52'), Decimal('1.95'), 'yes', datetime.date(2026, 3, 29), 12)
(13, Decimal('7.67'), Decimal('7.31'), None, 'no', datetime.date(2026, 3, 29), 13)
(14, Decimal('5.98'), Decimal('5.20'), None, 'no', datetime.date(2026, 3, 29), 14)
(15, Decimal('4.47'), Decimal('3.78'), None, 'no', datetime.date(2026, 3, 29), 15)
(16, Decimal('2.24'), Decimal('1.99'), Decimal('1.56'), 'yes', datetime.date(2026, 3, 29), 16)
(17, Decimal('6.69'), Decimal('6.11'), None, 'no', datetime.date(2026, 3, 29), 17)
(18, Decimal('4.05'), Decimal('3.32'), None, 'no', datetime.date(2026, 3, 29), 18)
(19, Decimal('5.05'), Decimal('4.58'), None, 'no', datetime.date(2026, 3, 29), 19)
(20, Decimal('7.51'), Decimal('6.68'), Decimal('6.20'), 'yes', datetime.date(2026, 3, 29), 20)
(21, Decimal('5.22'), Decimal('4.60'), None, 'no', datetime.date(2026, 3, 29), 21)
(22, Decimal('7.18'), Decimal('6.40'), None, 'no', datetime.date(2026, 3, 29), 22)
(23, Decimal('3.36'), Decimal('2.38'), None, 'no', datetime.date(2026, 3, 29), 23)
(24, Decimal('2.26'), Decimal('1.73'), Decimal('0.75'), 'yes', datetime.date(2026, 3, 29), 24)
(25, Decimal('2.48'), Decimal('1.89'), None, 'no', datetime.date(2026, 3, 29), 25)
(26, Decimal('1.74'), Decimal('1.01'), None, 'no', datetime.date(2026, 3, 29), 26)
(27, Decimal('6.46'), Decimal('5.80'), None, 'no', datetime.date(2026, 3, 29), 27)
(28, Decimal('7.18'), Decimal('6.73'), Decimal('5.64'), 'yes', datetime.date(2026, 3, 29), 28)
(29, Decimal('5.35'), Decimal('4.69'), None, 'no', datetime.date(2026, 3, 29), 29)
(30, Decimal('4.46'), Decimal('3.59'), None, 'no', datetime.date(2026, 3, 29), 30)
(31, Decimal('7.63'), Decimal('7.05'), None, 'no', datetime.date(2026, 3, 29), 31)
(32, Decimal('5.81'), Decimal('5.56'), Decimal('4.46'), 'yes', datetime.date(2026, 3, 29), 32)
(33, Decimal('5.70'), Decimal('4.71'), None, 'no', datetime.date(2026, 3, 29), 33)
(34, Decimal('6.83'), Decimal('6.40'), None, 'no', datetime.date(2026, 3, 29), 34)
(35, Decimal('4.00'), Decimal('3.27'), None, 'no', datetime.date(2026, 3, 29), 35)
(36, Decimal('1.64'), Decimal('1.07'), Decimal('0.85'), 'yes', datetime.date(2026, 3, 29), 36)
(37, Decimal('2.25'), Decimal('2.00'), None, 'no', datetime.date(2026, 3, 29), 37)
(38, Decimal('6.48'), Decimal('6.18'), None, 'no', datetime.date(2026, 3, 29), 38)
(39, Decimal('3.10'), Decimal('2.59'), None, 'no', datetime.date(2026, 3, 29), 39)
(40, Decimal('7.15'), Decimal('6.89'), Decimal('6.13'), 'yes', datetime.date(2026, 3, 29), 40)
(41, Decimal('6.29'), Decimal('5.19'), None, 'no', datetime.date(2026, 3, 29), 41)
(42, Decimal('7.91'), Decimal('6.83'), None, 'no', datetime.date(2026, 3, 29), 42)
(43, Decimal('4.66'), Decimal('3.99'), None, 'no', datetime.date(2026, 3, 29), 43)
(44, Decimal('5.14'), Decimal('4.04'), Decimal('2.60'), 'yes', datetime.date(2026, 3, 29), 44)
(45, Decimal('3.90'), Decimal('3.44'), None, 'no', datetime.date(2026, 3, 29), 45)
(46, Decimal('4.38'), Decimal('3.87'), None, 'no', datetime.date(2026, 3, 29), 46)
(47, Decimal('5.90'), Decimal('5.07'), None, 'no', datetime.date(2026, 3, 29), 47)
(48, Decimal('4.57'), Decimal('4.27'), Decimal('3.55'), 'yes', datetime.date(2026, 3, 29), 48)
(49, Decimal('5.21'), Decimal('4.40'), None, 'no', datetime.date(2026, 3, 29), 49)
(50, Decimal('8.71'), Decimal('7.79'), None, 'no', datetime.date(2026, 3, 29), 50)
(51, Decimal('6.08'), Decimal('5.22'), None, 'no', datetime.date(2026, 3, 29), 51)
(52, Decimal('7.05'), Decimal('6.70'), Decimal('5.34'), 'yes', datetime.date(2026, 3, 29), 52)
(53, Decimal('7.67'), Decimal('6.58'), None, 'no', datetime.date(2026, 3, 29), 53)
(54, Decimal('7.78'), Decimal('7.13'), None, 'no', datetime.date(2026, 3, 29), 54)
(55, Decimal('5.38'), Decimal('4.99'), None, 'no', datetime.date(2026, 3, 29), 55)
(56, Decimal('6.80'), Decimal('6.44'), Decimal('6.20'), 'yes', datetime.date(2026, 3, 29), 56)
(57, Decimal('4.24'), Decimal('3.79'), None, 'no', datetime.date(2026, 3, 29), 57)
(58, Decimal('5.03'), Decimal('4.68'), None, 'no', datetime.date(2026, 3, 29), 58)
(59, Decimal('2.99'), Decimal('2.55'), None, 'no', datetime.date(2026, 3, 29), 59)
(60, Decimal('3.60'), Decimal('2.97'), Decimal('2.79'), 'yes', datetime.date(2026, 3, 29), 60)
(61, Decimal('7.74'), Decimal('7.05'), None, 'no', datetime.date(2026, 3, 29), 61)
(62, Decimal('3.38'), Decimal('2.98'), None, 'no', datetime.date(2026, 3, 29), 62)
(63, Decimal('4.57'), Decimal('4.08'), None, 'no', datetime.date(2026, 3, 29), 63)
(64, Decimal('3.23'), Decimal('2.35'), Decimal('0.86'), 'yes', datetime.date(2026, 3, 29), 64)
(65, Decimal('5.29'), Decimal('4.70'), None, 'no', datetime.date(2026, 3, 29), 65)
(66, Decimal('3.01'), Decimal('2.73'), None, 'no', datetime.date(2026, 3, 29), 66)
(67, Decimal('4.55'), Decimal('4.14'), None, 'no', datetime.date(2026, 3, 29), 67)
(68, Decimal('7.46'), Decimal('7.13'), Decimal('6.95'), 'yes', datetime.date(2026, 3, 29), 68)
(69, Decimal('8.20'), Decimal('7.58'), None, 'no', datetime.date(2026, 3, 29), 69)
(70, Decimal('3.37'), Decimal('2.74'), None, 'no', datetime.date(2026, 3, 29), 70)
(71, Decimal('2.65'), Decimal('2.03'), None, 'no', datetime.date(2026, 3, 29), 71)
(72, Decimal('8.36'), Decimal('7.47'), Decimal('6.38'), 'yes', datetime.date(2026, 3, 29), 72)
(73, Decimal('4.06'), Decimal('3.57'), None, 'no', datetime.date(2026, 3, 29), 73)
(74, Decimal('3.49'), Decimal('2.67'), None, 'no', datetime.date(2026, 3, 29), 74)
(75, Decimal('5.69'), Decimal('4.87'), None, 'no', datetime.date(2026, 3, 29), 75)
(76, Decimal('4.47'), Decimal('4.09'), Decimal('2.84'), 'yes', datetime.date(2026, 3, 29), 76)
(77, Decimal('8.40'), Decimal('7.52'), None, 'no', datetime.date(2026, 3, 29), 77)
(78, Decimal('7.33'), Decimal('6.48'), None, 'no', datetime.date(2026, 3, 29), 78)
(79, Decimal('6.93'), Decimal('6.55'), None, 'no', datetime.date(2026, 3, 29), 79)
(80, Decimal('5.60'), Decimal('5.12'), Decimal('4.93'), 'yes', datetime.date(2026, 3, 29), 80)
(81, Decimal('6.35'), Decimal('5.37'), None, 'no', datetime.date(2026, 3, 29), 81)
(82, Decimal('9.36'), Decimal('7.68'), None, 'no', datetime.date(2026, 3, 29), 82)
(83, Decimal('18.42'), Decimal('17.16'), None, 'no', datetime.date(2026, 3, 29), 83)
(84, Decimal('18.17'), Decimal('15.99'), Decimal('14.55'), 'yes', datetime.date(2026, 3, 29), 84)
(85, Decimal('10.73'), Decimal('9.86'), None, 'no', datetime.date(2026, 3, 29), 85)
(86, Decimal('8.94'), Decimal('8.11'), None, 'no', datetime.date(2026, 3, 29), 86)
(87, Decimal('8.65'), Decimal('7.09'), None, 'no', datetime.date(2026, 3, 29), 87)
(88, Decimal('17.69'), Decimal('15.76'), Decimal('14.96'), 'yes', datetime.date(2026, 3, 29), 88)
(89, Decimal('14.48'), Decimal('12.62'), None, 'no', datetime.date(2026, 3, 29), 89)
(90, Decimal('7.09'), Decimal('5.47'), None, 'no', datetime.date(2026, 3, 29), 90)
(91, Decimal('17.82'), Decimal('15.99'), None, 'no', datetime.date(2026, 3, 29), 91)
(92, Decimal('15.74'), Decimal('14.43'), Decimal('14.04'), 'yes', datetime.date(2026, 3, 29), 92)
(93, Decimal('16.25'), Decimal('15.18'), None, 'no', datetime.date(2026, 3, 29), 93)
(94, Decimal('16.40'), Decimal('14.25'), None, 'no', datetime.date(2026, 3, 29), 94)
(95, Decimal('11.14'), Decimal('9.96'), None, 'no', datetime.date(2026, 3, 29), 95)
(96, Decimal('18.30'), Decimal('16.57'), Decimal('16.19'), 'yes', datetime.date(2026, 3, 29), 96)
(97, Decimal('7.64'), Decimal('6.88'), None, 'no', datetime.date(2026, 3, 29), 97)
(98, Decimal('17.75'), Decimal('15.88'), None, 'no', datetime.date(2026, 3, 29), 98)
(99, Decimal('7.89'), Decimal('5.98'), None, 'no', datetime.date(2026, 3, 29), 99)
(100, Decimal('18.73'), Decimal('17.11'), Decimal('16.49'), 'yes', datetime.date(2026, 3, 29), 100)
(101, Decimal('9.35'), Decimal('8.85'), None, 'no', datetime.date(2026, 3, 29), 101)
(102, Decimal('2.67'), Decimal('0.91'), None, 'no', datetime.date(2026, 3, 29), 102)
(103, Decimal('10.61'), Decimal('9.52'), None, 'no', datetime.date(2026, 3, 29), 103)
(104, Decimal('14.16'), Decimal('13.21'), Decimal('11.88'), 'yes', datetime.date(2026, 3, 29), 104)
(105, Decimal('12.82'), Decimal('12.20'), None, 'no', datetime.date(2026, 3, 29), 105)
(106, Decimal('5.64'), Decimal('4.90'), None, 'no', datetime.date(2026, 3, 29), 106)
(107, Decimal('5.50'), Decimal('4.32'), None, 'no', datetime.date(2026, 3, 29), 107)
(108, Decimal('5.73'), Decimal('4.80'), Decimal('4.47'), 'yes', datetime.date(2026, 3, 29), 108)
(109, Decimal('13.87'), Decimal('13.04'), None, 'no', datetime.date(2026, 3, 29), 109)
(110, Decimal('8.22'), Decimal('7.04'), None, 'no', datetime.date(2026, 3, 29), 110)
(111, Decimal('13.79'), Decimal('12.86'), None, 'no', datetime.date(2026, 3, 29), 111)
(112, Decimal('13.96'), Decimal('12.91'), Decimal('12.04'), 'yes', datetime.date(2026, 3, 29), 112)
(113, Decimal('9.03'), Decimal('8.70'), None, 'no', datetime.date(2026, 3, 29), 113)
(114, Decimal('7.99'), Decimal('7.42'), None, 'no', datetime.date(2026, 3, 29), 114)
(115, Decimal('2.54'), Decimal('1.04'), None, 'no', datetime.date(2026, 3, 29), 115)
(116, Decimal('4.64'), Decimal('3.63'), Decimal('2.50'), 'yes', datetime.date(2026, 3, 29), 116)
(117, Decimal('9.45'), Decimal('8.66'), None, 'no', datetime.date(2026, 3, 29), 117)
(118, Decimal('8.97'), Decimal('7.84'), None, 'no', datetime.date(2026, 3, 29), 118)
(119, Decimal('12.29'), Decimal('11.83'), None, 'no', datetime.date(2026, 3, 29), 119)
(120, Decimal('9.49'), Decimal('8.82'), Decimal('8.30'), 'yes', datetime.date(2026, 3, 29), 120)
(121, Decimal('8.05'), Decimal('7.34'), None, 'no', datetime.date(2026, 3, 29), 121)
(122, Decimal('6.26'), Decimal('5.30'), None, 'no', datetime.date(2026, 3, 29), 122)
(123, Decimal('9.25'), Decimal('8.61'), None, 'no', datetime.date(2026, 3, 29), 123)
(124, Decimal('6.70'), Decimal('5.99'), Decimal('5.15'), 'yes', datetime.date(2026, 3, 29), 124)
(125, Decimal('7.38'), Decimal('6.73'), None, 'no', datetime.date(2026, 3, 29), 125)
(126, Decimal('6.02'), Decimal('5.34'), None, 'no', datetime.date(2026, 3, 29), 126)
(127, Decimal('9.49'), Decimal('8.59'), None, 'no', datetime.date(2026, 3, 29), 127)
(128, Decimal('8.94'), Decimal('7.80'), Decimal('7.30'), 'yes', datetime.date(2026, 3, 29), 128)
(129, Decimal('6.25'), Decimal('5.11'), None, 'no', datetime.date(2026, 3, 29), 129)
(130, Decimal('8.63'), Decimal('8.29'), None, 'no', datetime.date(2026, 3, 29), 130)
(131, Decimal('2.52'), Decimal('1.88'), None, 'no', datetime.date(2026, 3, 29), 131)
(132, Decimal('2.11'), Decimal('1.67'), Decimal('1.44'), 'yes', datetime.date(2026, 3, 29), 132)
(133, Decimal('7.18'), Decimal('6.20'), None, 'no', datetime.date(2026, 3, 29), 133)
(134, Decimal('9.11'), Decimal('8.76'), None, 'no', datetime.date(2026, 3, 29), 134)
(135, Decimal('7.58'), Decimal('6.72'), None, 'no', datetime.date(2026, 3, 29), 135)
(136, Decimal('2.71'), Decimal('1.63'), Decimal('0.52'), 'yes', datetime.date(2026, 3, 29), 136)
(137, Decimal('3.36'), Decimal('2.21'), None, 'no', datetime.date(2026, 3, 29), 137)
(138, Decimal('4.88'), Decimal('4.19'), None, 'no', datetime.date(2026, 3, 29), 138)
(139, Decimal('9.90'), Decimal('8.87'), None, 'no', datetime.date(2026, 3, 29), 139)
(140, Decimal('2.86'), Decimal('2.23'), Decimal('1.38'), 'yes', datetime.date(2026, 3, 29), 140)
(141, Decimal('6.38'), Decimal('5.85'), None, 'no', datetime.date(2026, 3, 29), 141)
(142, Decimal('6.18'), Decimal('5.01'), None, 'no', datetime.date(2026, 3, 29), 142)
(143, Decimal('3.18'), Decimal('2.22'), None, 'no', datetime.date(2026, 3, 29), 143)
(144, Decimal('7.39'), Decimal('7.07'), Decimal('6.47'), 'yes', datetime.date(2026, 3, 29), 144)
(145, Decimal('9.23'), Decimal('8.32'), None, 'no', datetime.date(2026, 3, 29), 145)
(146, Decimal('3.63'), Decimal('2.15'), None, 'no', datetime.date(2026, 3, 29), 146)
(147, Decimal('10.87'), Decimal('9.40'), None, 'no', datetime.date(2026, 3, 29), 147)
(148, Decimal('4.04'), Decimal('3.42'), Decimal('3.22'), 'yes', datetime.date(2026, 3, 29), 148)
(149, Decimal('10.78'), Decimal('10.16'), None, 'no', datetime.date(2026, 3, 29), 149)
(150, Decimal('4.29'), Decimal('3.48'), None, 'no', datetime.date(2026, 3, 29), 150)
(151, Decimal('12.10'), Decimal('10.82'), None, 'no', datetime.date(2026, 3, 29), 151)
(152, Decimal('5.58'), Decimal('5.10'), Decimal('3.71'), 'yes', datetime.date(2026, 3, 29), 152)
(153, Decimal('8.70'), Decimal('7.56'), None, 'no', datetime.date(2026, 3, 29), 153)
(154, Decimal('3.88'), Decimal('3.51'), None, 'no', datetime.date(2026, 3, 29), 154)
(155, Decimal('9.87'), Decimal('9.06'), None, 'no', datetime.date(2026, 3, 29), 155)
(156, Decimal('3.71'), Decimal('2.28'), Decimal('1.27'), 'yes', datetime.date(2026, 3, 29), 156)
(157, Decimal('11.01'), Decimal('10.61'), None, 'no', datetime.date(2026, 3, 29), 157)
(158, Decimal('11.55'), Decimal('11.17'), None, 'no', datetime.date(2026, 3, 29), 158)
(159, Decimal('11.62'), Decimal('10.78'), None, 'no', datetime.date(2026, 3, 29), 159)
(160, Decimal('6.38'), Decimal('5.42'), Decimal('4.02'), 'yes', datetime.date(2026, 3, 29), 160)
(161, Decimal('6.74'), Decimal('5.98'), None, 'no', datetime.date(2026, 3, 29), 161)
(162, Decimal('10.37'), Decimal('9.39'), None, 'no', datetime.date(2026, 3, 29), 162)
(163, Decimal('4.52'), Decimal('3.70'), None, 'no', datetime.date(2026, 3, 29), 163)
(164, Decimal('3.70'), Decimal('2.80'), Decimal('2.23'), 'yes', datetime.date(2026, 3, 29), 164)
(165, Decimal('7.26'), Decimal('5.24'), None, 'no', datetime.date(2026, 3, 29), 165)
(166, Decimal('7.05'), Decimal('5.55'), None, 'no', datetime.date(2026, 3, 29), 166)
(167, Decimal('5.48'), Decimal('4.29'), None, 'no', datetime.date(2026, 3, 29), 167)
(168, Decimal('3.24'), Decimal('2.24'), Decimal('2.07'), 'yes', datetime.date(2026, 3, 29), 168)
(169, Decimal('13.25'), Decimal('11.65'), None, 'no', datetime.date(2026, 3, 29), 169)
(170, Decimal('5.64'), Decimal('4.19'), None, 'no', datetime.date(2026, 3, 29), 170)
(171, Decimal('16.07'), Decimal('15.36'), None, 'no', datetime.date(2026, 3, 29), 171)
(172, Decimal('14.45'), Decimal('13.09'), Decimal('12.27'), 'yes', datetime.date(2026, 3, 29), 172)
(173, Decimal('14.67'), Decimal('13.38'), None, 'no', datetime.date(2026, 3, 29), 173)
(174, Decimal('10.08'), Decimal('8.20'), None, 'no', datetime.date(2026, 3, 29), 174)
(175, Decimal('16.74'), Decimal('15.55'), None, 'no', datetime.date(2026, 3, 29), 175)
(176, Decimal('14.64'), Decimal('12.73'), Decimal('11.72'), 'yes', datetime.date(2026, 3, 29), 176)
(177, Decimal('8.66'), Decimal('7.46'), None, 'no', datetime.date(2026, 3, 29), 177)
(178, Decimal('3.75'), Decimal('2.99'), None, 'no', datetime.date(2026, 3, 29), 178)
(179, Decimal('3.98'), Decimal('2.00'), None, 'no', datetime.date(2026, 3, 29), 179)
(180, Decimal('6.57'), Decimal('5.74'), Decimal('5.48'), 'yes', datetime.date(2026, 3, 29), 180)
(181, Decimal('11.24'), Decimal('9.46'), None, 'no', datetime.date(2026, 3, 29), 181)
(182, Decimal('9.37'), Decimal('8.59'), None, 'no', datetime.date(2026, 3, 29), 182)
(183, Decimal('4.65'), Decimal('3.85'), None, 'no', datetime.date(2026, 3, 29), 183)
(184, Decimal('7.04'), Decimal('6.47'), Decimal('5.72'), 'yes', datetime.date(2026, 3, 29), 184)
(185, Decimal('4.89'), Decimal('2.95'), None, 'no', datetime.date(2026, 3, 29), 185)
(186, Decimal('12.69'), Decimal('11.46'), None, 'no', datetime.date(2026, 3, 29), 186)
(187, Decimal('4.68'), Decimal('2.74'), None, 'no', datetime.date(2026, 3, 29), 187)
(188, Decimal('5.40'), Decimal('4.49'), Decimal('4.34'), 'yes', datetime.date(2026, 3, 29), 188)
(189, Decimal('6.19'), Decimal('5.08'), None, 'no', datetime.date(2026, 3, 29), 189)
(190, Decimal('7.52'), Decimal('6.88'), None, 'no', datetime.date(2026, 3, 29), 190)
(191, Decimal('7.54'), Decimal('7.23'), None, 'no', datetime.date(2026, 3, 29), 191)
(192, Decimal('4.90'), Decimal('4.45'), Decimal('3.76'), 'yes', datetime.date(2026, 3, 29), 192)
(193, Decimal('2.45'), Decimal('2.11'), None, 'no', datetime.date(2026, 3, 29), 193)
(194, Decimal('5.34'), Decimal('4.64'), None, 'no', datetime.date(2026, 3, 29), 194)
(195, Decimal('8.43'), Decimal('7.23'), None, 'no', datetime.date(2026, 3, 29), 195)
(196, Decimal('10.25'), Decimal('8.83'), Decimal('7.71'), 'yes', datetime.date(2026, 3, 29), 196)
(197, Decimal('11.66'), Decimal('10.70'), None, 'no', datetime.date(2026, 3, 29), 197)
(198, Decimal('5.58'), Decimal('3.61'), None, 'no', datetime.date(2026, 3, 29), 198)
(199, Decimal('3.63'), Decimal('2.10'), None, 'no', datetime.date(2026, 3, 29), 199)
(200, Decimal('9.07'), Decimal('8.70'), Decimal('7.42'), 'yes', datetime.date(2026, 3, 29), 200)
(201, Decimal('14.40'), Decimal('13.20'), None, 'no', datetime.date(2026, 3, 29), 201)
(202, Decimal('12.08'), Decimal('10.58'), None, 'no', datetime.date(2026, 3, 29), 202)
(203, Decimal('3.34'), Decimal('2.30'), None, 'no', datetime.date(2026, 3, 29), 203)
(204, Decimal('8.70'), Decimal('7.16'), Decimal('5.92'), 'yes', datetime.date(2026, 3, 29), 204)
(205, Decimal('13.44'), Decimal('12.31'), None, 'no', datetime.date(2026, 3, 29), 205)
(206, Decimal('14.41'), Decimal('13.12'), None, 'no', datetime.date(2026, 3, 29), 206)
(207, Decimal('11.48'), Decimal('10.91'), None, 'no', datetime.date(2026, 3, 29), 207)
(208, Decimal('1.75'), Decimal('1.34'), Decimal('0.94'), 'yes', datetime.date(2026, 3, 29), 208)
(209, Decimal('2.83'), Decimal('1.29'), None, 'no', datetime.date(2026, 3, 29), 209)
(210, Decimal('9.50'), Decimal('8.30'), None, 'no', datetime.date(2026, 3, 29), 210)
(211, Decimal('10.50'), Decimal('9.21'), None, 'no', datetime.date(2026, 3, 29), 211)
(212, Decimal('8.48'), Decimal('8.27'), Decimal('7.04'), 'yes', datetime.date(2026, 3, 29), 212)
(213, Decimal('12.29'), Decimal('11.29'), None, 'no', datetime.date(2026, 3, 29), 213)
(214, Decimal('9.16'), Decimal('7.91'), None, 'no', datetime.date(2026, 3, 29), 214)
(215, Decimal('2.26'), Decimal('0.88'), None, 'no', datetime.date(2026, 3, 29), 215)
(216, Decimal('5.00'), Decimal('4.68'), Decimal('4.17'), 'yes', datetime.date(2026, 3, 29), 216)
(217, Decimal('12.01'), Decimal('11.48'), None, 'no', datetime.date(2026, 3, 29), 217)
(218, Decimal('12.17'), Decimal('10.41'), None, 'no', datetime.date(2026, 3, 29), 218)
(219, Decimal('8.55'), Decimal('7.74'), None, 'no', datetime.date(2026, 3, 29), 219)
(220, Decimal('8.33'), Decimal('7.04'), Decimal('5.85'), 'yes', datetime.date(2026, 3, 29), 220)
(221, Decimal('7.66'), Decimal('6.62'), None, 'no', datetime.date(2026, 3, 29), 221)
(222, Decimal('2.96'), Decimal('2.57'), None, 'no', datetime.date(2026, 3, 29), 222)
(223, Decimal('4.50'), Decimal('3.33'), None, 'no', datetime.date(2026, 3, 29), 223)
(224, Decimal('4.94'), Decimal('4.00'), Decimal('3.83'), 'yes', datetime.date(2026, 3, 29), 224)
(225, Decimal('2.82'), Decimal('2.27'), None, 'no', datetime.date(2026, 3, 29), 225)
(226, Decimal('8.14'), Decimal('7.04'), None, 'no', datetime.date(2026, 3, 29), 226)
(227, Decimal('8.17'), Decimal('7.59'), None, 'no', datetime.date(2026, 3, 29), 227)
(228, Decimal('6.78'), Decimal('5.98'), Decimal('5.20'), 'yes', datetime.date(2026, 3, 29), 228)

## product images

In [42]:
product_images

,product_id,image_url,image_description
0,1,cdn.local/products/banana-bunch.jpg,Banana Bunch product image
1,2,cdn.local/products/gala-apples-3-lb.jpg,Gala Apples 3 lb product image
2,3,cdn.local/products/fuji-apples-3-lb.jpg,Fuji Apples 3 lb product image
3,4,cdn.local/products/navel-oranges-4-lb.jpg,Navel Oranges 4 lb product image
4,5,cdn.local/products/red-seedless-grapes-2-lb.jpg,Red Seedless Grapes 2 lb product image
...,...,...,...
235,236,cdn.local/products/bran-crunch-cereal-16-oz.jpg,Bran Crunch Cereal 16 oz product image
236,237,cdn.local/products/cinnamon-bagel-chips-7-oz.jpg,Cinnamon Bagel Chips 7 oz product image
237,238,cdn.local/products/honey-breakfast-biscuits-5-...,Honey Breakfast Biscuits 5 ct product image
238,239,cdn.local/products/chia-oat-cups-4-ct.jpg,Chia Oat Cups 4 ct product image
239,240,cdn.local/products/protein-pancake-mix-20-oz.jpg,Protein Pancake Mix 20 oz product image

In [43]:
query = "INSERT INTO product_images(product_id, image_url, image_description) VALUES (%s,%s,%s)"
data = list(product_images.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM product_images")
for i in cursor:
    print(i)

(1, 'cdn.local/products/banana-bunch.jpg', 'Banana Bunch product image')
(2, 'cdn.local/products/gala-apples-3-lb.jpg', 'Gala Apples 3 lb product image')
(3, 'cdn.local/products/fuji-apples-3-lb.jpg', 'Fuji Apples 3 lb product image')
(4, 'cdn.local/products/navel-oranges-4-lb.jpg', 'Navel Oranges 4 lb product image')
(5, 'cdn.local/products/red-seedless-grapes-2-lb.jpg', 'Red Seedless Grapes 2 lb product image')
(6, 'cdn.local/products/green-seedless-grapes-2-lb.jpg', 'Green Seedless Grapes 2 lb product image')
(7, 'cdn.local/products/strawberries-1-lb.jpg', 'Strawberries 1 lb product image')
(8, 'cdn.local/products/blueberries-1-pint.jpg', 'Blueberries 1 pint product image')
(9, 'cdn.local/products/raspberries-6-oz.jpg', 'Raspberries 6 oz product image')
(10, 'cdn.local/products/blackberries-6-oz.jpg', 'Blackberries 6 oz product image')
(11, 'cdn.local/products/ataulfo-mango.jpg', 'Ataulfo Mango product image')
(12, 'cdn.local/products/pineapple-whole.jpg', 'Pineapple Whole product image')
(13, 'cdn.local/products/mini-watermelon.jpg', 'Mini Watermelon product image')
(14, 'cdn.local/products/cantaloupe-whole.jpg', 'Cantaloupe Whole product image')
(15, 'cdn.local/products/honeydew-melon.jpg', 'Honeydew Melon product image')
(16, 'cdn.local/products/bartlett-pears-2-lb.jpg', 'Bartlett Pears 2 lb product image')
(17, 'cdn.local/products/yellow-peaches-2-lb.jpg', 'Yellow Peaches 2 lb product image')
(18, 'cdn.local/products/black-plums-2-lb.jpg', 'Black Plums 2 lb product image')
(19, 'cdn.local/products/kiwi-4-ct.jpg', 'Kiwi 4 ct product image')
(20, 'cdn.local/products/lemons-2-lb.jpg', 'Lemons 2 lb product image')
(21, 'cdn.local/products/roma-tomatoes-1-lb.jpg', 'Roma Tomatoes 1 lb product image')
(22, 'cdn.local/products/vine-tomatoes-1-lb.jpg', 'Vine Tomatoes 1 lb product image')
(23, 'cdn.local/products/baby-spinach-5-oz.jpg', 'Baby Spinach 5 oz product image')
(24, 'cdn.local/products/romaine-hearts-3-ct.jpg', 'Romaine Hearts 3 ct product image')
(25, 'cdn.local/products/broccoli-crowns.jpg', 'Broccoli Crowns product image')
(26, 'cdn.local/products/cauliflower-head.jpg', 'Cauliflower Head product image')
(27, 'cdn.local/products/carrots-2-lb.jpg', 'Carrots 2 lb product image')
(28, 'cdn.local/products/celery-bunch.jpg', 'Celery Bunch product image')
(29, 'cdn.local/products/english-cucumber.jpg', 'English Cucumber product image')
(30, 'cdn.local/products/red-bell-pepper.jpg', 'Red Bell Pepper product image')
(31, 'cdn.local/products/green-bell-pepper.jpg', 'Green Bell Pepper product image')
(32, 'cdn.local/products/yellow-onions-3-lb.jpg', 'Yellow Onions 3 lb product image')
(33, 'cdn.local/products/garlic-bulb.jpg', 'Garlic Bulb product image')
(34, 'cdn.local/products/russet-potatoes-5-lb.jpg', 'Russet Potatoes 5 lb product image')
(35, 'cdn.local/products/sweet-potatoes-3-lb.jpg', 'Sweet Potatoes 3 lb product image')
(36, 'cdn.local/products/zucchini-1-lb.jpg', 'Zucchini 1 lb product image')
(37, 'cdn.local/products/white-mushrooms-8-oz.jpg', 'White Mushrooms 8 oz product image')
(38, 'cdn.local/products/green-beans-12-oz.jpg', 'Green Beans 12 oz product image')
(39, 'cdn.local/products/sweet-corn-4-ct.jpg', 'Sweet Corn 4 ct product image')
(40, 'cdn.local/products/green-cabbage.jpg', 'Green Cabbage product image')
(41, 'cdn.local/products/whole-milk-1-gal.jpg', 'Whole Milk 1 gal product image')
(42, 'cdn.local/products/2percent-milk-1-gal.jpg', '2% Milk 1 gal product image')
(43, 'cdn.local/products/skim-milk-1-gal.jpg', 'Skim Milk 1 gal product image')
(44, 'cdn.local/products/plain-greek-yogurt-32-oz.jpg', 'Plain Greek Yogurt 32 oz product image')
(45, 'cdn.local/products/vanilla-greek-yogurt-32-oz.jpg', 'Vanilla Greek Yogurt 32 oz product image')
(46, 'cdn.local/products/sharp-cheddar-block-8-oz.jpg', 'Sharp Cheddar Block 8 oz product image')
(47, 'cdn.local/products/shredded-mozzarella-8-oz.jpg', 'Shredded Mozzarella 8 oz product image')
(48, 'cdn.local/products/grated-parmesan-8-oz.jpg', 'Grated Parmesan 8 oz product image')
(49, 'cdn.local/products/salted-butter-16-oz.jpg', 'Salted Butter 16 oz product image')
(50, 'cdn.local/products/unsalted-butter-16-oz.jpg', 'Unsalted Butter 16 oz product image')
(51, 'cdn.local/products/large-eggs-12-ct.jpg', 'Large Eggs 12 ct product image')
(52, 'cdn.local/products/egg-whites-16-oz.jpg', 'Egg Whites 16 oz product image')
(53, 'cdn.local/products/sour-cream-16-oz.jpg', 'Sour Cream 16 oz product image')
(54, 'cdn.local/products/cream-cheese-8-oz.jpg', 'Cream Cheese 8 oz product image')
(55, 'cdn.local/products/heavy-whipping-cream-16-oz.jpg', 'Heavy Whipping Cream 16 oz product image')
(56, 'cdn.local/products/half-and-half-32-oz.jpg', 'Half & Half 32 oz product image')
(57, 'cdn.local/products/low-fat-cottage-cheese-24-oz.jpg', 'Low Fat Cottage Cheese 24 oz product image')
(58, 'cdn.local/products/fruit-yogurt-4-ct.jpg', 'Fruit Yogurt 4 ct product image')
(59, 'cdn.local/products/chocolate-milk-1-qt.jpg', 'Chocolate Milk 1 qt product image')
(60, 'cdn.local/products/string-cheese-12-ct.jpg', 'String Cheese 12 ct product image')
(61, 'cdn.local/products/whole-wheat-bread-loaf.jpg', 'Whole Wheat Bread Loaf product image')
(62, 'cdn.local/products/white-sandwich-bread.jpg', 'White Sandwich Bread product image')
(63, 'cdn.local/products/sourdough-bread.jpg', 'Sourdough Bread product image')
(64, 'cdn.local/products/multigrain-bread.jpg', 'Multigrain Bread product image')
(65, 'cdn.local/products/plain-bagels-6-ct.jpg', 'Plain Bagels 6 ct product image')
(66, 'cdn.local/products/sesame-bagels-6-ct.jpg', 'Sesame Bagels 6 ct product image')
(67, 'cdn.local/products/butter-croissants-4-ct.jpg', 'Butter Croissants 4 ct product image')
(68, 'cdn.local/products/blueberry-muffins-4-ct.jpg', 'Blueberry Muffins 4 ct product image')
(69, 'cdn.local/products/chocolate-muffins-4-ct.jpg', 'Chocolate Muffins 4 ct product image')
(70, 'cdn.local/products/cinnamon-rolls-4-ct.jpg', 'Cinnamon Rolls 4 ct product image')
(71, 'cdn.local/products/chocolate-cake-slice.jpg', 'Chocolate Cake Slice product image')
(72, 'cdn.local/products/vanilla-cupcakes-6-ct.jpg', 'Vanilla Cupcakes 6 ct product image')
(73, 'cdn.local/products/dinner-rolls-12-ct.jpg', 'Dinner Rolls 12 ct product image')
(74, 'cdn.local/products/hamburger-buns-8-ct.jpg', 'Hamburger Buns 8 ct product image')
(75, 'cdn.local/products/hot-dog-buns-8-ct.jpg', 'Hot Dog Buns 8 ct product image')
(76, 'cdn.local/products/pita-bread-6-ct.jpg', 'Pita Bread 6 ct product image')
(77, 'cdn.local/products/flour-tortillas-10-ct.jpg', 'Flour Tortillas 10 ct product image')
(78, 'cdn.local/products/corn-tortillas-20-ct.jpg', 'Corn Tortillas 20 ct product image')
(79, 'cdn.local/products/assorted-donuts-6-ct.jpg', 'Assorted Donuts 6 ct product image')
(80, 'cdn.local/products/brownie-tray-4-ct.jpg', 'Brownie Tray 4 ct product image')
(81, 'cdn.local/products/boneless-chicken-breast-1-lb.jpg', 'Boneless Chicken Breast 1 lb product image')
(82, 'cdn.local/products/boneless-chicken-thighs-1-lb.jpg', 'Boneless Chicken Thighs 1 lb product image')
(83, 'cdn.local/products/chicken-wings-family-pack.jpg', 'Chicken Wings Family Pack product image')
(84, 'cdn.local/products/whole-chicken.jpg', 'Whole Chicken product image')
(85, 'cdn.local/products/ground-turkey-93percent-lean-1-lb.jpg', 'Ground Turkey 93% Lean 1 lb product image')
(86, 'cdn.local/products/turkey-breast-cutlets-1-lb.jpg', 'Turkey Breast Cutlets 1 lb product image')
(87, 'cdn.local/products/turkey-breast-deli-8-oz.jpg', 'Turkey Breast Deli 8 oz product image')
(88, 'cdn.local/products/chicken-sausage-mild-12-oz.jpg', 'Chicken Sausage Mild 12 oz product image')
(89, 'cdn.local/products/turkey-sausage-links-12-oz.jpg', 'Turkey Sausage Links 12 oz product image')
(90, 'cdn.local/products/atlantic-salmon-fillet-1-lb.jpg', 'Atlantic Salmon Fillet 1 lb product image')
(91, 'cdn.local/products/tilapia-fillets-1-lb.jpg', 'Tilapia Fillets 1 lb product image')
(92, 'cdn.local/products/cod-fillets-1-lb.jpg', 'Cod Fillets 1 lb product image')
(93, 'cdn.local/products/raw-shrimp-1-lb.jpg', 'Raw Shrimp 1 lb product image')
(94, 'cdn.local/products/cooked-shrimp-1-lb.jpg', 'Cooked Shrimp 1 lb product image')
(95, 'cdn.local/products/sea-scallops-12-oz.jpg', 'Sea Scallops 12 oz product image')
(96, 'cdn.local/products/mussels-1-lb.jpg', 'Mussels 1 lb product image')
(97, 'cdn.local/products/crab-cakes-2-ct.jpg', 'Crab Cakes 2 ct product image')
(98, 'cdn.local/products/smoked-salmon-4-oz.jpg', 'Smoked Salmon 4 oz product image')
(99, 'cdn.local/products/lobster-tails-2-ct.jpg', 'Lobster Tails 2 ct product image')
(100, 'cdn.local/products/breaded-fish-fillets-16-oz.jpg', 'Breaded Fish Fillets 16 oz product image')
(101, 'cdn.local/products/orange-juice-52-oz.jpg', 'Orange Juice 52 oz product image')
(102, 'cdn.local/products/apple-juice-64-oz.jpg', 'Apple Juice 64 oz product image')
(103, 'cdn.local/products/lime-sparkling-water-8-pk.jpg', 'Lime Sparkling Water 8 pk product image')
(104, 'cdn.local/products/berry-sparkling-water-8-pk.jpg', 'Berry Sparkling Water 8 pk product image')
(105, 'cdn.local/products/cola-12-pk.jpg', 'Cola 12 pk product image')
(106, 'cdn.local/products/diet-cola-12-pk.jpg', 'Diet Cola 12 pk product image')
(107, 'cdn.local/products/lemonade-59-oz.jpg', 'Lemonade 59 oz product image')
(108, 'cdn.local/products/lemon-iced-tea-64-oz.jpg', 'Lemon Iced Tea 64 oz product image')
(109, 'cdn.local/products/cold-brew-coffee-48-oz.jpg', 'Cold Brew Coffee 48 oz product image')
(110, 'cdn.local/products/medium-roast-ground-coffee-12-oz.jpg', 'Medium Roast Ground Coffee 12 oz product image')
(111, 'cdn.local/products/breakfast-blend-coffee-pods-12-ct.jpg', 'Breakfast Blend Coffee Pods 12 ct product image')
(112, 'cdn.local/products/black-tea-bags-40-ct.jpg', 'Black Tea Bags 40 ct product image')
(113, 'cdn.local/products/green-tea-bags-40-ct.jpg', 'Green Tea Bags 40 ct product image')
(114, 'cdn.local/products/blue-sports-drink-8-pk.jpg', 'Blue Sports Drink 8 pk product image')
(115, 'cdn.local/products/citrus-energy-drink-4-pk.jpg', 'Citrus Energy Drink 4 pk product image')
(116, 'cdn.local/products/coconut-water-1-l.jpg', 'Coconut Water 1 L product image')
(117, 'cdn.local/products/purified-water-24-pk.jpg', 'Purified Water 24 pk product image')
(118, 'cdn.local/products/unsweetened-almond-milk-64-oz.jpg', 'Unsweetened Almond Milk 64 oz product image')
(119, 'cdn.local/products/original-oat-milk-64-oz.jpg', 'Original Oat Milk 64 oz product image')
(120, 'cdn.local/products/hot-chocolate-mix-10-ct.jpg', 'Hot Chocolate Mix 10 ct product image')
(121, 'cdn.local/products/classic-potato-chips-8-oz.jpg', 'Classic Potato Chips 8 oz product image')
(122, 'cdn.local/products/barbecue-potato-chips-8-oz.jpg', 'Barbecue Potato Chips 8 oz product image')
(123, 'cdn.local/products/restaurant-style-tortilla-chips-13-oz.jpg', 'Restaurant Style Tortilla Chips 13 oz product image')
(124, 'cdn.local/products/pretzel-twists-16-oz.jpg', 'Pretzel Twists 16 oz product image')
(125, 'cdn.local/products/chocolate-chip-cookies-13-oz.jpg', 'Chocolate Chip Cookies 13 oz product image')
(126, 'cdn.local/products/oatmeal-raisin-cookies-13-oz.jpg', 'Oatmeal Raisin Cookies 13 oz product image')
(127, 'cdn.local/products/milk-chocolate-bar-1-55-oz.jpg', 'Milk Chocolate Bar 1.55 oz product image')
(128, 'cdn.local/products/dark-chocolate-bar-3-5-oz.jpg', 'Dark Chocolate Bar 3.5 oz product image')
(129, 'cdn.local/products/deluxe-trail-mix-14-oz.jpg', 'Deluxe Trail Mix 14 oz product image')
(130, 'cdn.local/products/roasted-mixed-nuts-10-oz.jpg', 'Roasted Mixed Nuts 10 oz product image')
(131, 'cdn.local/products/butter-popcorn-6-ct.jpg', 'Butter Popcorn 6 ct product image')
(132, 'cdn.local/products/peanut-protein-bars-5-ct.jpg', 'Peanut Protein Bars 5 ct product image')
(133, 'cdn.local/products/variety-granola-bars-6-ct.jpg', 'Variety Granola Bars 6 ct product image')
(134, 'cdn.local/products/original-crackers-13-7-oz.jpg', 'Original Crackers 13.7 oz product image')
(135, 'cdn.local/products/baked-cheese-crackers-12-4-oz.jpg', 'Baked Cheese Crackers 12.4 oz product image')
(136, 'cdn.local/products/fruit-snacks-10-ct.jpg', 'Fruit Snacks 10 ct product image')
(137, 'cdn.local/products/sea-salt-rice-cakes-4-47-oz.jpg', 'Sea Salt Rice Cakes 4.47 oz product image')
(138, 'cdn.local/products/plant-based-jerky-2-5-oz.jpg', 'Plant Based Jerky 2.5 oz product image')
(139, 'cdn.local/products/gummy-bears-8-oz.jpg', 'Gummy Bears 8 oz product image')
(140, 'cdn.local/products/peanut-butter-sandwich-crackers-8-ct.jpg', 'Peanut Butter Sandwich Crackers 8 ct product image')
(141, 'cdn.local/products/margherita-frozen-pizza-14-oz.jpg', 'Margherita Frozen Pizza 14 oz product image')
(142, 'cdn.local/products/pepperoni-frozen-pizza-15-oz.jpg', 'Pepperoni Frozen Pizza 15 oz product image')
(143, 'cdn.local/products/frozen-mixed-vegetables-12-oz.jpg', 'Frozen Mixed Vegetables 12 oz product image')
(144, 'cdn.local/products/frozen-broccoli-florets-12-oz.jpg', 'Frozen Broccoli Florets 12 oz product image')
(145, 'cdn.local/products/frozen-french-fries-28-oz.jpg', 'Frozen French Fries 28 oz product image')
(146, 'cdn.local/products/frozen-chicken-nuggets-32-oz.jpg', 'Frozen Chicken Nuggets 32 oz product image')
(147, 'cdn.local/products/frozen-waffles-10-ct.jpg', 'Frozen Waffles 10 ct product image')
(148, 'cdn.local/products/frozen-pancakes-12-ct.jpg', 'Frozen Pancakes 12 ct product image')
(149, 'cdn.local/products/vanilla-ice-cream-48-oz.jpg', 'Vanilla Ice Cream 48 oz product image')
(150, 'cdn.local/products/chocolate-ice-cream-48-oz.jpg', 'Chocolate Ice Cream 48 oz product image')
(151, 'cdn.local/products/frozen-berry-blend-16-oz.jpg', 'Frozen Berry Blend 16 oz product image')
(152, 'cdn.local/products/frozen-mango-chunks-16-oz.jpg', 'Frozen Mango Chunks 16 oz product image')
(153, 'cdn.local/products/family-size-frozen-lasagna-38-oz.jpg', 'Family Size Frozen Lasagna 38 oz product image')
(154, 'cdn.local/products/frozen-mac-and-cheese-12-oz.jpg', 'Frozen Mac & Cheese 12 oz product image')
(155, 'cdn.local/products/frozen-fish-sticks-24-oz.jpg', 'Frozen Fish Sticks 24 oz product image')
(156, 'cdn.local/products/frozen-shrimp-tempura-9-2-oz.jpg', 'Frozen Shrimp Tempura 9.2 oz product image')
(157, 'cdn.local/products/frozen-pie-crusts-2-ct.jpg', 'Frozen Pie Crusts 2 ct product image')
(158, 'cdn.local/products/frozen-garlic-bread-16-oz.jpg', 'Frozen Garlic Bread 16 oz product image')
(159, 'cdn.local/products/frozen-turkey-meatballs-20-oz.jpg', 'Frozen Turkey Meatballs 20 oz product image')
(160, 'cdn.local/products/frozen-cheesecake-slices-16-oz.jpg', 'Frozen Cheesecake Slices 16 oz product image')
(161, 'cdn.local/products/lemon-dish-soap-19-4-oz.jpg', 'Lemon Dish Soap 19.4 oz product image')
(162, 'cdn.local/products/free-and-clear-dish-soap-19-4-oz.jpg', 'Free & Clear Dish Soap 19.4 oz product image')
(163, 'cdn.local/products/laundry-detergent-64-oz.jpg', 'Laundry Detergent 64 oz product image')
(164, 'cdn.local/products/fabric-softener-50-oz.jpg', 'Fabric Softener 50 oz product image')
(165, 'cdn.local/products/paper-towels-6-ct.jpg', 'Paper Towels 6 ct product image')
(166, 'cdn.local/products/toilet-paper-12-ct.jpg', 'Toilet Paper 12 ct product image')
(167, 'cdn.local/products/kitchen-trash-bags-30-ct.jpg', 'Kitchen Trash Bags 30 ct product image')
(168, 'cdn.local/products/heavy-duty-aluminum-foil-75-ft.jpg', 'Heavy Duty Aluminum Foil 75 ft product image')
(169, 'cdn.local/products/plastic-wrap-200-ft.jpg', 'Plastic Wrap 200 ft product image')
(170, 'cdn.local/products/cleaning-sponges-6-ct.jpg', 'Cleaning Sponges 6 ct product image')
(171, 'cdn.local/products/glass-cleaner-32-oz.jpg', 'Glass Cleaner 32 oz product image')
(172, 'cdn.local/products/disinfecting-wipes-75-ct.jpg', 'Disinfecting Wipes 75 ct product image')
(173, 'cdn.local/products/all-purpose-cleaner-32-oz.jpg', 'All Purpose Cleaner 32 oz product image')
(174, 'cdn.local/products/household-bleach-81-oz.jpg', 'Household Bleach 81 oz product image')
(175, 'cdn.local/products/indoor-broom.jpg', 'Indoor Broom product image')
(176, 'cdn.local/products/mop-refill-head.jpg', 'Mop Refill Head product image')
(177, 'cdn.local/products/sandwich-zipper-bags-100-ct.jpg', 'Sandwich Zipper Bags 100 ct product image')
(178, 'cdn.local/products/freezer-zipper-bags-40-ct.jpg', 'Freezer Zipper Bags 40 ct product image')
(179, 'cdn.local/products/linen-air-freshener-8-oz.jpg', 'Linen Air Freshener 8 oz product image')
(180, 'cdn.local/products/aa-batteries-8-ct.jpg', 'AA Batteries 8 ct product image')
(181, 'cdn.local/products/herbal-shampoo-12-oz.jpg', 'Herbal Shampoo 12 oz product image')
(182, 'cdn.local/products/herbal-conditioner-12-oz.jpg', 'Herbal Conditioner 12 oz product image')
(183, 'cdn.local/products/mint-toothpaste-5-8-oz.jpg', 'Mint Toothpaste 5.8 oz product image')
(184, 'cdn.local/products/soft-toothbrushes-2-ct.jpg', 'Soft Toothbrushes 2 ct product image')
(185, 'cdn.local/products/fresh-body-wash-18-oz.jpg', 'Fresh Body Wash 18 oz product image')
(186, 'cdn.local/products/moisturizing-bar-soap-6-ct.jpg', 'Moisturizing Bar Soap 6 ct product image')
(187, 'cdn.local/products/aloe-hand-soap-12-5-oz.jpg', 'Aloe Hand Soap 12.5 oz product image')
(188, 'cdn.local/products/gentle-face-wash-8-oz.jpg', 'Gentle Face Wash 8 oz product image')
(189, 'cdn.local/products/fresh-deodorant-2-6-oz.jpg', 'Fresh Deodorant 2.6 oz product image')
(190, 'cdn.local/products/unscented-body-lotion-16-oz.jpg', 'Unscented Body Lotion 16 oz product image')
(191, 'cdn.local/products/sensitive-shaving-cream-11-oz.jpg', 'Sensitive Shaving Cream 11 oz product image')
(192, 'cdn.local/products/disposable-razors-4-ct.jpg', 'Disposable Razors 4 ct product image')
(193, 'cdn.local/products/cotton-swabs-300-ct.jpg', 'Cotton Swabs 300 ct product image')
(194, 'cdn.local/products/cotton-balls-200-ct.jpg', 'Cotton Balls 200 ct product image')
(195, 'cdn.local/products/facial-tissues-4-ct.jpg', 'Facial Tissues 4 ct product image')
(196, 'cdn.local/products/cool-mint-mouthwash-1-l.jpg', 'Cool Mint Mouthwash 1 L product image')
(197, 'cdn.local/products/waxed-dental-floss-2-pk.jpg', 'Waxed Dental Floss 2 pk product image')
(198, 'cdn.local/products/hand-sanitizer-8-oz.jpg', 'Hand Sanitizer 8 oz product image')
(199, 'cdn.local/products/original-lip-balm-0-15-oz.jpg', 'Original Lip Balm 0.15 oz product image')
(200, 'cdn.local/products/sunscreen-spf-50-6-oz.jpg', 'Sunscreen SPF 50 6 oz product image')
(201, 'cdn.local/products/basmati-rice-5-lb.jpg', 'Basmati Rice 5 lb product image')
(202, 'cdn.local/products/jasmine-rice-5-lb.jpg', 'Jasmine Rice 5 lb product image')
(203, 'cdn.local/products/penne-pasta-16-oz.jpg', 'Penne Pasta 16 oz product image')
(204, 'cdn.local/products/spaghetti-pasta-16-oz.jpg', 'Spaghetti Pasta 16 oz product image')
(205, 'cdn.local/products/extra-virgin-olive-oil-1-l.jpg', 'Extra Virgin Olive Oil 1 L product image')
(206, 'cdn.local/products/canola-oil-48-oz.jpg', 'Canola Oil 48 oz product image')
(207, 'cdn.local/products/all-purpose-flour-5-lb.jpg', 'All Purpose Flour 5 lb product image')
(208, 'cdn.local/products/granulated-sugar-4-lb.jpg', 'Granulated Sugar 4 lb product image')
(209, 'cdn.local/products/light-brown-sugar-2-lb.jpg', 'Light Brown Sugar 2 lb product image')
(210, 'cdn.local/products/iodized-salt-26-oz.jpg', 'Iodized Salt 26 oz product image')
(211, 'cdn.local/products/ground-black-pepper-4-oz.jpg', 'Ground Black Pepper 4 oz product image')
(212, 'cdn.local/products/canned-black-beans-15-oz.jpg', 'Canned Black Beans 15 oz product image')
(213, 'cdn.local/products/canned-chickpeas-15-oz.jpg', 'Canned Chickpeas 15 oz product image')
(214, 'cdn.local/products/canned-corn-15-25-oz.jpg', 'Canned Corn 15.25 oz product image')
(215, 'cdn.local/products/tomato-sauce-24-oz.jpg', 'Tomato Sauce 24 oz product image')
(216, 'cdn.local/products/creamy-peanut-butter-16-oz.jpg', 'Creamy Peanut Butter 16 oz product image')

## Store staff

In [44]:
store_staff

    emp_id           username password  store_id     role availability_status
0        1      olivia.parker  pass123         1  manager                 yes
1        2       chloe.martin  pass123         1   packer                 yes
2        3       jacob.turner  pass123         1   packer                 yes
3        4         grace.ward  pass123         1   packer                 yes
4        5      daniel.murphy  pass123         2  manager                 yes
5        6         mason.bell  pass123         2   packer                 yes
6        7          zoe.kelly  pass123         2   packer                 yes
7        8         henry.cook  pass123         2   packer                 yes
8        9     sophia.collins  pass123         3  manager                 yes
9       10        nora.bailey  pass123         3   packer                 yes
10      11       logan.cooper  pass123         3   packer                 yes
11      12        lily.rivera  pass123         3   packer                 yes
12      13         ethan.reed  pass123         4  manager                 yes
13      14      elijah.morris  pass123         4   packer                 yes
14      15    hannah.peterson  pass123         4   packer                 yes
15      16          jack.gray  pass123         4   packer                 yes
16      17        ava.bennett  pass123         5  manager                 yes
17      18         ella.james  pass123         5   packer                 yes
18      19        owen.watson  pass123         5   packer                 yes
19      20    scarlett.bryant  pass123         5   packer                 yes
20      21        liam.foster  pass123         6  manager                 yes
21      22       levi.russell  pass123         6   packer                 yes
22      23          aria.diaz  pass123         6   packer                 yes
23      24        wyatt.ortiz  pass123         6   packer                 yes
24      25          mia.hayes  pass123         7  manager                 yes
25      26      layla.sanders  pass123         7   packer                 yes
26      27      julian.powell  pass123         7   packer                 yes
27      28         sofia.long  pass123         7   packer                 yes
28      29        noah.brooks  pass123         8  manager                 yes
29      30        isaac.perry  pass123         8   packer                 yes
30      31       avery.hughes  pass123         8   packer                 yes
31      32   sebastian.flores  pass123         8   packer                 yes
32      33      emma.sullivan  pass123         9  manager                 yes
33      34  camila.washington  pass123         9   packer                 yes
34      35     gabriel.butler  pass123         9   packer                 yes
35      36   penelope.simmons  pass123         9   packer                 yes
36      37        lucas.price  pass123        10  manager                 yes
37      38      carter.foster  pass123        10   packer                 yes
38      39       riley.graham  pass123        10   packer                 yes
39      40        nathan.cole  pass123        10   packer                 yes

In [45]:
store_staff_details = store_staff[['emp_id','username','password','store_id']]
store_staff_details.head()

   emp_id       username password  store_id
0       1  olivia.parker  pass123         1
1       2   chloe.martin  pass123         1
2       3   jacob.turner  pass123         1
3       4     grace.ward  pass123         1
4       5  daniel.murphy  pass123         2

In [46]:
query = "INSERT INTO store_staff(emp_id, username, password, store_id) VALUES (%s,%s,%s,%s)"
data = list(store_staff_details.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM store_staff")
for i in cursor:
    print(i)

(1, 'olivia.parker', 'pass123', 1)
(2, 'chloe.martin', 'pass123', 1)
(3, 'jacob.turner', 'pass123', 1)
(4, 'grace.ward', 'pass123', 1)
(5, 'daniel.murphy', 'pass123', 2)
(6, 'mason.bell', 'pass123', 2)
(7, 'zoe.kelly', 'pass123', 2)
(8, 'henry.cook', 'pass123', 2)
(9, 'sophia.collins', 'pass123', 3)
(10, 'nora.bailey', 'pass123', 3)
(11, 'logan.cooper', 'pass123', 3)
(12, 'lily.rivera', 'pass123', 3)
(13, 'ethan.reed', 'pass123', 4)
(14, 'elijah.morris', 'pass123', 4)
(15, 'hannah.peterson', 'pass123', 4)
(16, 'jack.gray', 'pass123', 4)
(17, 'ava.bennett', 'pass123', 5)
(18, 'ella.james', 'pass123', 5)
(19, 'owen.watson', 'pass123', 5)
(20, 'scarlett.bryant', 'pass123', 5)
(21, 'liam.foster', 'pass123', 6)
(22, 'levi.russell', 'pass123', 6)
(23, 'aria.diaz', 'pass123', 6)
(24, 'wyatt.ortiz', 'pass123', 6)
(25, 'mia.hayes', 'pass123', 7)
(26, 'layla.sanders', 'pass123', 7)
(27, 'julian.powell', 'pass123', 7)
(28, 'sofia.long', 'pass123', 7)
(29, 'noah.brooks', 'pass123', 8)
(30, 'isaac.perry', 'pass123', 8)
(31, 'avery.hughes', 'pass123', 8)
(32, 'sebastian.flores', 'pass123', 8)
(33, 'emma.sullivan', 'pass123', 9)
(34, 'camila.washington', 'pass123', 9)
(35, 'gabriel.butler', 'pass123', 9)
(36, 'penelope.simmons', 'pass123', 9)
(37, 'lucas.price', 'pass123', 10)
(38, 'carter.foster', 'pass123', 10)
(39, 'riley.graham', 'pass123', 10)
(40, 'nathan.cole', 'pass123', 10)

## Store manager

In [47]:
manager_detail = store_staff[store_staff['role'] == 'manager']
manager_detail = manager_detail['emp_id']
manager_detail.head()

0      1
4      5
8      9
12    13
16    17
Name: emp_id, dtype: int64

In [48]:
query = "INSERT INTO store_manager(emp_id) VALUES (%s)"
data = []
for i in manager_detail:
    data.append([i])
cursor.executemany(query, data)
cursor.execute("SELECT * FROM store_manager")
for i in cursor:
    print(i)

(1,)
(5,)
(9,)
(13,)
(17,)
(21,)
(25,)
(29,)
(33,)
(37,)

## Packer

In [49]:
packer_detail = store_staff[store_staff['role'] == 'packer']
packer_detail = packer_detail[['emp_id',"availability_status"]]
packer_detail.head()

   emp_id availability_status
1       2                 yes
2       3                 yes
3       4                 yes
5       6                 yes
6       7                 yes

In [50]:
query = "INSERT INTO store_staff_packer(emp_id,Availability_status) VALUES (%s,%s)"
data = list(packer_detail.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM store_staff_packer")
for i in cursor:
    print(i)

(2, 'yes')
(3, 'yes')
(4, 'yes')
(6, 'yes')
(7, 'yes')
(8, 'yes')
(10, 'yes')
(11, 'yes')
(12, 'yes')
(14, 'yes')
(15, 'yes')
(16, 'yes')
(18, 'yes')
(19, 'yes')
(20, 'yes')
(22, 'yes')
(23, 'yes')
(24, 'yes')
(26, 'yes')
(27, 'yes')
(28, 'yes')
(30, 'yes')
(31, 'yes')
(32, 'yes')
(34, 'yes')
(35, 'yes')
(36, 'yes')
(38, 'yes')
(39, 'yes')
(40, 'yes')

# Customer

In [51]:
customer[['first_name', 'last_name']] = customer['name'].str.split(' ', n=1, expand=True)
customer = customer.drop(columns=['name'])
customer = customer[['customer_id', 'first_name', 'last_name', 'email', 'password', 'date_of_birth']]

In [52]:
customer

,customer_id,first_name,last_name,email,password,date_of_birth
0,1,Emma,Parker,emma.parker1@gmail.com,emma@123,1983-02-01
1,2,Liam,Murphy,liam.murphy2@outlook.com,liam@123,1973-12-07
2,3,Olivia,Collins,olivia.collins3@yahoo.com,olivia@123,1966-02-03
3,4,Noah,Reed,noah.reed4@icloud.com,noah@123,1992-06-25
4,5,Ava,Bennett,ava.bennett5@gmail.com,ava@123,1976-10-07
...,...,...,...,...,...,...
95,96,Connor,Chen,connor.chen96@icloud.com,connor@123,1969-06-13
96,97,Elena,Lin,elena.lin97@gmail.com,elena@123,1970-09-06
97,98,Jonathan,Wong,jonathan.wong98@outlook.com,jonathan@123,1993-10-22
98,99,Ruby,Zhang,ruby.zhang99@yahoo.com,ruby@123,1998-04-02
99,100,Jeremiah,Liu,jeremiah.liu100@icloud.com,jeremiah@123,1998-05-06

In [53]:
query = "INSERT INTO customer(customer_id, first_name, last_name, email, password, date_of_birth) VALUES (%s,%s,%s,%s,%s,%s)"
data = list(customer.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM customer")
for i in cursor:
    print(i)

(1, 'Emma', 'Parker', 'emma.parker1@gmail.com', 'emma@123', datetime.date(1983, 2, 1))
(2, 'Liam', 'Murphy', 'liam.murphy2@outlook.com', 'liam@123', datetime.date(1973, 12, 7))
(3, 'Olivia', 'Collins', 'olivia.collins3@yahoo.com', 'olivia@123', datetime.date(1966, 2, 3))
(4, 'Noah', 'Reed', 'noah.reed4@icloud.com', 'noah@123', datetime.date(1992, 6, 25))
(5, 'Ava', 'Bennett', 'ava.bennett5@gmail.com', 'ava@123', datetime.date(1976, 10, 7))
(6, 'Elijah', 'Foster', 'elijah.foster6@outlook.com', 'elijah@123', datetime.date(1985, 10, 3))
(7, 'Sophia', 'Hayes', 'sophia.hayes7@yahoo.com', 'sophia@123', datetime.date(1975, 3, 26))
(8, 'Lucas', 'Brooks', 'lucas.brooks8@icloud.com', 'lucas@123', datetime.date(1972, 2, 4))
(9, 'Isabella', 'Sullivan', 'isabella.sullivan9@gmail.com', 'isabella@123', datetime.date(2002, 6, 4))
(10, 'Mason', 'Price', 'mason.price10@outlook.com', 'mason@123', datetime.date(1978, 5, 5))
(11, 'Mia', 'Martin', 'mia.martin11@yahoo.com', 'mia@123', datetime.date(1999, 3, 24))
(12, 'Ethan', 'Turner', 'ethan.turner12@icloud.com', 'ethan@123', datetime.date(1968, 11, 14))
(13, 'Charlotte', 'Ward', 'charlotte.ward13@gmail.com', 'charlotte@123', datetime.date(1968, 9, 15))
(14, 'James', 'Bell', 'james.bell14@outlook.com', 'james@123', datetime.date(1977, 1, 3))
(15, 'Amelia', 'Kelly', 'amelia.kelly15@yahoo.com', 'amelia@123', datetime.date(1978, 2, 4))
(16, 'Benjamin', 'Cook', 'benjamin.cook16@icloud.com', 'benjamin@123', datetime.date(1980, 5, 4))
(17, 'Harper', 'Bailey', 'harper.bailey17@gmail.com', 'harper@123', datetime.date(1991, 3, 20))
(18, 'Alexander', 'Cooper', 'alexander.cooper18@outlook.com', 'alexander@123', datetime.date(1992, 7, 10))
(19, 'Evelyn', 'Rivera', 'evelyn.rivera19@yahoo.com', 'evelyn@123', datetime.date(1971, 1, 21))
(20, 'Michael', 'Morris', 'michael.morris20@icloud.com', 'michael@123', datetime.date(1970, 6, 18))
(21, 'Abigail', 'Peterson', 'abigail.peterson21@gmail.com', 'abigail@123', datetime.date(1993, 12, 9))
(22, 'Daniel', 'Gray', 'daniel.gray22@outlook.com', 'daniel@123', datetime.date(1990, 4, 26))
(23, 'Emily', 'James', 'emily.james23@yahoo.com', 'emily@123', datetime.date(1991, 12, 9))
(24, 'Henry', 'Watson', 'henry.watson24@icloud.com', 'henry@123', datetime.date(1998, 9, 10))
(25, 'Ella', 'Bryant', 'ella.bryant25@gmail.com', 'ella@123', datetime.date(1966, 11, 15))
(26, 'Jackson', 'Russell', 'jackson.russell26@outlook.com', 'jackson@123', datetime.date(1984, 5, 11))
(27, 'Avery', 'Diaz', 'avery.diaz27@yahoo.com', 'avery@123', datetime.date(1981, 9, 9))
(28, 'Sebastian', 'Ortiz', 'sebastian.ortiz28@icloud.com', 'sebastian@123', datetime.date(1997, 6, 4))
(29, 'Sofia', 'Sanders', 'sofia.sanders29@gmail.com', 'sofia@123', datetime.date(1965, 1, 9))
(30, 'Jack', 'Powell', 'jack.powell30@outlook.com', 'jack@123', datetime.date(1991, 2, 9))
(31, 'Camila', 'Long', 'camila.long31@yahoo.com', 'camila@123', datetime.date(1976, 12, 17))
(32, 'Owen', 'Perry', 'owen.perry32@icloud.com', 'owen@123', datetime.date(2004, 12, 21))
(33, 'Aria', 'Hughes', 'aria.hughes33@gmail.com', 'aria@123', datetime.date(1973, 10, 22))
(34, 'Theodore', 'Flores', 'theodore.flores34@outlook.com', 'theodore@123', datetime.date(1967, 10, 25))
(35, 'Scarlett', 'Washington', 'scarlett.washington35@yahoo.com', 'scarlett@123', datetime.date(1970, 3, 28))
(36, 'Levi', 'Butler', 'levi.butler36@icloud.com', 'levi@123', datetime.date(1999, 10, 28))
(37, 'Grace', 'Simmons', 'grace.simmons37@gmail.com', 'grace@123', datetime.date(1979, 12, 18))
(38, 'Mateo', 'Graham', 'mateo.graham38@outlook.com', 'mateo@123', datetime.date(1984, 1, 16))
(39, 'Chloe', 'Cole', 'chloe.cole39@yahoo.com', 'chloe@123', datetime.date(1978, 6, 14))
(40, 'Samuel', 'Baker', 'samuel.baker40@icloud.com', 'samuel@123', datetime.date(1975, 10, 14))
(41, 'Victoria', 'Richardson', 'victoria.richardson41@gmail.com', 'victoria@123', datetime.date(1976, 7, 27))
(42, 'Wyatt', 'Cox', 'wyatt.cox42@outlook.com', 'wyatt@123', datetime.date(1992, 10, 6))
(43, 'Riley', 'Howard', 'riley.howard43@yahoo.com', 'riley@123', datetime.date(1965, 7, 21))
(44, 'Julian', 'Ward', 'julian.ward44@icloud.com', 'julian@123', datetime.date(1987, 12, 22))
(45, 'Layla', 'Torres', 'layla.torres45@gmail.com', 'layla@123', datetime.date(1969, 10, 26))
(46, 'Asher', 'Peterson', 'asher.peterson46@outlook.com', 'asher@123', datetime.date(1995, 11, 5))
(47, 'Nora', 'Ramirez', 'nora.ramirez47@yahoo.com', 'nora@123', datetime.date(1978, 9, 21))
(48, 'Gabriel', 'Barnes', 'gabriel.barnes48@icloud.com', 'gabriel@123', datetime.date(1996, 9, 26))
(49, 'Lily', 'Ross', 'lily.ross49@gmail.com', 'lily@123', datetime.date(2001, 9, 5))
(50, 'Carter', 'Henderson', 'carter.henderson50@outlook.com', 'carter@123', datetime.date(1972, 10, 3))
(51, 'Zoey', 'Coleman', 'zoey.coleman51@yahoo.com', 'zoey@123', datetime.date(1981, 5, 18))
(52, 'Isaac', 'Jenkins', 'isaac.jenkins52@icloud.com', 'isaac@123', datetime.date(1969, 11, 27))
(53, 'Hannah', 'Patterson', 'hannah.patterson53@gmail.com', 'hannah@123', datetime.date(1974, 5, 1))
(54, 'Jayden', 'Perry', 'jayden.perry54@outlook.com', 'jayden@123', datetime.date(1967, 11, 1))
(55, 'Hazel', 'Powell', 'hazel.powell55@yahoo.com', 'hazel@123', datetime.date(2000, 7, 1))
(56, 'Lincoln', 'Long', 'lincoln.long56@icloud.com', 'lincoln@123', datetime.date(2004, 1, 27))
(57, 'Ellie', 'Fisher', 'ellie.fisher57@gmail.com', 'ellie@123', datetime.date(1973, 10, 22))
(58, 'Anthony', 'Ellis', 'anthony.ellis58@outlook.com', 'anthony@123', datetime.date(1998, 11, 18))
(59, 'Aurora', 'Kim', 'aurora.kim59@yahoo.com', 'aurora@123', datetime.date(2003, 2, 27))
(60, 'Hudson', 'Patel', 'hudson.patel60@icloud.com', 'hudson@123', datetime.date(1969, 4, 22))
(61, 'Penelope', 'Shah', 'penelope.shah61@gmail.com', 'penelope@123', datetime.date(1988, 11, 14))
(62, 'Dylan', 'Mehta', 'dylan.mehta62@outlook.com', 'dylan@123', datetime.date(1986, 1, 19))
(63, 'Natalie', 'Desai', 'natalie.desai63@yahoo.com', 'natalie@123', datetime.date(1988, 11, 2))
(64, 'Ezra', 'Kapoor', 'ezra.kapoor64@icloud.com', 'ezra@123', datetime.date(1987, 12, 7))
(65, 'Brooklyn', 'Malhotra', 'brooklyn.malhotra65@gmail.com', 'brooklyn@123', datetime.date(1971, 7, 18))
(66, 'Thomas', 'Singh', 'thomas.singh66@outlook.com', 'thomas@123', datetime.date(1969, 1, 2))
(67, 'Stella', 'Kaur', 'stella.kaur67@yahoo.com', 'stella@123', datetime.date(1986, 7, 21))
(68, 'Charles', 'Chopra', 'charles.chopra68@icloud.com', 'charles@123', datetime.date(1982, 9, 18))
(69, 'Lucy', 'Iyer', 'lucy.iyer69@gmail.com', 'lucy@123', datetime.date(1997, 7, 22))
(70, 'Christopher', 'Rao', 'christopher.rao70@outlook.com', 'christopher@123', datetime.date(1986, 12, 5))
(71, 'Paisley', 'Nair', 'paisley.nair71@yahoo.com', 'paisley@123', datetime.date(1996, 8, 12))
(72, 'Jaxon', 'Menon', 'jaxon.menon72@icloud.com', 'jaxon@123', datetime.date(1972, 1, 20))
(73, 'Savannah', 'Gupta', 'savannah.gupta73@gmail.com', 'savannah@123', datetime.date(1970, 11, 17))
(74, 'Josiah', 'Verma', 'josiah.verma74@outlook.com', 'josiah@123', datetime.date(1976, 9, 5))
(75, 'Claire', 'Das', 'claire.das75@yahoo.com', 'claire@123', datetime.date(1999, 4, 19))
(76, 'Isaiah', 'Banerjee', 'isaiah.banerjee76@icloud.com', 'isaiah@123', datetime.date(1972, 2, 2))
(77, 'Skylar', 'Mukherjee', 'skylar.mukherjee77@gmail.com', 'skylar@123', datetime.date(1973, 6, 6))
(78, 'Andrew', 'Reddy', 'andrew.reddy78@outlook.com', 'andrew@123', datetime.date(1994, 12, 20))
(79, 'Bella', 'Kulkarni', 'bella.kulkarni79@yahoo.com', 'bella@123', datetime.date(1997, 1, 25))
(80, 'Joshua', 'Joshi', 'joshua.joshi80@icloud.com', 'joshua@123', datetime.date(1990, 11, 21))
(81, 'Anna', 'Donovan', 'anna.donovan81@gmail.com', 'anna@123', datetime.date(1993, 4, 18))
(82, 'Nathan', 'McCarthy', 'nathan.mccarthy82@outlook.com', 'nathan@123', datetime.date(2001, 4, 4))
(83, 'Caroline', 'Obrien', 'caroline.obrien83@yahoo.com', 'caroline@123', datetime.date(1996, 9, 16))
(84, 'Adrian', 'Quinn', 'adrian.quinn84@icloud.com', 'adrian@123', datetime.date(1978, 7, 1))
(85, 'Sarah', 'Walsh', 'sarah.walsh85@gmail.com', 'sarah@123', datetime.date(1979, 4, 8))
(86, 'Caleb', 'Shea', 'caleb.shea86@outlook.com', 'caleb@123', datetime.date(1976, 7, 7))
(87, 'Madelyn', 'Fitzgerald', 'madelyn.fitzgerald87@yahoo.com', 'madelyn@123', datetime.date(1966, 1, 6))
(88, 'Ryan', 'Malone', 'ryan.malone88@icloud.com', 'ryan@123', datetime.date(1991, 12, 11))
(89, 'Kennedy', 'Santos', 'kennedy.santos89@gmail.com', 'kennedy@123', datetime.date(1968, 3, 1))
(90, 'Christian', 'Alvarez', 'christian.alvarez90@outlook.com', 'christian@123', datetime.date(1973, 2, 23))
(91, 'Maya', 'Morales', 'maya.morales91@yahoo.com', 'maya@123', datetime.date(1997, 12, 26))
(92, 'Aaron', 'Castro', 'aaron.castro92@icloud.com', 'aaron@123', datetime.date(1985, 9, 27))
(93, 'Allison', 'Nguyen', 'allison.nguyen93@gmail.com', 'allison@123', datetime.date(1985, 10, 19))
(94, 'Adam', 'Tran', 'adam.tran94@outlook.com', 'adam@123', datetime.date(1997, 3, 16))
(95, 'Naomi', 'Pham', 'naomi.pham95@yahoo.com', 'naomi@123', datetime.date(2004, 12, 10))
(96, 'Connor', 'Chen', 'connor.chen96@icloud.com', 'connor@123', datetime.date(1969, 6, 13))
(97, 'Elena', 'Lin', 'elena.lin97@gmail.com', 'elena@123', datetime.date(1970, 9, 6))
(98, 'Jonathan', 'Wong', 'jonathan.wong98@outlook.com', 'jonathan@123', datetime.date(1993, 10, 22))
(99, 'Ruby', 'Zhang', 'ruby.zhang99@yahoo.com', 'ruby@123', datetime.date(1998, 4, 2))
(100, 'Jeremiah', 'Liu', 'jeremiah.liu100@icloud.com', 'jeremiah@123', datetime.date(1998, 5, 6))

## Customer Address

In [54]:
customer_address

              street        city          state country  zip_code  customer_id
0      616 Beacon St      Quincy  Massachusetts     USA      2169            1
1    283 Pleasant St      Boston  Massachusetts     USA      2108            2
2      737 Summer St      Quincy  Massachusetts     USA      2169            3
3     68 Chestnut St      Boston  Massachusetts     USA      2108            4
4       762 Park Ave      Malden  Massachusetts     USA      2148            5
..               ...         ...            ...     ...       ...          ...
95      656 Broadway      Quincy  Massachusetts     USA      2169           96
96   239 Chestnut St      Quincy  Massachusetts     USA      2169           97
97      63 Summer St       Salem  Massachusetts     USA      1970           98
98     359 Walnut St      Revere  Massachusetts     USA      2151           99
99  219 Highland Ave  Somerville  Massachusetts     USA      2143          100

[100 rows x 6 columns]

In [55]:
query= "INSERT INTO customer_address (street, city, state, country, zip_code, customer_id) VALUES (%s,%s,%s,%s,%s,%s)"
data = list(customer_address.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM customer_address")
for i in cursor:
    print(i)

('616 Beacon St', 'Quincy', 'Massachusetts', 'USA', '2169', 1)
('283 Pleasant St', 'Boston', 'Massachusetts', 'USA', '2108', 2)
('737 Summer St', 'Quincy', 'Massachusetts', 'USA', '2169', 3)
('68 Chestnut St', 'Boston', 'Massachusetts', 'USA', '2108', 4)
('762 Park Ave', 'Malden', 'Massachusetts', 'USA', '2148', 5)
('843 Summer St', 'Somerville', 'Massachusetts', 'USA', '2143', 6)
('192 Franklin St', 'Medford', 'Massachusetts', 'USA', '2155', 7)
('446 Oak St', 'Malden', 'Massachusetts', 'USA', '2148', 8)
('388 Beacon St', 'Revere', 'Massachusetts', 'USA', '2151', 9)
('119 Massachusetts Ave', 'Cambridge', 'Massachusetts', 'USA', '2139', 10)
('616 Cedar St', 'Quincy', 'Massachusetts', 'USA', '2169', 11)
('412 Maple St', 'Somerville', 'Massachusetts', 'USA', '2143', 12)
('776 Pine St', 'Medford', 'Massachusetts', 'USA', '2155', 13)
('280 Pleasant St', 'Revere', 'Massachusetts', 'USA', '2151', 14)
('579 Prospect St', 'Watertown', 'Massachusetts', 'USA', '2472', 15)
('441 Walnut St', 'Boston', 'Massachusetts', 'USA', '2108', 16)
('714 School St', 'Cambridge', 'Massachusetts', 'USA', '2139', 17)
('800 Franklin St', 'Malden', 'Massachusetts', 'USA', '2148', 18)
('152 Highland Ave', 'Revere', 'Massachusetts', 'USA', '2151', 19)
('715 Franklin St', 'Cambridge', 'Massachusetts', 'USA', '2139', 20)
('14 Highland Ave', 'Quincy', 'Massachusetts', 'USA', '2169', 21)
('707 Maple St', 'Somerville', 'Massachusetts', 'USA', '2143', 22)
('501 Massachusetts Ave', 'Waltham', 'Massachusetts', 'USA', '2451', 23)
('281 Pine St', 'Brookline', 'Massachusetts', 'USA', '2445', 24)
('629 School St', 'Salem', 'Massachusetts', 'USA', '1970', 25)
('174 Main St', 'Boston', 'Massachusetts', 'USA', '2108', 26)
('717 Pine St', 'Quincy', 'Massachusetts', 'USA', '2169', 27)
('645 Pleasant St', 'Cambridge', 'Massachusetts', 'USA', '2139', 28)
('811 Cedar St', 'Brookline', 'Massachusetts', 'USA', '2445', 29)
('215 Park Ave', 'Malden', 'Massachusetts', 'USA', '2148', 30)
('415 Massachusetts Ave', 'Watertown', 'Massachusetts', 'USA', '2472', 31)
('629 Walnut St', 'Boston', 'Massachusetts', 'USA', '2108', 32)
('152 Beacon St', 'Newton', 'Massachusetts', 'USA', '2458', 33)
('615 Cedar St', 'Medford', 'Massachusetts', 'USA', '2155', 34)
('229 Chestnut St', 'Quincy', 'Massachusetts', 'USA', '2169', 35)
('971 School St', 'Watertown', 'Massachusetts', 'USA', '2472', 36)
('957 Beacon St', 'Newton', 'Massachusetts', 'USA', '2458', 37)
('414 Park Ave', 'Waltham', 'Massachusetts', 'USA', '2451', 38)
('442 Oak St', 'Boston', 'Massachusetts', 'USA', '2108', 39)
('385 River St', 'Medford', 'Massachusetts', 'USA', '2155', 40)
('386 Broadway', 'Newton', 'Massachusetts', 'USA', '2458', 41)
('950 Pleasant St', 'Brookline', 'Massachusetts', 'USA', '2445', 42)
('401 Washington St', 'Boston', 'Massachusetts', 'USA', '2108', 43)
('735 Washington St', 'Waltham', 'Massachusetts', 'USA', '2451', 44)
('536 Pleasant St', 'Revere', 'Massachusetts', 'USA', '2151', 45)
('666 Beacon St', 'Cambridge', 'Massachusetts', 'USA', '2139', 46)
('212 Park Ave', 'Salem', 'Massachusetts', 'USA', '1970', 47)
('564 Beacon St', 'Medford', 'Massachusetts', 'USA', '2155', 48)
('74 Elm St', 'Watertown', 'Massachusetts', 'USA', '2472', 49)
('859 Pine St', 'Boston', 'Massachusetts', 'USA', '2108', 50)
('596 School St', 'Watertown', 'Massachusetts', 'USA', '2472', 51)
('144 Walnut St', 'Brookline', 'Massachusetts', 'USA', '2445', 52)
('624 Main St', 'Boston', 'Massachusetts', 'USA', '2108', 53)
('152 Elm St', 'Boston', 'Massachusetts', 'USA', '2108', 54)
('883 Summer St', 'Cambridge', 'Massachusetts', 'USA', '2139', 55)
('180 Chestnut St', 'Salem', 'Massachusetts', 'USA', '1970', 56)
('123 Massachusetts Ave', 'Quincy', 'Massachusetts', 'USA', '2169', 57)
('672 Broadway', 'Malden', 'Massachusetts', 'USA', '2148', 58)
('608 Elm St', 'Cambridge', 'Massachusetts', 'USA', '2139', 59)
('522 Main St', 'Medford', 'Massachusetts', 'USA', '2155', 60)
('480 Chestnut St', 'Somerville', 'Massachusetts', 'USA', '2143', 61)
('616 Cedar St', 'Somerville', 'Massachusetts', 'USA', '2143', 62)
('787 Oak St', 'Newton', 'Massachusetts', 'USA', '2458', 63)
('485 Highland Ave', 'Salem', 'Massachusetts', 'USA', '1970', 64)
('692 Main St', 'Quincy', 'Massachusetts', 'USA', '2169', 65)
('888 Highland Ave', 'Waltham', 'Massachusetts', 'USA', '2451', 66)
('981 Elm St', 'Quincy', 'Massachusetts', 'USA', '2169', 67)
('985 Massachusetts Ave', 'Watertown', 'Massachusetts', 'USA', '2472', 68)
('767 Walnut St', 'Malden', 'Massachusetts', 'USA', '2148', 69)
('845 Maple St', 'Medford', 'Massachusetts', 'USA', '2155', 70)
('743 Oak St', 'Quincy', 'Massachusetts', 'USA', '2169', 71)
('635 River St', 'Medford', 'Massachusetts', 'USA', '2155', 72)
('719 Washington St', 'Salem', 'Massachusetts', 'USA', '1970', 73)
('513 Highland Ave', 'Waltham', 'Massachusetts', 'USA', '2451', 74)
('446 Oak St', 'Waltham', 'Massachusetts', 'USA', '2451', 75)
('140 Cedar St', 'Somerville', 'Massachusetts', 'USA', '2143', 76)
('113 Park Ave', 'Medford', 'Massachusetts', 'USA', '2155', 77)
('220 Broadway', 'Quincy', 'Massachusetts', 'USA', '2169', 78)
('680 Walnut St', 'Waltham', 'Massachusetts', 'USA', '2451', 79)
('54 Elm St', 'Newton', 'Massachusetts', 'USA', '2458', 80)
('916 Elm St', 'Watertown', 'Massachusetts', 'USA', '2472', 81)
('325 Summer St', 'Malden', 'Massachusetts', 'USA', '2148', 82)
('186 Massachusetts Ave', 'Quincy', 'Massachusetts', 'USA', '2169', 83)
('899 School St', 'Cambridge', 'Massachusetts', 'USA', '2139', 84)
('17 Beacon St', 'Revere', 'Massachusetts', 'USA', '2151', 85)
('212 Oak St', 'Revere', 'Massachusetts', 'USA', '2151', 86)
('390 Oak St', 'Waltham', 'Massachusetts', 'USA', '2451', 87)
('600 Summer St', 'Watertown', 'Massachusetts', 'USA', '2472', 88)
('106 Oak St', 'Brookline', 'Massachusetts', 'USA', '2445', 89)
('882 Pleasant St', 'Revere', 'Massachusetts', 'USA', '2151', 90)
('829 Oak St', 'Boston', 'Massachusetts', 'USA', '2108', 91)
('649 Summer St', 'Boston', 'Massachusetts', 'USA', '2108', 92)
('688 Oak St', 'Medford', 'Massachusetts', 'USA', '2155', 93)
('384 Pine St', 'Brookline', 'Massachusetts', 'USA', '2445', 94)
('310 River St', 'Quincy', 'Massachusetts', 'USA', '2169', 95)
('656 Broadway', 'Quincy', 'Massachusetts', 'USA', '2169', 96)
('239 Chestnut St', 'Quincy', 'Massachusetts', 'USA', '2169', 97)
('63 Summer St', 'Salem', 'Massachusetts', 'USA', '1970', 98)
('359 Walnut St', 'Revere', 'Massachusetts', 'USA', '2151', 99)
('219 Highland Ave', 'Somerville', 'Massachusetts', 'USA', '2143', 100)

## Customer card details

In [56]:
card_details[['first_name', 'last_name']] = card_details['card_name'].str.split(' ', n=1, expand=True)
card_details = card_details.drop(columns=['card_name'])
card_details = card_details[['card_id', 'first_name', 'last_name', 'last_4_digits', 'exp_date', 'customer_id']]

In [57]:
card_details

    card_id first_name last_name  last_4_digits    exp_date  customer_id
0         1       Emma    Parker           6212  2031-06-01            1
1         2       Liam    Murphy           3621  2031-08-01            2
2         3     Olivia   Collins            320  2031-11-01            3
3         4       Noah      Reed           9652  2029-11-01            4
4         5        Ava   Bennett           6040  2031-05-01            5
..      ...        ...       ...            ...         ...          ...
95       96     Connor      Chen           6667  2028-10-01           96
96       97      Elena       Lin           1806  2031-02-01           97
97       98   Jonathan      Wong           1243  2030-02-01           98
98       99       Ruby     Zhang           6292  2027-12-01           99
99      100   Jeremiah       Liu           2284  2031-03-01          100

[100 rows x 6 columns]

In [58]:
query = "INSERT INTO card_details (card_id, first_name, last_name, last_4_digits, exp_date, customer_id) VALUES (%s,%s,%s,%s,%s,%s)"
data = list(card_details.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM card_details")
for i in cursor:
    print(i)

(1, 'Emma', 'Parker', '6212', datetime.date(2031, 6, 1), 1)
(2, 'Liam', 'Murphy', '3621', datetime.date(2031, 8, 1), 2)
(3, 'Olivia', 'Collins', '320', datetime.date(2031, 11, 1), 3)
(4, 'Noah', 'Reed', '9652', datetime.date(2029, 11, 1), 4)
(5, 'Ava', 'Bennett', '6040', datetime.date(2031, 5, 1), 5)
(6, 'Elijah', 'Foster', '7914', datetime.date(2031, 8, 1), 6)
(7, 'Sophia', 'Hayes', '8520', datetime.date(2028, 10, 1), 7)
(8, 'Lucas', 'Brooks', '4514', datetime.date(2031, 5, 1), 8)
(9, 'Isabella', 'Sullivan', '4993', datetime.date(2030, 9, 1), 9)
(10, 'Mason', 'Price', '8077', datetime.date(2028, 6, 1), 10)
(11, 'Mia', 'Martin', '2740', datetime.date(2030, 1, 1), 11)
(12, 'Ethan', 'Turner', '3696', datetime.date(2027, 4, 1), 12)
(13, 'Charlotte', 'Ward', '261', datetime.date(2030, 8, 1), 13)
(14, 'James', 'Bell', '3221', datetime.date(2030, 5, 1), 14)
(15, 'Amelia', 'Kelly', '2780', datetime.date(2031, 9, 1), 15)
(16, 'Benjamin', 'Cook', '7285', datetime.date(2029, 11, 1), 16)
(17, 'Harper', 'Bailey', '3906', datetime.date(2031, 5, 1), 17)
(18, 'Alexander', 'Cooper', '9010', datetime.date(2027, 5, 1), 18)
(19, 'Evelyn', 'Rivera', '7052', datetime.date(2028, 3, 1), 19)
(20, 'Michael', 'Morris', '3851', datetime.date(2031, 8, 1), 20)
(21, 'Abigail', 'Peterson', '387', datetime.date(2028, 12, 1), 21)
(22, 'Daniel', 'Gray', '7361', datetime.date(2030, 2, 1), 22)
(23, 'Emily', 'James', '8833', datetime.date(2031, 3, 1), 23)
(24, 'Henry', 'Watson', '1019', datetime.date(2030, 7, 1), 24)
(25, 'Ella', 'Bryant', '5237', datetime.date(2030, 6, 1), 25)
(26, 'Jackson', 'Russell', '6874', datetime.date(2030, 9, 1), 26)
(27, 'Avery', 'Diaz', '3559', datetime.date(2029, 3, 1), 27)
(28, 'Sebastian', 'Ortiz', '4547', datetime.date(2031, 8, 1), 28)
(29, 'Sofia', 'Sanders', '9238', datetime.date(2030, 1, 1), 29)
(30, 'Jack', 'Powell', '2401', datetime.date(2031, 2, 1), 30)
(31, 'Camila', 'Long', '5917', datetime.date(2029, 2, 1), 31)
(32, 'Owen', 'Perry', '1970', datetime.date(2028, 1, 1), 32)
(33, 'Aria', 'Hughes', '4833', datetime.date(2031, 1, 1), 33)
(34, 'Theodore', 'Flores', '480', datetime.date(2028, 6, 1), 34)
(35, 'Scarlett', 'Washington', '5189', datetime.date(2031, 4, 1), 35)
(36, 'Levi', 'Butler', '5929', datetime.date(2031, 11, 1), 36)
(37, 'Grace', 'Simmons', '2116', datetime.date(2029, 7, 1), 37)
(38, 'Mateo', 'Graham', '3446', datetime.date(2031, 3, 1), 38)
(39, 'Chloe', 'Cole', '5172', datetime.date(2030, 8, 1), 39)
(40, 'Samuel', 'Baker', '574', datetime.date(2029, 8, 1), 40)
(41, 'Victoria', 'Richardson', '267', datetime.date(2031, 10, 1), 41)
(42, 'Wyatt', 'Cox', '7049', datetime.date(2027, 8, 1), 42)
(43, 'Riley', 'Howard', '559', datetime.date(2030, 7, 1), 43)
(44, 'Julian', 'Ward', '2763', datetime.date(2028, 10, 1), 44)
(45, 'Layla', 'Torres', '1987', datetime.date(2027, 7, 1), 45)
(46, 'Asher', 'Peterson', '290', datetime.date(2031, 10, 1), 46)
(47, 'Nora', 'Ramirez', '4400', datetime.date(2029, 7, 1), 47)
(48, 'Gabriel', 'Barnes', '364', datetime.date(2028, 11, 1), 48)
(49, 'Lily', 'Ross', '1841', datetime.date(2029, 5, 1), 49)
(50, 'Carter', 'Henderson', '7812', datetime.date(2027, 9, 1), 50)
(51, 'Zoey', 'Coleman', '112', datetime.date(2028, 12, 1), 51)
(52, 'Isaac', 'Jenkins', '8007', datetime.date(2027, 12, 1), 52)
(53, 'Hannah', 'Patterson', '9327', datetime.date(2031, 7, 1), 53)
(54, 'Jayden', 'Perry', '5797', datetime.date(2031, 9, 1), 54)
(55, 'Hazel', 'Powell', '7479', datetime.date(2029, 5, 1), 55)
(56, 'Lincoln', 'Long', '1883', datetime.date(2028, 3, 1), 56)
(57, 'Ellie', 'Fisher', '8304', datetime.date(2028, 3, 1), 57)
(58, 'Anthony', 'Ellis', '3379', datetime.date(2027, 5, 1), 58)
(59, 'Aurora', 'Kim', '8326', datetime.date(2030, 6, 1), 59)
(60, 'Hudson', 'Patel', '1624', datetime.date(2028, 3, 1), 60)
(61, 'Penelope', 'Shah', '9153', datetime.date(2031, 4, 1), 61)
(62, 'Dylan', 'Mehta', '2500', datetime.date(2027, 9, 1), 62)
(63, 'Natalie', 'Desai', '873', datetime.date(2028, 5, 1), 63)
(64, 'Ezra', 'Kapoor', '1514', datetime.date(2030, 8, 1), 64)
(65, 'Brooklyn', 'Malhotra', '274', datetime.date(2028, 10, 1), 65)
(66, 'Thomas', 'Singh', '2402', datetime.date(2027, 12, 1), 66)
(67, 'Stella', 'Kaur', '4887', datetime.date(2028, 9, 1), 67)
(68, 'Charles', 'Chopra', '9332', datetime.date(2031, 11, 1), 68)
(69, 'Lucy', 'Iyer', '4403', datetime.date(2030, 12, 1), 69)
(70, 'Christopher', 'Rao', '4918', datetime.date(2031, 2, 1), 70)
(71, 'Paisley', 'Nair', '1292', datetime.date(2029, 3, 1), 71)
(72, 'Jaxon', 'Menon', '6963', datetime.date(2028, 10, 1), 72)
(73, 'Savannah', 'Gupta', '3292', datetime.date(2028, 11, 1), 73)
(74, 'Josiah', 'Verma', '6688', datetime.date(2029, 6, 1), 74)
(75, 'Claire', 'Das', '6147', datetime.date(2029, 10, 1), 75)
(76, 'Isaiah', 'Banerjee', '1901', datetime.date(2030, 5, 1), 76)
(77, 'Skylar', 'Mukherjee', '4828', datetime.date(2031, 12, 1), 77)
(78, 'Andrew', 'Reddy', '9809', datetime.date(2031, 5, 1), 78)
(79, 'Bella', 'Kulkarni', '623', datetime.date(2030, 9, 1), 79)
(80, 'Joshua', 'Joshi', '219', datetime.date(2029, 11, 1), 80)
(81, 'Anna', 'Donovan', '3139', datetime.date(2027, 5, 1), 81)
(82, 'Nathan', 'McCarthy', '51', datetime.date(2029, 5, 1), 82)
(83, 'Caroline', 'Obrien', '6901', datetime.date(2028, 2, 1), 83)
(84, 'Adrian', 'Quinn', '4446', datetime.date(2028, 5, 1), 84)
(85, 'Sarah', 'Walsh', '3297', datetime.date(2030, 2, 1), 85)
(86, 'Caleb', 'Shea', '3476', datetime.date(2027, 12, 1), 86)
(87, 'Madelyn', 'Fitzgerald', '9401', datetime.date(2027, 9, 1), 87)
(88, 'Ryan', 'Malone', '1309', datetime.date(2028, 5, 1), 88)
(89, 'Kennedy', 'Santos', '1776', datetime.date(2027, 4, 1), 89)
(90, 'Christian', 'Alvarez', '4370', datetime.date(2030, 8, 1), 90)
(91, 'Maya', 'Morales', '9074', datetime.date(2028, 1, 1), 91)
(92, 'Aaron', 'Castro', '9350', datetime.date(2030, 4, 1), 92)
(93, 'Allison', 'Nguyen', '8537', datetime.date(2031, 11, 1), 93)
(94, 'Adam', 'Tran', '4692', datetime.date(2029, 11, 1), 94)
(95, 'Naomi', 'Pham', '3943', datetime.date(2027, 1, 1), 95)
(96, 'Connor', 'Chen', '6667', datetime.date(2028, 10, 1), 96)
(97, 'Elena', 'Lin', '1806', datetime.date(2031, 2, 1), 97)
(98, 'Jonathan', 'Wong', '1243', datetime.date(2030, 2, 1), 98)
(99, 'Ruby', 'Zhang', '6292', datetime.date(2027, 12, 1), 99)
(100, 'Jeremiah', 'Liu', '2284', datetime.date(2031, 3, 1), 100)

# orders

In [59]:
orders

,order_id,order_type,order_time,order_date,order_status,customer_id,store_id
0,1,Delivery,2026-02-12 05:54:29,2026-02-12,Confirmed,2,8
1,2,Delivery,2026-02-04 13:09:54,2026-02-04,Confirmed,18,3
2,3,Delivery,2026-02-07 03:56:00,2026-02-07,Cancelled,75,9
3,4,Delivery,2026-03-05 10:27:24,2026-03-05,Confirmed,48,4
4,5,Delivery,2026-02-22 00:41:26,2026-02-22,Failed,62,6
...,...,...,...,...,...,...,...
215,216,Delivery,2026-02-13 14:51:49,2026-02-13,Cancelled,8,2
216,217,Delivery,2026-03-09 13:01:32,2026-03-09,Confirmed,72,1
217,218,Delivery,2026-03-08 10:43:19,2026-03-08,Confirmed,37,2
218,219,Pickup,2026-03-12 04:54:18,2026-03-12,Confirmed,38,9
219,220,Delivery,2026-03-01 05:53:19,2026-03-01,Confirmed,78,5

In [60]:
import datetime as dt
orders['order_time'] = pd.to_datetime(orders['order_time']).dt.time
orders.head()

,order_id,order_type,order_time,order_date,order_status,customer_id,store_id
0,1,Delivery,05:54:29,2026-02-12,Confirmed,2,8
1,2,Delivery,13:09:54,2026-02-04,Confirmed,18,3
2,3,Delivery,03:56:00,2026-02-07,Cancelled,75,9
3,4,Delivery,10:27:24,2026-03-05,Confirmed,48,4
4,5,Delivery,00:41:26,2026-02-22,Failed,62,6

In [61]:
query = "INSERT INTO customer_order(order_id, order_type, order_time, order_date, order_status, customer_id, store_id) VALUES (%s,%s,%s,%s,%s,%s,%s)"
data = list(orders.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM customer_order")
for i in cursor:
    print(i)

(1, 'Delivery', datetime.timedelta(seconds=21269), datetime.date(2026, 2, 12), 'Confirmed', 2, 8)
(2, 'Delivery', datetime.timedelta(seconds=47394), datetime.date(2026, 2, 4), 'Confirmed', 18, 3)
(3, 'Delivery', datetime.timedelta(seconds=14160), datetime.date(2026, 2, 7), 'Cancelled', 75, 9)
(4, 'Delivery', datetime.timedelta(seconds=37644), datetime.date(2026, 3, 5), 'Confirmed', 48, 4)
(5, 'Delivery', datetime.timedelta(seconds=2486), datetime.date(2026, 2, 22), 'Failed', 62, 6)
(6, 'Delivery', datetime.timedelta(seconds=171), datetime.date(2026, 3, 3), 'Failed', 52, 5)
(7, 'Pickup', datetime.timedelta(seconds=27965), datetime.date(2026, 2, 27), 'Failed', 92, 2)
(8, 'Delivery', datetime.timedelta(seconds=82983), datetime.date(2026, 2, 6), 'Confirmed', 20, 8)
(9, 'Pickup', datetime.timedelta(seconds=62212), datetime.date(2026, 2, 3), 'Confirmed', 89, 8)
(10, 'Delivery', datetime.timedelta(seconds=15635), datetime.date(2026, 2, 19), 'Confirmed', 25, 5)
(11, 'Delivery', datetime.timedelta(seconds=53644), datetime.date(2026, 3, 29), 'Confirmed', 89, 7)
(12, 'Pickup', datetime.timedelta(seconds=35841), datetime.date(2026, 3, 25), 'Confirmed', 36, 5)
(13, 'Pickup', datetime.timedelta(seconds=26376), datetime.date(2026, 2, 22), 'Confirmed', 48, 2)
(14, 'Delivery', datetime.timedelta(seconds=19190), datetime.date(2026, 2, 25), 'Confirmed', 37, 5)
(15, 'Pickup', datetime.timedelta(seconds=28930), datetime.date(2026, 2, 3), 'Confirmed', 91, 4)
(16, 'Pickup', datetime.timedelta(seconds=63128), datetime.date(2026, 3, 28), 'Confirmed', 53, 1)
(17, 'Pickup', datetime.timedelta(seconds=27819), datetime.date(2026, 2, 7), 'Confirmed', 14, 9)
(18, 'Delivery', datetime.timedelta(seconds=81339), datetime.date(2026, 3, 19), 'Confirmed', 57, 5)
(19, 'Delivery', datetime.timedelta(seconds=74018), datetime.date(2026, 2, 6), 'Confirmed', 60, 6)
(20, 'Delivery', datetime.timedelta(seconds=45935), datetime.date(2026, 2, 14), 'Confirmed', 58, 7)
(21, 'Delivery', datetime.timedelta(seconds=68778), datetime.date(2026, 2, 27), 'Confirmed', 54, 6)
(22, 'Delivery', datetime.timedelta(seconds=80118), datetime.date(2026, 2, 8), 'Confirmed', 56, 4)
(23, 'Delivery', datetime.timedelta(seconds=75480), datetime.date(2026, 3, 26), 'Confirmed', 79, 4)
(24, 'Delivery', datetime.timedelta(seconds=51638), datetime.date(2026, 2, 8), 'Confirmed', 87, 5)
(25, 'Delivery', datetime.timedelta(seconds=48019), datetime.date(2026, 2, 14), 'Confirmed', 85, 4)
(26, 'Delivery', datetime.timedelta(seconds=36782), datetime.date(2026, 3, 1), 'Confirmed', 10, 10)
(27, 'Pickup', datetime.timedelta(seconds=38644), datetime.date(2026, 2, 8), 'Confirmed', 24, 4)
(28, 'Pickup', datetime.timedelta(seconds=80293), datetime.date(2026, 3, 4), 'Cancelled', 99, 2)
(29, 'Delivery', datetime.timedelta(seconds=51584), datetime.date(2026, 2, 28), 'Confirmed', 84, 2)
(30, 'Pickup', datetime.timedelta(seconds=64707), datetime.date(2026, 3, 9), 'Confirmed', 60, 6)
(31, 'Pickup', datetime.timedelta(seconds=36531), datetime.date(2026, 2, 28), 'Confirmed', 37, 7)
(32, 'Delivery', datetime.timedelta(seconds=70467), datetime.date(2026, 2, 3), 'Confirmed', 81, 2)
(33, 'Pickup', datetime.timedelta(seconds=22085), datetime.date(2026, 3, 1), 'Cancelled', 21, 10)
(34, 'Pickup', datetime.timedelta(seconds=67590), datetime.date(2026, 2, 5), 'Confirmed', 28, 8)
(35, 'Pickup', datetime.timedelta(seconds=67280), datetime.date(2026, 2, 9), 'Cancelled', 72, 2)
(36, 'Delivery', datetime.timedelta(seconds=8895), datetime.date(2026, 2, 23), 'Confirmed', 70, 8)
(37, 'Pickup', datetime.timedelta(seconds=76569), datetime.date(2026, 2, 22), 'Confirmed', 32, 10)
(38, 'Pickup', datetime.timedelta(seconds=10392), datetime.date(2026, 3, 20), 'Confirmed', 97, 5)
(39, 'Delivery', datetime.timedelta(seconds=15064), datetime.date(2026, 2, 3), 'Confirmed', 25, 6)
(40, 'Pickup', datetime.timedelta(seconds=10563), datetime.date(2026, 3, 26), 'Confirmed', 83, 5)
(41, 'Delivery', datetime.timedelta(seconds=82805), datetime.date(2026, 3, 5), 'Confirmed', 90, 9)
(42, 'Pickup', datetime.timedelta(seconds=38631), datetime.date(2026, 3, 9), 'Confirmed', 40, 6)
(43, 'Delivery', datetime.timedelta(seconds=52046), datetime.date(2026, 2, 11), 'Confirmed', 95, 3)
(44, 'Delivery', datetime.timedelta(seconds=37940), datetime.date(2026, 3, 23), 'Confirmed', 56, 10)
(45, 'Delivery', datetime.timedelta(seconds=83046), datetime.date(2026, 2, 25), 'Cancelled', 66, 5)
(46, 'Delivery', datetime.timedelta(seconds=66431), datetime.date(2026, 3, 26), 'Failed', 72, 9)
(47, 'Delivery', datetime.timedelta(seconds=48036), datetime.date(2026, 2, 11), 'Confirmed', 65, 7)
(48, 'Delivery', datetime.timedelta(seconds=4146), datetime.date(2026, 3, 1), 'Confirmed', 90, 5)
(49, 'Delivery', datetime.timedelta(seconds=79857), datetime.date(2026, 3, 9), 'Cancelled', 44, 5)
(50, 'Delivery', datetime.timedelta(seconds=80621), datetime.date(2026, 3, 24), 'Confirmed', 65, 5)
(51, 'Delivery', datetime.timedelta(seconds=605), datetime.date(2026, 2, 12), 'Confirmed', 96, 1)
(52, 'Pickup', datetime.timedelta(seconds=7445), datetime.date(2026, 3, 8), 'Confirmed', 76, 8)
(53, 'Pickup', datetime.timedelta(seconds=58080), datetime.date(2026, 3, 17), 'Failed', 80, 5)
(54, 'Pickup', datetime.timedelta(seconds=23429), datetime.date(2026, 2, 19), 'Confirmed', 29, 7)
(55, 'Delivery', datetime.timedelta(seconds=35898), datetime.date(2026, 2, 14), 'Confirmed', 50, 8)
(56, 'Delivery', datetime.timedelta(seconds=34298), datetime.date(2026, 2, 10), 'Confirmed', 76, 3)
(57, 'Delivery', datetime.timedelta(seconds=19922), datetime.date(2026, 2, 8), 'Confirmed', 2, 6)
(58, 'Delivery', datetime.timedelta(seconds=41230), datetime.date(2026, 2, 20), 'Confirmed', 4, 9)
(59, 'Delivery', datetime.timedelta(seconds=61941), datetime.date(2026, 3, 26), 'Failed', 53, 2)
(60, 'Pickup', datetime.timedelta(seconds=14811), datetime.date(2026, 3, 14), 'Confirmed', 8, 6)
(61, 'Delivery', datetime.timedelta(seconds=6029), datetime.date(2026, 2, 12), 'Confirmed', 62, 7)
(62, 'Pickup', datetime.timedelta(seconds=23055), datetime.date(2026, 2, 3), 'Confirmed', 27, 3)
(63, 'Delivery', datetime.timedelta(seconds=28675), datetime.date(2026, 3, 7), 'Confirmed', 14, 1)
(64, 'Delivery', datetime.timedelta(seconds=66034), datetime.date(2026, 2, 12), 'Confirmed', 91, 8)
(65, 'Pickup', datetime.timedelta(seconds=12529), datetime.date(2026, 3, 9), 'Confirmed', 17, 3)
(66, 'Pickup', datetime.timedelta(seconds=47945), datetime.date(2026, 2, 3), 'Confirmed', 51, 1)
(67, 'Pickup', datetime.timedelta(seconds=4100), datetime.date(2026, 3, 15), 'Confirmed', 34, 8)
(68, 'Delivery', datetime.timedelta(seconds=81435), datetime.date(2026, 2, 18), 'Confirmed', 31, 2)
(69, 'Pickup', datetime.timedelta(seconds=23222), datetime.date(2026, 3, 16), 'Confirmed', 7, 5)
(70, 'Delivery', datetime.timedelta(seconds=26132), datetime.date(2026, 3, 19), 'Confirmed', 89, 3)
(71, 'Delivery', datetime.timedelta(seconds=71529), datetime.date(2026, 2, 2), 'Failed', 48, 8)
(72, 'Delivery', datetime.timedelta(seconds=28004), datetime.date(2026, 3, 20), 'Confirmed', 90, 9)
(73, 'Delivery', datetime.timedelta(seconds=7512), datetime.date(2026, 3, 13), 'Confirmed', 85, 3)
(74, 'Pickup', datetime.timedelta(seconds=29291), datetime.date(2026, 3, 26), 'Confirmed', 6, 10)
(75, 'Delivery', datetime.timedelta(seconds=24491), datetime.date(2026, 3, 2), 'Confirmed', 50, 6)
(76, 'Delivery', datetime.timedelta(seconds=68518), datetime.date(2026, 2, 2), 'Confirmed', 2, 10)
(77, 'Delivery', datetime.timedelta(seconds=55817), datetime.date(2026, 2, 19), 'Failed', 17, 2)
(78, 'Pickup', datetime.timedelta(seconds=26483), datetime.date(2026, 2, 13), 'Confirmed', 62, 1)
(79, 'Pickup', datetime.timedelta(seconds=3849), datetime.date(2026, 3, 19), 'Confirmed', 78, 2)
(80, 'Pickup', datetime.timedelta(seconds=36289), datetime.date(2026, 3, 12), 'Confirmed', 84, 9)
(81, 'Pickup', datetime.timedelta(seconds=47732), datetime.date(2026, 3, 14), 'Confirmed', 56, 2)
(82, 'Delivery', datetime.timedelta(seconds=12995), datetime.date(2026, 3, 1), 'Confirmed', 6, 5)
(83, 'Delivery', datetime.timedelta(seconds=31739), datetime.date(2026, 3, 27), 'Failed', 45, 7)
(84, 'Delivery', datetime.timedelta(seconds=53709), datetime.date(2026, 2, 27), 'Confirmed', 94, 2)
(85, 'Delivery', datetime.timedelta(seconds=49532), datetime.date(2026, 3, 10), 'Confirmed', 43, 10)
(86, 'Pickup', datetime.timedelta(seconds=9465), datetime.date(2026, 3, 1), 'Confirmed', 51, 8)
(87, 'Delivery', datetime.timedelta(seconds=83342), datetime.date(2026, 2, 2), 'Confirmed', 72, 1)
(88, 'Pickup', datetime.timedelta(seconds=14861), datetime.date(2026, 2, 23), 'Confirmed', 13, 7)
(89, 'Pickup', datetime.timedelta(seconds=73592), datetime.date(2026, 2, 23), 'Confirmed', 85, 6)
(90, 'Delivery', datetime.timedelta(seconds=55460), datetime.date(2026, 3, 26), 'Confirmed', 41, 8)
(91, 'Pickup', datetime.timedelta(seconds=45454), datetime.date(2026, 3, 25), 'Confirmed', 54, 8)
(92, 'Pickup', datetime.timedelta(seconds=10917), datetime.date(2026, 3, 2), 'Confirmed', 12, 8)
(93, 'Delivery', datetime.timedelta(seconds=43912), datetime.date(2026, 3, 13), 'Confirmed', 3, 3)
(94, 'Delivery', datetime.timedelta(seconds=68046), datetime.date(2026, 3, 7), 'Confirmed', 99, 6)
(95, 'Delivery', datetime.timedelta(seconds=21706), datetime.date(2026, 3, 18), 'Failed', 91, 9)
(96, 'Pickup', datetime.timedelta(seconds=17079), datetime.date(2026, 2, 17), 'Confirmed', 19, 2)
(97, 'Pickup', datetime.timedelta(seconds=20359), datetime.date(2026, 2, 23), 'Confirmed', 87, 10)
(98, 'Delivery', datetime.timedelta(seconds=60010), datetime.date(2026, 3, 28), 'Failed', 15, 6)
(99, 'Delivery', datetime.timedelta(seconds=80764), datetime.date(2026, 3, 24), 'Confirmed', 29, 6)
(100, 'Delivery', datetime.timedelta(seconds=29059), datetime.date(2026, 2, 5), 'Confirmed', 47, 2)
(101, 'Pickup', datetime.timedelta(seconds=12124), datetime.date(2026, 2, 14), 'Confirmed', 81, 9)
(102, 'Pickup', datetime.timedelta(seconds=19997), datetime.date(2026, 3, 27), 'Confirmed', 85, 10)
(103, 'Delivery', datetime.timedelta(seconds=54683), datetime.date(2026, 3, 11), 'Cancelled', 86, 4)
(104, 'Delivery', datetime.timedelta(seconds=22638), datetime.date(2026, 2, 11), 'Confirmed', 12, 3)
(105, 'Delivery', datetime.timedelta(seconds=29735), datetime.date(2026, 2, 25), 'Confirmed', 51, 5)
(106, 'Pickup', datetime.timedelta(seconds=30242), datetime.date(2026, 3, 3), 'Confirmed', 18, 8)
(107, 'Delivery', datetime.timedelta(seconds=24103), datetime.date(2026, 2, 5), 'Confirmed', 1, 9)
(108, 'Pickup', datetime.timedelta(seconds=51967), datetime.date(2026, 3, 11), 'Confirmed', 68, 7)
(109, 'Pickup', datetime.timedelta(seconds=63867), datetime.date(2026, 2, 16), 'Confirmed', 59, 2)
(110, 'Delivery', datetime.timedelta(seconds=46811), datetime.date(2026, 2, 24), 'Confirmed', 87, 1)
(111, 'Delivery', datetime.timedelta(seconds=29093), datetime.date(2026, 3, 13), 'Confirmed', 2, 10)
(112, 'Delivery', datetime.timedelta(seconds=81558), datetime.date(2026, 2, 1), 'Confirmed', 97, 9)
(113, 'Delivery', datetime.timedelta(seconds=30378), datetime.date(2026, 2, 17), 'Confirmed', 88, 3)
(114, 'Pickup', datetime.timedelta(seconds=71507), datetime.date(2026, 3, 22), 'Confirmed', 68, 10)
(115, 'Delivery', datetime.timedelta(seconds=53869), datetime.date(2026, 3, 5), 'Confirmed', 45, 3)
(116, 'Delivery', datetime.timedelta(seconds=31188), datetime.date(2026, 3, 20), 'Confirmed', 21, 9)
(117, 'Pickup', datetime.timedelta(seconds=62281), datetime.date(2026, 3, 22), 'Confirmed', 16, 8)
(118, 'Delivery', datetime.timedelta(seconds=76606), datetime.date(2026, 3, 12), 'Confirmed', 96, 2)
(119, 'Delivery', datetime.timedelta(seconds=17451), datetime.date(2026, 3, 27), 'Confirmed', 31, 8)
(120, 'Pickup', datetime.timedelta(seconds=71588), datetime.date(2026, 3, 19), 'Confirmed', 79, 9)
(121, 'Delivery', datetime.timedelta(seconds=44959), datetime.date(2026, 3, 23), 'Confirmed', 23, 10)
(122, 'Pickup', datetime.timedelta(seconds=81892), datetime.date(2026, 3, 24), 'Confirmed', 99, 10)
(123, 'Pickup', datetime.timedelta(seconds=56295), datetime.date(2026, 3, 20), 'Cancelled', 86, 8)
(124, 'Pickup', datetime.timedelta(seconds=1216), datetime.date(2026, 3, 5), 'Confirmed', 7, 6)
(125, 'Delivery', datetime.timedelta(seconds=28564), datetime.date(2026, 3, 1), 'Confirmed', 62, 6)
(126, 'Pickup', datetime.timedelta(seconds=71190), datetime.date(2026, 2, 9), 'Confirmed', 67, 10)
(127, 'Pickup', datetime.timedelta(seconds=44673), datetime.date(2026, 3, 6), 'Confirmed', 31, 8)
(128, 'Pickup', datetime.timedelta(seconds=85187), datetime.date(2026, 2, 1), 'Confirmed', 57, 5)
(129, 'Delivery', datetime.timedelta(seconds=79232), datetime.date(2026, 3, 21), 'Confirmed', 27, 6)
(130, 'Pickup', datetime.timedelta(seconds=630), datetime.date(2026, 2, 12), 'Confirmed', 30, 3)
(131, 'Delivery', datetime.timedelta(seconds=22822), datetime.date(2026, 3, 17), 'Confirmed', 63, 6)
(132, 'Delivery', datetime.timedelta(seconds=13325), datetime.date(2026, 2, 27), 'Confirmed', 42, 8)
(133, 'Delivery', datetime.timedelta(seconds=43183), datetime.date(2026, 2, 14), 'Confirmed', 77, 9)
(134, 'Delivery', datetime.timedelta(seconds=19050), datetime.date(2026, 2, 11), 'Confirmed', 1, 2)
(135, 'Delivery', datetime.timedelta(seconds=84502), datetime.date(2026, 2, 10), 'Cancelled', 22, 2)
(136, 'Pickup', datetime.timedelta(seconds=7289), datetime.date(2026, 3, 7), 'Confirmed', 85, 5)
(137, 'Delivery', datetime.timedelta(seconds=27788), datetime.date(2026, 3, 7), 'Confirmed', 69, 2)
(138, 'Delivery', datetime.timedelta(seconds=49322), datetime.date(2026, 3, 17), 'Confirmed', 80, 4)
(139, 'Pickup', datetime.timedelta(seconds=34197), datetime.date(2026, 2, 5), 'Confirmed', 77, 5)
(140, 'Pickup', datetime.timedelta(seconds=52744), datetime.date(2026, 2, 4), 'Failed', 37, 1)
(141, 'Pickup', datetime.timedelta(seconds=55768), datetime.date(2026, 2, 23), 'Failed', 1, 3)
(142, 'Delivery', datetime.timedelta(seconds=10422), datetime.date(2026, 3, 5), 'Confirmed', 98, 2)
(143, 'Delivery', datetime.timedelta(seconds=26266), datetime.date(2026, 3, 14), 'Failed', 46, 7)
(144, 'Delivery', datetime.timedelta(seconds=20065), datetime.date(2026, 3, 8), 'Failed', 72, 7)
(145, 'Delivery', datetime.timedelta(seconds=47492), datetime.date(2026, 3, 15), 'Confirmed', 47, 8)
(146, 'Delivery', datetime.timedelta(seconds=32126), datetime.date(2026, 3, 9), 'Failed', 76, 5)
(147, 'Pickup', datetime.timedelta(seconds=38661), datetime.date(2026, 2, 19), 'Confirmed', 68, 4)
(148, 'Delivery', datetime.timedelta(seconds=85801), datetime.date(2026, 3, 14), 'Cancelled', 71, 8)
(149, 'Pickup', datetime.timedelta(seconds=78294), datetime.date(2026, 3, 1), 'Confirmed', 93, 7)
(150, 'Delivery', datetime.timedelta(seconds=461), datetime.date(2026, 2, 28), 'Confirmed', 51, 5)
(151, 'Delivery', datetime.timedelta(seconds=7373), datetime.date(2026, 3, 20), 'Confirmed', 81, 9)
(152, 'Delivery', datetime.timedelta(seconds=72966), datetime.date(2026, 2, 5), 'Failed', 18, 4)
(153, 'Pickup', datetime.timedelta(seconds=67246), datetime.date(2026, 3, 7), 'Confirmed', 52, 1)
(154, 'Pickup', datetime.timedelta(seconds=82930), datetime.date(2026, 3, 1), 'Confirmed', 49, 4)
(155, 'Pickup', datetime.timedelta(seconds=28947), datetime.date(2026, 3, 4), 'Confirmed', 16, 1)
(156, 'Pickup', datetime.timedelta(seconds=8429), datetime.date(2026, 3, 20), 'Confirmed', 52, 7)
(157, 'Delivery', datetime.timedelta(seconds=45487), datetime.date(2026, 3, 1), 'Failed', 45, 4)
(158, 'Pickup', datetime.timedelta(seconds=59062), datetime.date(2026, 3, 26), 'Confirmed', 25, 2)
(159, 'Delivery', datetime.timedelta(seconds=70372), datetime.date(2026, 3, 20), 'Confirmed', 88, 9)
(160, 'Delivery', datetime.timedelta(seconds=61018), datetime.date(2026, 3, 12), 'Confirmed', 29, 6)
(161, 'Pickup', datetime.timedelta(seconds=9539), datetime.date(2026, 3, 2), 'Confirmed', 87, 2)
(162, 'Delivery', datetime.timedelta(seconds=79803), datetime.date(2026, 3, 4), 'Confirmed', 48, 8)
(163, 'Pickup', datetime.timedelta(seconds=82085), datetime.date(2026, 3, 3), 'Confirmed', 67, 5)
(164, 'Pickup', datetime.timedelta(seconds=67138), datetime.date(2026, 3, 13), 'Confirmed', 93, 7)
(165, 'Delivery', datetime.timedelta(seconds=17070), datetime.date(2026, 2, 18), 'Confirmed', 25, 8)
(166, 'Delivery', datetime.timedelta(seconds=6015), datetime.date(2026, 2, 22), 'Failed', 39, 2)
(167, 'Pickup', datetime.timedelta(seconds=39955), datetime.date(2026, 3, 28), 'Confirmed', 37, 6)
(168, 'Pickup', datetime.timedelta(seconds=1838), datetime.date(2026, 2, 10), 'Confirmed', 14, 1)
(169, 'Delivery', datetime.timedelta(seconds=33380), datetime.date(2026, 2, 1), 'Confirmed', 57, 7)
(170, 'Delivery', datetime.timedelta(seconds=74183), datetime.date(2026, 3, 1), 'Cancelled', 39, 6)
(171, 'Delivery', datetime.timedelta(seconds=79755), datetime.date(2026, 3, 19), 'Confirmed', 68, 4)
(172, 'Pickup', datetime.timedelta(seconds=24042), datetime.date(2026, 3, 14), 'Confirmed', 90, 10)
(173, 'Pickup', datetime.timedelta(seconds=66405), datetime.date(2026, 2, 8), 'Confirmed', 56, 8)
(174, 'Delivery', datetime.timedelta(seconds=50272), datetime.date(2026, 2, 18), 'Confirmed', 33, 7)
(175, 'Pickup', datetime.timedelta(seconds=54757), datetime.date(2026, 3, 9), 'Cancelled', 85, 7)
(176, 'Delivery', datetime.timedelta(seconds=423), datetime.date(2026, 3, 16), 'Confirmed', 25, 5)
(177, 'Delivery', datetime.timedelta(seconds=55159), datetime.date(2026, 3, 2), 'Confirmed', 79, 10)
(178, 'Delivery', datetime.timedelta(seconds=8211), datetime.date(2026, 3, 20), 'Confirmed', 77, 7)
(179, 'Delivery', datetime.timedelta(seconds=1300), datetime.date(2026, 3, 22), 'Confirmed', 96, 9)
(180, 'Delivery', datetime.timedelta(seconds=6318), datetime.date(2026, 3, 20), 'Confirmed', 99, 1)
(181, 'Pickup', datetime.timedelta(seconds=20640), datetime.date(2026, 3, 5), 'Confirmed', 35, 8)
(182, 'Delivery', datetime.timedelta(seconds=66231), datetime.date(2026, 3, 17), 'Confirmed', 92, 8)
(183, 'Pickup', datetime.timedelta(seconds=37637), datetime.date(2026, 3, 22), 'Confirmed', 27, 8)
(184, 'Delivery', datetime.timedelta(seconds=37424), datetime.date(2026, 2, 8), 'Confirmed', 32, 5)
(185, 'Pickup', datetime.timedelta(seconds=363), datetime.date(2026, 3, 17), 'Failed', 34, 3)
(186, 'Delivery', datetime.timedelta(seconds=77311), datetime.date(2026, 3, 9), 'Confirmed', 71, 5)
(187, 'Pickup', datetime.timedelta(seconds=24498), datetime.date(2026, 3, 19), 'Cancelled', 30, 8)
(188, 'Delivery', datetime.timedelta(seconds=10324), datetime.date(2026, 3, 17), 'Confirmed', 40, 3)
(189, 'Pickup', datetime.timedelta(seconds=51319), datetime.date(2026, 2, 12), 'Confirmed', 75, 4)
(190, 'Delivery', datetime.timedelta(seconds=13882), datetime.date(2026, 3, 16), 'Confirmed', 40, 10)
(191, 'Delivery', datetime.timedelta(seconds=15296), datetime.date(2026, 3, 6), 'Confirmed', 7, 6)
(192, 'Delivery', datetime.timedelta(seconds=37121), datetime.date(2026, 3, 27), 'Confirmed', 96, 9)
(193, 'Delivery', datetime.timedelta(seconds=65947), datetime.date(2026, 2, 8), 'Confirmed', 96, 6)
(194, 'Pickup', datetime.timedelta(seconds=8160), datetime.date(2026, 3, 27), 'Cancelled', 19, 7)
(195, 'Delivery', datetime.timedelta(seconds=22295), datetime.date(2026, 2, 23), 'Confirmed', 34, 10)
(196, 'Delivery', datetime.timedelta(seconds=58873), datetime.date(2026, 2, 5), 'Confirmed', 9, 8)
(197, 'Delivery', datetime.timedelta(seconds=14972), datetime.date(2026, 3, 22), 'Confirmed', 26, 3)
(198, 'Delivery', datetime.timedelta(seconds=84397), datetime.date(2026, 3, 4), 'Confirmed', 83, 6)
(199, 'Pickup', datetime.timedelta(seconds=16526), datetime.date(2026, 2, 8), 'Confirmed', 15, 7)
(200, 'Delivery', datetime.timedelta(seconds=69555), datetime.date(2026, 3, 4), 'Confirmed', 44, 7)
(201, 'Delivery', datetime.timedelta(seconds=55788), datetime.date(2026, 3, 12), 'Confirmed', 100, 8)
(202, 'Delivery', datetime.timedelta(seconds=13560), datetime.date(2026, 2, 22), 'Confirmed', 47, 10)

## Order Assignment

In [62]:
order_assignment

     assignment_id   assignment_status  manager_id  packer_id  order_id
0                1           confirmed          29         31         1
1                2  Ready for delivery           9         11         2
2                3           confirmed          33         36         3
3                4           delivered          13         15         4
4                5           confirmed          21         23         5
..             ...                 ...         ...        ...       ...
215            216           confirmed           5          8       216
216            217           delivered           1          2       217
217            218             packing           5          7       218
218            219             packing          33         34       219
219            220           delivered          17         19       220

[220 rows x 5 columns]

In [63]:
query = "INSERT INTO order_assignment(assignment_id, assignment_status, manager_id, packer_id, order_id) VALUES (%s,%s,%s,%s,%s)"
data = list(order_assignment.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM order_assignment")
for i in cursor:
    print(i)

(1, 'confirmed', 29, 31, 1)
(2, 'Ready for delivery', 9, 11, 2)
(3, 'confirmed', 33, 36, 3)
(4, 'delivered', 13, 15, 4)
(5, 'confirmed', 21, 23, 5)
(6, 'confirmed', 17, 20, 6)
(7, 'confirmed', 5, 6, 7)
(8, 'packing', 29, 32, 8)
(9, 'Ready for pickup', 29, 32, 9)
(10, 'packing', 17, 18, 10)
(11, 'confirmed', 25, 27, 11)
(12, 'confirmed', 17, 19, 12)
(13, 'Ready for pickup', 5, 6, 13)
(14, 'packing', 17, 19, 14)
(15, 'Ready for pickup', 13, 15, 15)
(16, 'Ready for pickup', 1, 3, 16)
(17, 'Ready for pickup', 33, 34, 17)
(18, 'packing', 17, 19, 18)
(19, 'out for delivery', 21, 24, 19)
(20, 'confirmed', 25, 28, 20)
(21, 'delivered', 21, 24, 21)
(22, 'out for delivery', 13, 16, 22)
(23, 'Ready for delivery', 13, 16, 23)
(24, 'delivered', 17, 19, 24)
(25, 'packing', 13, 16, 25)
(26, 'delivered', 37, 39, 26)
(27, 'packing', 13, 16, 27)
(28, 'confirmed', 5, 7, 28)
(29, 'packing', 5, 6, 29)
(30, 'packing', 21, 22, 30)
(31, 'confirmed', 25, 27, 31)
(32, 'out for delivery', 5, 6, 32)
(33, 'confirmed', 37, 39, 33)
(34, 'Ready for pickup', 29, 32, 34)
(35, 'confirmed', 5, 8, 35)
(36, 'packing', 29, 30, 36)
(37, 'Ready for pickup', 37, 40, 37)
(38, 'packing', 17, 20, 38)
(39, 'packing', 21, 22, 39)
(40, 'packing', 17, 20, 40)
(41, 'delivered', 33, 36, 41)
(42, 'Ready for pickup', 21, 24, 42)
(43, 'confirmed', 9, 12, 43)
(44, 'Ready for delivery', 37, 38, 44)
(45, 'confirmed', 17, 19, 45)
(46, 'confirmed', 33, 34, 46)
(47, 'delivered', 25, 27, 47)
(48, 'Ready for delivery', 17, 19, 48)
(49, 'confirmed', 17, 19, 49)
(50, 'delivered', 17, 19, 50)
(51, 'out for delivery', 1, 4, 51)
(52, 'packing', 29, 32, 52)
(53, 'confirmed', 17, 19, 53)
(54, 'packing', 25, 28, 54)
(55, 'out for delivery', 29, 30, 55)
(56, 'Ready for delivery', 9, 12, 56)
(57, 'Ready for delivery', 21, 23, 57)
(58, 'confirmed', 33, 36, 58)
(59, 'confirmed', 5, 7, 59)
(60, 'Ready for pickup', 21, 22, 60)
(61, 'Ready for delivery', 25, 28, 61)
(62, 'Ready for pickup', 9, 11, 62)
(63, 'packing', 1, 3, 63)
(64, 'Ready for delivery', 29, 31, 64)
(65, 'packing', 9, 12, 65)
(66, 'packing', 1, 2, 66)
(67, 'Ready for pickup', 29, 31, 67)
(68, 'delivered', 5, 8, 68)
(69, 'Ready for pickup', 17, 18, 69)
(70, 'packing', 9, 11, 70)
(71, 'confirmed', 29, 32, 71)
(72, 'delivered', 33, 34, 72)
(73, 'Ready for delivery', 9, 12, 73)
(74, 'confirmed', 37, 40, 74)
(75, 'packing', 21, 24, 75)
(76, 'confirmed', 37, 40, 76)
(77, 'confirmed', 5, 6, 77)
(78, 'Ready for pickup', 1, 2, 78)
(79, 'packing', 5, 8, 79)
(80, 'packing', 33, 35, 80)
(81, 'Ready for pickup', 5, 7, 81)
(82, 'confirmed', 17, 20, 82)
(83, 'confirmed', 25, 27, 83)
(84, 'Ready for delivery', 5, 8, 84)
(85, 'Ready for delivery', 37, 40, 85)
(86, 'Ready for pickup', 29, 31, 86)
(87, 'delivered', 1, 2, 87)
(88, 'Ready for pickup', 25, 27, 88)
(89, 'packing', 21, 22, 89)
(90, 'Ready for delivery', 29, 30, 90)
(91, 'packing', 29, 32, 91)
(92, 'Ready for pickup', 29, 31, 92)
(93, 'Ready for delivery', 9, 11, 93)
(94, 'out for delivery', 21, 23, 94)
(95, 'confirmed', 33, 36, 95)
(96, 'packing', 5, 8, 96)
(97, 'packing', 37, 40, 97)
(98, 'confirmed', 21, 22, 98)
(99, 'packing', 21, 22, 99)
(100, 'out for delivery', 5, 6, 100)
(101, 'Ready for pickup', 33, 35, 101)
(102, 'Ready for pickup', 37, 38, 102)
(103, 'confirmed', 13, 15, 103)
(104, 'out for delivery', 9, 11, 104)
(105, 'delivered', 17, 18, 105)
(106, 'Ready for pickup', 29, 31, 106)
(107, 'delivered', 33, 36, 107)
(108, 'Ready for pickup', 25, 28, 108)
(109, 'Ready for pickup', 5, 8, 109)
(110, 'Ready for delivery', 1, 4, 110)
(111, 'delivered', 37, 38, 111)
(112, 'out for delivery', 33, 35, 112)
(113, 'delivered', 9, 12, 113)
(114, 'packing', 37, 39, 114)
(115, 'Ready for delivery', 9, 12, 115)
(116, 'confirmed', 33, 36, 116)
(117, 'Ready for pickup', 29, 30, 117)
(118, 'confirmed', 5, 6, 118)
(119, 'delivered', 29, 32, 119)
(120, 'packing', 33, 36, 120)
(121, 'confirmed', 37, 39, 121)
(122, 'Ready for pickup', 37, 39, 122)
(123, 'confirmed', 29, 31, 123)
(124, 'confirmed', 21, 23, 124)
(125, 'packing', 21, 23, 125)
(126, 'Ready for pickup', 37, 40, 126)
(127, 'Ready for pickup', 29, 32, 127)
(128, 'packing', 17, 18, 128)
(129, 'delivered', 21, 22, 129)
(130, 'confirmed', 9, 12, 130)
(131, 'delivered', 21, 24, 131)
(132, 'packing', 29, 31, 132)
(133, 'out for delivery', 33, 35, 133)
(134, 'delivered', 5, 8, 134)
(135, 'confirmed', 5, 7, 135)
(136, 'Ready for pickup', 17, 19, 136)
(137, 'out for delivery', 5, 8, 137)
(138, 'confirmed', 13, 14, 138)
(139, 'Ready for pickup', 17, 18, 139)
(140, 'confirmed', 1, 4, 140)
(141, 'confirmed', 9, 12, 141)
(142, 'confirmed', 5, 6, 142)
(143, 'confirmed', 25, 27, 143)
(144, 'confirmed', 25, 28, 144)
(145, 'packing', 29, 30, 145)
(146, 'confirmed', 17, 19, 146)
(147, 'packing', 13, 14, 147)
(148, 'confirmed', 29, 31, 148)
(149, 'packing', 25, 27, 149)
(150, 'confirmed', 17, 19, 150)
(151, 'Ready for delivery', 33, 34, 151)
(152, 'confirmed', 13, 15, 152)
(153, 'confirmed', 1, 2, 153)
(154, 'Ready for pickup', 13, 16, 154)
(155, 'Ready for pickup', 1, 4, 155)
(156, 'Ready for pickup', 25, 28, 156)
(157, 'confirmed', 13, 15, 157)
(158, 'Ready for pickup', 5, 6, 158)
(159, 'Ready for delivery', 33, 36, 159)
(160, 'Ready for delivery', 21, 22, 160)
(161, 'Ready for pickup', 5, 8, 161)
(162, 'out for delivery', 29, 32, 162)
(163, 'Ready for pickup', 17, 18, 163)
(164, 'Ready for pickup', 25, 28, 164)
(165, 'out for delivery', 29, 32, 165)
(166, 'confirmed', 5, 7, 166)
(167, 'packing', 21, 24, 167)
(168, 'Ready for pickup', 1, 3, 168)
(169, 'Ready for delivery', 25, 26, 169)
(170, 'confirmed', 21, 23, 170)
(171, 'confirmed', 13, 15, 171)
(172, 'confirmed', 37, 39, 172)
(173, 'confirmed', 29, 32, 173)
(174, 'packing', 25, 26, 174)
(175, 'confirmed', 25, 28, 175)
(176, 'out for delivery', 17, 20, 176)
(177, 'delivered', 37, 40, 177)
(178, 'delivered', 25, 27, 178)
(179, 'delivered', 33, 36, 179)
(180, 'Ready for delivery', 1, 2, 180)
(181, 'confirmed', 29, 31, 181)
(182, 'delivered', 29, 30, 182)
(183, 'Ready for pickup', 29, 31, 183)
(184, 'Ready for delivery', 17, 20, 184)
(185, 'confirmed', 9, 11, 185)
(186, 'Ready for delivery', 17, 18, 186)
(187, 'confirmed', 29, 31, 187)
(188, 'out for delivery', 9, 12, 188)
(189, 'packing', 13, 14, 189)
(190, 'delivered', 37, 38, 190)
(191, 'packing', 21, 22, 191)
(192, 'Ready for delivery', 33, 36, 192)
(193, 'out for delivery', 21, 24, 193)
(194, 'confirmed', 25, 27, 194)
(195, 'out for delivery', 37, 39, 195)
(196, 'packing', 29, 32, 196)
(197, 'packing', 9, 11, 197)
(198, 'Ready for delivery', 21, 24, 198)
(199, 'confirmed', 25, 28, 199)
(200, 'packing', 25, 27, 200)
(201, 'packing', 29, 30, 201)
(202, 'Ready for delivery', 37, 38, 202)
(203, 'confirmed', 33, 34, 203)
(204, 'confirmed', 21, 22, 204)
(205, 'out for delivery', 37, 38, 205)
(206, 'delivered', 21, 24, 206)
(207, 'Ready for pickup', 9, 12, 207)
(208, 'packing', 29, 31, 208)
(209, 'confirmed', 33, 36, 209)
(210, 'Ready for delivery', 29, 32, 210)
(211, 'Ready for delivery', 17, 18, 211)
(212, 'packing', 37, 40, 212)
(213, 'confirmed', 5, 6, 213)
(214, 'confirmed', 21, 22, 214)
(215, 'Ready for pickup', 33, 36, 215)
(216, 'confirmed', 5, 8, 216)
(217, 'delivered', 1, 2, 217)
(218, 'packing', 5, 7, 218)
(219, 'packing', 33, 34, 219)
(220, 'delivered', 17, 19, 220)

## order items

In [64]:
order_items

     quantity  price_at_purchase  order_id  product_id
0           1               1.07         1          36
1           1               4.18         2         188
2           4               0.90         2         115
3           2               6.57         2         135
4           3               4.95         2         106
..        ...                ...       ...         ...
740         2               7.87       220         212
741         4               7.07       220         190
742         2              10.04       220         149
743         3              12.83       220         176
744         3               3.74       220          15

[745 rows x 4 columns]

In [65]:
query = "INSERT INTO order_items(quantity, price_at_purchase, order_id, product_id) VALUES (%s,%s,%s,%s)"
data = list(order_items.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM order_items")
for i in cursor:
    print(i)

(1, Decimal('1.07'), 1, 36)
(2, Decimal('6.34'), 2, 53)
(3, Decimal('4.95'), 2, 106)
(4, Decimal('0.90'), 2, 115)
(2, Decimal('6.57'), 2, 135)
(1, Decimal('4.18'), 2, 188)
(4, Decimal('2.89'), 3, 35)
(2, Decimal('5.94'), 3, 38)
(4, Decimal('6.67'), 3, 53)
(3, Decimal('6.95'), 4, 68)
(2, Decimal('3.49'), 5, 46)
(3, Decimal('7.19'), 5, 144)
(3, Decimal('2.22'), 5, 230)
(2, Decimal('3.79'), 6, 30)
(4, Decimal('8.56'), 6, 117)
(2, Decimal('7.64'), 7, 50)
(1, Decimal('16.81'), 8, 96)
(4, Decimal('10.31'), 8, 157)
(4, Decimal('6.70'), 8, 221)
(1, Decimal('4.82'), 9, 3)
(1, Decimal('2.18'), 9, 25)
(4, Decimal('6.78'), 9, 61)
(4, Decimal('5.51'), 9, 90)
(3, Decimal('9.68'), 10, 103)
(3, Decimal('4.80'), 10, 129)
(2, Decimal('6.71'), 10, 135)
(4, Decimal('8.42'), 10, 182)
(4, Decimal('6.46'), 10, 221)
(4, Decimal('7.31'), 11, 31)
(3, Decimal('2.15'), 11, 37)
(2, Decimal('7.42'), 11, 54)
(1, Decimal('3.70'), 11, 63)
(3, Decimal('13.05'), 11, 109)
(2, Decimal('4.41'), 11, 188)
(3, Decimal('5.25'), 12, 9)
(4, Decimal('7.02'), 12, 54)
(2, Decimal('9.30'), 12, 103)
(1, Decimal('3.44'), 13, 116)
(4, Decimal('8.24'), 13, 123)
(4, Decimal('8.02'), 13, 128)
(3, Decimal('3.08'), 13, 178)
(4, Decimal('5.70'), 13, 228)
(2, Decimal('3.21'), 14, 62)
(3, Decimal('9.30'), 14, 155)
(4, Decimal('7.24'), 15, 121)
(2, Decimal('6.22'), 15, 133)
(3, Decimal('13.21'), 15, 173)
(4, Decimal('10.52'), 16, 218)
(4, Decimal('7.32'), 17, 13)
(3, Decimal('2.20'), 17, 37)
(1, Decimal('4.74'), 17, 80)
(4, Decimal('10.47'), 17, 197)
(3, Decimal('10.00'), 18, 231)
(4, Decimal('6.33'), 19, 52)
(1, Decimal('17.22'), 19, 100)
(4, Decimal('10.54'), 19, 159)
(4, Decimal('2.93'), 20, 62)
(3, Decimal('7.93'), 20, 82)
(2, Decimal('6.73'), 20, 110)
(3, Decimal('6.39'), 20, 133)
(3, Decimal('2.08'), 20, 143)
(4, Decimal('5.29'), 20, 233)
(2, Decimal('3.01'), 21, 18)
(1, Decimal('4.40'), 21, 48)
(2, Decimal('16.03'), 21, 88)
(3, Decimal('4.09'), 21, 167)
(3, Decimal('1.69'), 22, 37)
(3, Decimal('16.00'), 22, 91)
(3, Decimal('8.45'), 22, 123)
(1, Decimal('6.52'), 22, 125)
(4, Decimal('3.29'), 22, 223)
(4, Decimal('1.08'), 23, 36)
(3, Decimal('7.32'), 23, 68)
(2, Decimal('1.92'), 24, 37)
(2, Decimal('5.03'), 24, 122)
(2, Decimal('2.32'), 24, 137)
(4, Decimal('6.32'), 24, 184)
(3, Decimal('3.15'), 24, 185)
(4, Decimal('8.57'), 24, 210)
(3, Decimal('2.20'), 25, 25)
(4, Decimal('8.63'), 25, 182)
(1, Decimal('1.58'), 26, 208)
(1, Decimal('4.87'), 27, 14)
(2, Decimal('0.91'), 27, 26)
(2, Decimal('7.51'), 27, 77)
(2, Decimal('9.61'), 27, 103)
(3, Decimal('8.87'), 27, 211)
(2, Decimal('14.72'), 28, 92)
(4, Decimal('7.26'), 28, 121)
(1, Decimal('8.47'), 28, 134)
(1, Decimal('2.17'), 28, 199)
(2, Decimal('2.50'), 28, 237)
(2, Decimal('6.64'), 29, 42)
(3, Decimal('2.77'), 29, 74)
(4, Decimal('8.78'), 29, 117)
(4, Decimal('4.62'), 30, 5)
(4, Decimal('7.43'), 30, 11)
(1, Decimal('11.43'), 30, 119)
(1, Decimal('2.54'), 30, 137)
(3, Decimal('2.74'), 30, 187)
(3, Decimal('4.57'), 31, 48)
(2, Decimal('4.13'), 31, 63)
(3, Decimal('8.71'), 31, 101)
(4, Decimal('9.38'), 31, 155)
(4, Decimal('2.07'), 32, 25)
(2, Decimal('0.79'), 32, 115)
(4, Decimal('2.30'), 32, 143)
(1, Decimal('13.41'), 32, 172)
(3, Decimal('6.92'), 33, 40)
(2, Decimal('4.92'), 34, 14)
(4, Decimal('5.79'), 34, 27)
(1, Decimal('8.22'), 34, 182)
(3, Decimal('6.72'), 35, 97)
(3, Decimal('8.91'), 35, 200)
(1, Decimal('11.54'), 35, 213)
(3, Decimal('9.11'), 36, 134)
(1, Decimal('8.53'), 36, 145)
(4, Decimal('2.22'), 37, 146)
(1, Decimal('9.52'), 37, 147)
(2, Decimal('16.10'), 38, 91)
(2, Decimal('0.79'), 38, 102)
(2, Decimal('8.45'), 38, 130)
(1, Decimal('5.74'), 38, 141)
(1, Decimal('8.77'), 38, 155)
(1, Decimal('2.92'), 38, 236)
(4, Decimal('2.70'), 39, 74)
(3, Decimal('15.63'), 39, 98)
(3, Decimal('0.79'), 39, 102)
(1, Decimal('11.82'), 40, 119)
(1, Decimal('7.32'), 40, 144)
(2, Decimal('13.26'), 41, 112)
(1, Decimal('8.36'), 41, 130)
(3, Decimal('9.81'), 41, 149)
(4, Decimal('3.71'), 42, 1)
(1, Decimal('5.44'), 42, 9)
(4, Decimal('6.11'), 42, 161)
(3, Decimal('5.50'), 42, 180)
(1, Decimal('2.82'), 43, 59)
(2, Decimal('3.96'), 44, 44)
(1, Decimal('2.22'), 44, 137)
(3, Decimal('15.46'), 44, 175)
(2, Decimal('0.94'), 45, 26)
(3, Decimal('16.06'), 45, 84)
(3, Decimal('3.50'), 45, 148)
(4, Decimal('2.82'), 45, 187)
(3, Decimal('1.19'), 45, 209)
(2, Decimal('3.41'), 45, 223)
(3, Decimal('6.42'), 46, 20)
(4, Decimal('6.91'), 46, 52)
(4, Decimal('11.81'), 46, 119)
(4, Decimal('7.80'), 47, 174)
(3, Decimal('2.07'), 47, 199)
(2, Decimal('4.17'), 48, 63)
(1, Decimal('11.54'), 48, 169)
(2, Decimal('3.05'), 49, 35)
(4, Decimal('17.40'), 49, 83)
(3, Decimal('16.16'), 49, 91)
(3, Decimal('2.41'), 49, 137)
(2, Decimal('3.07'), 50, 18)
(4, Decimal('3.71'), 50, 154)
(4, Decimal('12.64'), 51, 112)
(4, Decimal('4.07'), 51, 224)
(1, Decimal('5.47'), 51, 238)
(1, Decimal('6.71'), 52, 34)
(1, Decimal('3.24'), 52, 35)
(1, Decimal('3.98'), 52, 76)
(4, Decimal('7.82'), 52, 153)
(2, Decimal('8.89'), 52, 196)
(1, Decimal('7.77'), 52, 239)
(4, Decimal('5.20'), 53, 3)
(3, Decimal('11.84'), 53, 105)
(3, Decimal('13.03'), 53, 176)
(4, Decimal('2.74'), 54, 12)
(2, Decimal('0.79'), 54, 26)
(4, Decimal('2.05'), 55, 6)
(1, Decimal('2.72'), 55, 66)
(4, Decimal('1.54'), 55, 132)
(3, Decimal('6.06'), 55, 133)
(1, Decimal('4.38'), 55, 188)
(4, Decimal('3.48'), 56, 45)
(1, Decimal('9.01'), 56, 139)
(1, Decimal('8.19'), 56, 210)
(2, Decimal('6.36'), 56, 221)
(2, Decimal('2.44'), 56, 234)
(4, Decimal('1.90'), 57, 237)
(1, Decimal('1.39'), 58, 36)
(3, Decimal('1.27'), 58, 115)
(3, Decimal('5.46'), 58, 129)
(3, Decimal('13.29'), 58, 173)
(1, Decimal('2.68'), 58, 187)
(3, Decimal('4.51'), 59, 48)
(3, Decimal('6.13'), 60, 2)
(4, Decimal('2.81'), 60, 70)
(1, Decimal('9.62'), 60, 147)
(1, Decimal('5.66'), 61, 32)
(4, Decimal('7.08'), 61, 54)
(4, Decimal('2.91'), 61, 60)
(2, Decimal('4.85'), 61, 142)
(4, Decimal('3.72'), 61, 148)
(3, Decimal('4.61'), 61, 167)
(1, Decimal('4.60'), 62, 5)
(1, Decimal('16.85'), 62, 83)
(2, Decimal('16.06'), 62, 91)
(3, Decimal('2.33'), 62, 168)
(4, Decimal('5.96'), 62, 228)
(2, Decimal('5.55'), 63, 51)
(2, Decimal('12.45'), 64, 105)
(3, Decimal('9.18'), 65, 103)
(4, Decimal('1.84'), 65, 199)
(4, Decimal('10.39'), 65, 231)
(2, Decimal('3.16'), 66, 35)
(3, Decimal('2.47'), 66, 66)
(1, Decimal('5.85'), 66, 124)
(1, Decimal('4.86'), 66, 189)
(1, Decimal('8.46'), 67, 134)
(4, Decimal('4.19'), 68, 43)
(2, Decimal('12.49'), 68, 205)
(1, Decimal('2.29'), 69, 37)
(4, Decimal('6.93'), 69, 52)
(1, Decimal('7.13'), 69, 77)
(2, Decimal('8.15'), 69, 130)
(2, Decimal('6.79'), 69, 226)
(1, Decimal('4.84'), 70, 51)
(3, Decimal('2.41'), 70, 199)
(1, Decimal('4.31'), 71, 19)
(2, Decimal('3.75'), 71, 30)
(4, Decimal('3.34'), 71, 35)
(1, Decimal('3.96'), 71, 57)
(3, Decimal('5.32'), 71, 165)
(4, Decimal('15.69'), 72, 84)
(4, Decimal('5.05'), 72, 152)
(4, Decimal('12.47'), 72, 176)
(1, Decimal('5.06'), 73, 108)
(3, Decimal('10.75'), 73, 202)
(4, Decimal('7.68'), 74, 72)
(1, Decimal('5.51'), 74, 122)
(1, Decimal('4.24'), 75, 48)
(3, Decimal('4.10'), 75, 57)
(3, Decimal('9.53'), 75, 103)
(2, Decimal('2.40'), 75, 137)
(1, Decimal('3.35'), 75, 148)
(3, Decimal('15.36'), 75, 175)
(4, Decimal('7.49'), 76, 121)
(1, Decimal('13.16'), 76, 172)
(1, Decimal('12.78'), 76, 176)
(4, Decimal('6.65'), 76, 184)
(2, Decimal('4.59'), 77, 188)
(3, Decimal('5.46'), 78, 180)
(2, Decimal('3.09'), 79, 45)
(1, Decimal('2.49'), 79, 70)
(3, Decimal('1.89'), 79, 71)
(2, Decimal('3.76'), 80, 1)
(2, Decimal('4.30'), 80, 170)
(4, Decimal('11.55'), 81, 119)
(3, Decimal('2.28'), 81, 203)
(3, Decimal('7.83'), 81, 239)
(2, Decimal('2.43'), 82, 23)
(4, Decimal('2.59'), 82, 59)
(2, Decimal('6.74'), 82, 97)
(4, Decimal('6.78'), 82, 110)
(2, Decimal('15.46'), 82, 171)
(3, Decimal('5.32'), 83, 32)
(2, Decimal('1.82'), 83, 37)
(3, Decimal('5.61'), 83, 122)
(3, Decimal('9.24'), 83, 147)
(4, Decimal('3.07'), 83, 223)
(2, Decimal('2.19'), 84, 16)
(3, Decimal('3.31'), 84, 30)
(2, Decimal('5.22'), 84, 160)
(4, Decimal('2.10'), 84, 237)
(1, Decimal('8.01'), 85, 118)
(3, Decimal('2.81'), 86, 12)
(2, Decimal('3.78'), 86, 116)
(3, Decimal('9.37'), 86, 211)
(1, Decimal('8.32'), 87, 10)
(2, Decimal('3.52'), 87, 18)
(2, Decimal('4.81'), 87, 58)
(2, Decimal('3.78'), 87, 163)
(1, Decimal('4.11'), 87, 224)
(2, Decimal('10.02'), 88, 85)
(4, Decimal('5.72'), 88, 90)
(4, Decimal('5.03'), 88, 152)
(3, Decimal('4.06'), 89, 57)
(3, Decimal('12.17'), 89, 119)
(2, Decimal('8.12'), 89, 145)
(4, Decimal('5.04'), 90, 3)
(3, Decimal('7.47'), 90, 118)
(2, Decimal('1.86'), 90, 131)
(4, Decimal('11.04'), 90, 151)
(2, Decimal('3.62'), 90, 224)
(1, Decimal('3.84'), 91, 1)
(1, Decimal('7.05'), 91, 40)
(2, Decimal('12.55'), 91, 111)
(1, Decimal('7.82'), 91, 153)
(1, Decimal('3.95'), 91, 198)
(2, Decimal('4.01'), 92, 67)
(4, Decimal('5.78'), 92, 99)
(3, Decimal('5.13'), 92, 126)
(1, Decimal('5.72'), 92, 160)
(2, Decimal('3.87'), 92, 183)
(4, Decimal('1.82'), 93, 4)
(2, Decimal('7.15'), 93, 13)
(4, Decimal('3.59'), 93, 30)
(2, Decimal('7.00'), 93, 125)
(3, Decimal('8.64'), 93, 139)
(2, Decimal('3.12'), 93, 148)
(2, Decimal('8.33'), 94, 86)
(3, Decimal('2.07'), 94, 131)
(2, Decimal('8.96'), 94, 139)
(3, Decimal('5.75'), 94, 233)
(1, Decimal('7.50'), 95, 128)
(3, Decimal('3.98'), 96, 1)
(1, Decimal('1.88'), 96, 6)
(4, Decimal('3.60'), 96, 18)
(3, Decimal('4.37'), 96, 63)
(3, Decimal('12.40'), 96, 89)
(2, Decimal('8.38'), 96, 212)
(2, Decimal('8.27'), 97, 86)
(3, Decimal('0.94'), 97, 102)
(1, Decimal('8.65'), 97, 127)
(2, Decimal('3.84'), 97, 138)
(1, Decimal('1.12'), 98, 102)
(1, Decimal('4.63'), 98, 108)
(2, Decimal('7.55'), 98, 153)
(3, Decimal('7.23'), 98, 204)
(1, Decimal('6.97'), 99, 52)
(3, Decimal('2.55'), 99, 70)
(1, Decimal('8.93'), 99, 127)
(3, Decimal('4.81'), 99, 129)
(2, Decimal('2.54'), 99, 143)
(4, Decimal('3.37'), 99, 154)
(1, Decimal('2.08'), 100, 16)
(1, Decimal('4.73'), 100, 49)
(2, Decimal('7.39'), 100, 68)
(4, Decimal('7.09'), 101, 61)
(3, Decimal('5.34'), 101, 90)
(2, Decimal('4.31'), 101, 138)
(1, Decimal('8.80'), 101, 196)
(2, Decimal('4.86'), 102, 21)
(2, Decimal('3.24'), 102, 30)
(3, Decimal('1.10'), 102, 115)
(4, Decimal('7.88'), 102, 214)
(4, Decimal('6.72'), 103, 56)
(2, Decimal('0.79'), 104, 26)
(4, Decimal('10.91'), 104, 213)
(4, Decimal('4.89'), 105, 14)
(3, Decimal('8.81'), 105, 101)
(4, Decimal('12.90'), 105, 206)
(3, Decimal('2.49'), 105, 222)
(4, Decimal('2.29'), 105, 229)
(1, Decimal('4.76'), 106, 19)
(4, Decimal('6.69'), 106, 78)
(3, Decimal('5.51'), 106, 238)
(4, Decimal('6.98'), 107, 40)
(3, Decimal('12.35'), 107, 105)
(3, Decimal('8.66'), 107, 155)
(3, Decimal('6.46'), 108, 78)
(3, Decimal('4.37'), 108, 107)
(4, Decimal('9.00'), 108, 240)
(3, Decimal('2.75'), 109, 39)
(2, Decimal('7.51'), 109, 69)
(3, Decimal('7.19'), 109, 77)
(1, Decimal('8.46'), 109, 127)
(1, Decimal('2.30'), 109, 230)
(3, Decimal('3.53'), 110, 46)
(2, Decimal('4.27'), 111, 224)
(3, Decimal('7.31'), 112, 31)
(2, Decimal('3.66'), 112, 154)
(1, Decimal('2.72'), 113, 8)
(2, Decimal('3.59'), 113, 35)
(3, Decimal('7.29'), 113, 153)
(4, Decimal('4.19'), 114, 138)
(4, Decimal('6.98'), 114, 195)
(1, Decimal('7.02'), 115, 52)
(3, Decimal('1.05'), 115, 102)
(2, Decimal('1.98'), 115, 131)
(2, Decimal('5.02'), 115, 216)
(1, Decimal('1.71'), 115, 229)
(3, Decimal('2.10'), 116, 6)
(2, Decimal('3.04'), 116, 35)
(3, Decimal('7.68'), 116, 72)
(1, Decimal('13.24'), 116, 109)
(4, Decimal('3.41'), 116, 235)
(1, Decimal('4.55'), 117, 49)
(3, Decimal('8.53'), 117, 117)
(4, Decimal('6.00'), 117, 161)
(4, Decimal('7.91'), 118, 219)
(4, Decimal('5.23'), 119, 142)
(4, Decimal('6.07'), 120, 133)
(4, Decimal('11.00'), 120, 158)
(1, Decimal('6.59'), 120, 221)
(4, Decimal('2.83'), 121, 12)
(3, Decimal('3.45'), 121, 73)
(3, Decimal('7.46'), 121, 153)
(3, Decimal('4.00'), 121, 167)
(4, Decimal('3.39'), 122, 30)
(4, Decimal('3.24'), 122, 150)
(1, Decimal('3.40'), 123, 15)
(3, Decimal('17.19'), 123, 83)
(3, Decimal('12.75'), 123, 111)
(3, Decimal('2.12'), 123, 131)
(2, Decimal('7.03'), 123, 144)
(2, Decimal('2.77'), 123, 185)
(4, Decimal('5.39'), 124, 14)
(2, Decimal('2.21'), 124, 23)
(3, Decimal('5.67'), 124, 161)
(1, Decimal('5.58'), 124, 228)
(1, Decimal('7.78'), 125, 72)
(3, Decimal('7.99'), 125, 145)
(1, Decimal('11.09'), 125, 151)
(1, Decimal('6.97'), 125, 190)
(3, Decimal('7.10'), 125, 204)
(3, Decimal('3.02'), 125, 235)
(4, Decimal('7.89'), 126, 128)
(2, Decimal('1.50'), 126, 131)
(4, Decimal('3.47'), 126, 150)
(3, Decimal('12.89'), 126, 172)
(2, Decimal('15.87'), 126, 175)
(3, Decimal('5.27'), 127, 3)
(3, Decimal('6.68'), 127, 61)
(2, Decimal('4.13'), 128, 183)
(4, Decimal('2.42'), 129, 64)
(3, Decimal('8.14'), 129, 86)
(3, Decimal('4.99'), 129, 126)
(2, Decimal('4.65'), 129, 232)
(2, Decimal('4.34'), 130, 63)
(3, Decimal('7.39'), 130, 87)
(2, Decimal('8.57'), 130, 196)
(2, Decimal('6.68'), 131, 20)
(1, Decimal('5.95'), 131, 27)
(4, Decimal('7.46'), 131, 50)
(4, Decimal('4.59'), 131, 108)
(1, Decimal('10.45'), 131, 197)
(2, Decimal('2.61'), 132, 64)
(2, Decimal('6.58'), 132, 190)
(2, Decimal('9.08'), 132, 196)
(4, Decimal('3.56'), 133, 57)
(1, Decimal('4.61'), 133, 108)
(1, Decimal('6.83'), 133, 144)
(2, Decimal('1.98'), 133, 146)
(3, Decimal('3.65'), 133, 163)
(4, Decimal('15.59'), 133, 175)
(1, Decimal('6.74'), 134, 78)
(3, Decimal('15.78'), 134, 91)
(4, Decimal('8.46'), 134, 123)
(3, Decimal('2.27'), 135, 12)
(4, Decimal('4.59'), 135, 58)
(2, Decimal('5.87'), 135, 161)
(2, Decimal('4.96'), 135, 216)
(2, Decimal('2.49'), 135, 230)
(4, Decimal('11.07'), 136, 186)
(1, Decimal('2.25'), 137, 12)
(1, Decimal('4.01'), 137, 163)
(2, Decimal('4.84'), 137, 216)
(3, Decimal('6.26'), 138, 79)
(1, Decimal('12.02'), 138, 119)
(4, Decimal('10.43'), 138, 159)
(3, Decimal('12.88'), 138, 176)
(3, Decimal('11.02'), 138, 213)
(1, Decimal('8.50'), 139, 123)
(1, Decimal('2.56'), 139, 187)
(4, Decimal('2.04'), 139, 199)
(1, Decimal('8.40'), 140, 117)
(4, Decimal('8.07'), 140, 130)
(2, Decimal('3.79'), 141, 198)
(1, Decimal('4.69'), 142, 49)
(3, Decimal('3.29'), 142, 73)
(2, Decimal('7.69'), 142, 128)
(2, Decimal('7.54'), 142, 191)
(1, Decimal('2.45'), 142, 199)
(4, Decimal('5.24'), 143, 47)
(3, Decimal('3.79'), 143, 67)
(3, Decimal('4.16'), 143, 224)
(3, Decimal('9.31'), 144, 155)
(4, Decimal('6.77'), 145, 190)
(4, Decimal('3.94'), 146, 48)
(4, Decimal('6.68'), 146, 97)
(4, Decimal('4.96'), 146, 152)
(2, Decimal('11.31'), 146, 158)
(4, Decimal('8.05'), 146, 212)
(3, Decimal('7.16'), 146, 226)
(4, Decimal('4.73'), 147, 106)
(4, Decimal('8.20'), 148, 127)
(2, Decimal('5.29'), 149, 3)
(3, Decimal('3.20'), 149, 30)
(1, Decimal('6.81'), 149, 61)
(2, Decimal('5.53'), 149, 126)
(3, Decimal('12.88'), 149, 176)
(4, Decimal('2.03'), 149, 237)
(4, Decimal('3.82'), 150, 1)
(4, Decimal('5.10'), 150, 9)
(3, Decimal('3.81'), 150, 116)
(4, Decimal('2.55'), 150, 225)
(2, Decimal('3.39'), 151, 15)
(3, Decimal('4.84'), 151, 55)
(3, Decimal('8.78'), 151, 200)
(3, Decimal('13.52'), 151, 201)
(1, Decimal('5.50'), 151, 233)
(4, Decimal('2.37'), 151, 237)
(4, Decimal('16.26'), 152, 84)
(3, Decimal('3.89'), 152, 167)
(3, Decimal('8.68'), 153, 120)
(1, Decimal('10.65'), 153, 207)
(2, Decimal('2.54'), 154, 8)
(1, Decimal('1.32'), 154, 26)
(3, Decimal('1.90'), 154, 71)
(1, Decimal('7.58'), 154, 82)
(3, Decimal('5.83'), 154, 233)
(3, Decimal('1.55'), 155, 6)
(4, Decimal('4.46'), 155, 19)
(1, Decimal('3.26'), 155, 148)
(3, Decimal('10.06'), 155, 149)
(2, Decimal('2.55'), 156, 203)
(4, Decimal('1.89'), 157, 71)
(4, Decimal('17.03'), 157, 83)
(1, Decimal('4.28'), 157, 170)
(1, Decimal('5.52'), 157, 238)
(3, Decimal('8.07'), 158, 50)
(1, Decimal('7.44'), 158, 177)
(4, Decimal('10.65'), 158, 202)
(4, Decimal('7.53'), 159, 72)
(1, Decimal('8.23'), 159, 86)
(1, Decimal('3.85'), 159, 198)
(1, Decimal('4.96'), 160, 51)
(2, Decimal('3.68'), 160, 63)
(2, Decimal('14.50'), 160, 92)
(1, Decimal('5.16'), 160, 122)
(2, Decimal('2.42'), 160, 187)
(4, Decimal('4.84'), 161, 33)
(2, Decimal('7.72'), 162, 11)
(3, Decimal('5.89'), 162, 124)
(2, Decimal('11.35'), 162, 158)
(3, Decimal('13.67'), 162, 173)
(1, Decimal('5.79'), 162, 180)
(2, Decimal('6.96'), 162, 190)
(3, Decimal('3.88'), 163, 63)
(2, Decimal('6.50'), 163, 97)
(1, Decimal('8.24'), 163, 212)
(2, Decimal('12.78'), 164, 109)
(1, Decimal('3.65'), 164, 150)
(2, Decimal('10.77'), 164, 151)
(2, Decimal('15.38'), 164, 171)
(1, Decimal('5.03'), 164, 216)
(1, Decimal('4.01'), 165, 1)
(2, Decimal('10.00'), 165, 85)
(1, Decimal('9.74'), 165, 103)
(2, Decimal('11.11'), 165, 207)
(1, Decimal('7.13'), 166, 31)
(3, Decimal('5.35'), 166, 90)
(1, Decimal('9.86'), 166, 103)
(4, Decimal('8.59'), 166, 130)
(2, Decimal('5.29'), 166, 152)
(3, Decimal('11.72'), 166, 217)
(1, Decimal('5.37'), 167, 51)
(1, Decimal('3.48'), 167, 57)
(3, Decimal('9.59'), 167, 103)
(4, Decimal('9.06'), 167, 139)
(4, Decimal('3.90'), 167, 170)
(2, Decimal('2.10'), 167, 179)
(2, Decimal('7.72'), 168, 72)
(4, Decimal('16.76'), 168, 83)
(1, Decimal('16.61'), 168, 96)
(1, Decimal('9.16'), 168, 240)
(1, Decimal('4.26'), 169, 5)
(4, Decimal('3.86'), 169, 15)
(2, Decimal('2.48'), 169, 64)
(2, Decimal('12.97'), 169, 111)
(4, Decimal('8.81'), 169, 196)
(2, Decimal('2.18'), 170, 64)
(1, Decimal('6.14'), 170, 99)
(2, Decimal('2.06'), 170, 131)
(3, Decimal('5.72'), 170, 141)
(2, Decimal('7.10'), 171, 61)
(4, Decimal('6.21'), 171, 99)
(3, Decimal('3.75'), 171, 148)
(3, Decimal('5.75'), 171, 161)
(2, Decimal('3.79'), 171, 170)
(2, Decimal('9.43'), 171, 181)
(4, Decimal('7.00'), 172, 42)
(2, Decimal('2.53'), 172, 64)
(2, Decimal('2.42'), 172, 137)
(2, Decimal('2.02'), 172, 179)
(4, Decimal('4.28'), 172, 188)
(2, Decimal('1.46'), 173, 4)
(3, Decimal('7.36'), 173, 11)
(1, Decimal('7.98'), 173, 210)
(2, Decimal('7.03'), 174, 61)
(1, Decimal('8.05'), 174, 86)
(4, Decimal('9.29'), 174, 162)
(1, Decimal('13.40'), 174, 172)
(1, Decimal('3.18'), 174, 178)
(1, Decimal('9.34'), 175, 147)
(3, Decimal('15.69'), 175, 175)
(4, Decimal('11.65'), 175, 186)
(2, Decimal('1.39'), 175, 208)
(1, Decimal('3.88'), 175, 224)
(1, Decimal('8.81'), 176, 123)
(1, Decimal('3.38'), 177, 154)
(1, Decimal('12.87'), 178, 112)
(2, Decimal('2.38'), 179, 12)
(4, Decimal('3.76'), 179, 57)
(3, Decimal('6.70'), 179, 144)
(1, Decimal('6.36'), 180, 22)
(2, Decimal('7.44'), 180, 77)
(2, Decimal('12.27'), 180, 105)
(3, Decimal('9.37'), 180, 181)
(3, Decimal('7.06'), 180, 190)
(3, Decimal('2.31'), 180, 234)
(4, Decimal('5.71'), 181, 166)
(1, Decimal('13.64'), 181, 173)
(4, Decimal('5.43'), 182, 41)
(3, Decimal('11.75'), 182, 119)
(4, Decimal('9.11'), 182, 147)
(2, Decimal('9.66'), 182, 181)
(3, Decimal('4.14'), 182, 192)
(3, Decimal('5.03'), 182, 232)
(4, Decimal('2.82'), 183, 39)
(2, Decimal('16.49'), 183, 96)
(2, Decimal('6.92'), 183, 97)
(1, Decimal('3.50'), 183, 148)
(4, Decimal('9.14'), 183, 155)
(3, Decimal('4.30'), 183, 192)
(1, Decimal('3.46'), 184, 1)
(2, Decimal('7.38'), 184, 72)
(4, Decimal('2.81'), 184, 178)
(2, Decimal('1.67'), 185, 179)
(1, Decimal('2.81'), 186, 39)
(4, Decimal('7.05'), 186, 40)
(4, Decimal('6.70'), 186, 79)
(2, Decimal('5.46'), 186, 122)
(3, Decimal('1.72'), 186, 136)
(3, Decimal('5.46'), 186, 166)
(3, Decimal('9.06'), 187, 120)
(1, Decimal('4.48'), 188, 107)
(3, Decimal('7.49'), 188, 121)
(2, Decimal('2.24'), 188, 146)
(4, Decimal('1.87'), 188, 168)
(3, Decimal('8.44'), 188, 174)
(3, Decimal('9.63'), 188, 181)
(2, Decimal('7.01'), 189, 190)
(4, Decimal('2.12'), 190, 225)
(3, Decimal('3.92'), 191, 63)
(1, Decimal('13.29'), 192, 109)
(2, Decimal('10.19'), 192, 218)
(1, Decimal('6.83'), 192, 226)
(2, Decimal('2.22'), 193, 25)
(4, Decimal('5.36'), 193, 81)
(3, Decimal('5.41'), 193, 180)
(2, Decimal('2.82'), 193, 222)
(3, Decimal('2.75'), 194, 59)
(1, Decimal('9.08'), 194, 211)
(2, Decimal('6.00'), 194, 228)
(2, Decimal('0.79'), 195, 36)
(4, Decimal('7.08'), 195, 121)
(3, Decimal('15.82'), 195, 175)
(4, Decimal('7.52'), 196, 50)
(2, Decimal('6.52'), 196, 133)
(2, Decimal('8.04'), 196, 174)
(3, Decimal('2.06'), 196, 179)
(1, Decimal('3.58'), 197, 30)
(4, Decimal('6.77'), 197, 54)
(2, Decimal('9.40'), 197, 103)

# payment

In [66]:
payment

,payment_id,payment_method,payment_status,total_amount,payment_date,card_id
0,1,paypal,Success,1.07,2026-02-12,NaN
1,2,credit card,Success,48.45,2026-02-04,18.0
2,3,debit card,Failed,50.12,2026-02-07,75.0
3,4,debit card,Success,20.85,2026-03-05,48.0
4,5,credit card,Failed,35.21,2026-02-22,62.0
...,...,...,...,...,...,...
215,216,credit card,Failed,84.19,2026-02-13,8.0
216,217,credit card,Success,41.02,2026-03-09,72.0
217,218,apple pay,Success,18.56,2026-03-08,NaN
218,219,paypal,Success,62.46,2026-03-12,NaN
219,220,apple pay,Success,135.35,2026-03-01,NaN

In [70]:
data = [
    tuple(None if pd.isna(item) else item for item in row) 
    for row in payment.itertuples(index=False, name=None)
]
query = "INSERT INTO payment(payment_id, payment_method, payment_status, total_amount, payment_date, card_id) VALUES (%s,%s,%s,%s,%s,%s)"
cursor.executemany(query, data)
cursor.execute("SELECT * FROM payment")
for i in cursor:
    print(i)

(1, 'paypal', 'Success', Decimal('1.07'), datetime.date(2026, 2, 12), None)
(2, 'credit card', 'Success', Decimal('48.45'), datetime.date(2026, 2, 4), 18)
(3, 'debit card', 'Failed', Decimal('50.12'), datetime.date(2026, 2, 7), 75)
(4, 'debit card', 'Success', Decimal('20.85'), datetime.date(2026, 3, 5), 48)
(5, 'credit card', 'Failed', Decimal('35.21'), datetime.date(2026, 2, 22), 62)
(6, 'credit card', 'Failed', Decimal('41.82'), datetime.date(2026, 3, 3), 52)
(7, 'paypal', 'Failed', Decimal('15.28'), datetime.date(2026, 2, 27), None)
(8, 'paypal', 'Success', Decimal('84.85'), datetime.date(2026, 2, 6), None)
(9, 'apple pay', 'Success', Decimal('56.16'), datetime.date(2026, 2, 3), None)
(10, 'google pay', 'Success', Decimal('116.38'), datetime.date(2026, 2, 19), None)
(11, 'debit card', 'Success', Decimal('102.20'), datetime.date(2026, 3, 29), 89)
(12, 'paypal', 'Success', Decimal('62.43'), datetime.date(2026, 3, 25), None)
(13, 'credit card', 'Success', Decimal('100.52'), datetime.date(2026, 2, 22), 48)
(14, 'paypal', 'Success', Decimal('34.32'), datetime.date(2026, 2, 25), None)
(15, 'credit card', 'Success', Decimal('81.03'), datetime.date(2026, 2, 3), 91)
(16, 'credit card', 'Success', Decimal('42.08'), datetime.date(2026, 3, 28), 53)
(17, 'apple pay', 'Success', Decimal('82.50'), datetime.date(2026, 2, 7), None)
(18, 'google pay', 'Success', Decimal('30.00'), datetime.date(2026, 3, 19), None)
(19, 'paypal', 'Success', Decimal('84.70'), datetime.date(2026, 2, 6), None)
(20, 'google pay', 'Success', Decimal('95.54'), datetime.date(2026, 2, 14), None)
(21, 'apple pay', 'Success', Decimal('54.75'), datetime.date(2026, 2, 27), None)
(22, 'paypal', 'Success', Decimal('98.10'), datetime.date(2026, 2, 8), None)
(23, 'apple pay', 'Success', Decimal('26.28'), datetime.date(2026, 3, 26), None)
(24, 'debit card', 'Success', Decimal('87.55'), datetime.date(2026, 2, 8), 87)
(25, 'credit card', 'Success', Decimal('41.12'), datetime.date(2026, 2, 14), 85)
(26, 'credit card', 'Success', Decimal('1.58'), datetime.date(2026, 3, 1), 10)
(27, 'credit card', 'Success', Decimal('67.54'), datetime.date(2026, 2, 8), 24)
(28, 'paypal', 'Failed', Decimal('74.12'), datetime.date(2026, 3, 4), None)
(29, 'google pay', 'Success', Decimal('56.71'), datetime.date(2026, 2, 28), None)
(30, 'google pay', 'Success', Decimal('70.39'), datetime.date(2026, 3, 9), None)
(31, 'paypal', 'Success', Decimal('85.62'), datetime.date(2026, 2, 28), None)
(32, 'debit card', 'Success', Decimal('32.47'), datetime.date(2026, 2, 3), 81)
(33, 'credit card', 'Failed', Decimal('20.76'), datetime.date(2026, 3, 1), 21)
(34, 'credit card', 'Success', Decimal('41.22'), datetime.date(2026, 2, 5), 28)
(35, 'apple pay', 'Failed', Decimal('58.43'), datetime.date(2026, 2, 9), None)
(36, 'debit card', 'Success', Decimal('35.86'), datetime.date(2026, 2, 23), 70)
(37, 'debit card', 'Success', Decimal('18.40'), datetime.date(2026, 2, 22), 32)
(38, 'apple pay', 'Success', Decimal('68.11'), datetime.date(2026, 3, 20), None)
(39, 'apple pay', 'Success', Decimal('60.06'), datetime.date(2026, 2, 3), None)
(40, 'apple pay', 'Success', Decimal('19.14'), datetime.date(2026, 3, 26), None)
(41, 'apple pay', 'Success', Decimal('64.31'), datetime.date(2026, 3, 5), None)
(42, 'credit card', 'Success', Decimal('61.22'), datetime.date(2026, 3, 9), 40)
(43, 'debit card', 'Success', Decimal('2.82'), datetime.date(2026, 2, 11), 95)
(44, 'google pay', 'Success', Decimal('56.52'), datetime.date(2026, 3, 23), None)
(45, 'paypal', 'Failed', Decimal('82.23'), datetime.date(2026, 2, 25), None)
(46, 'paypal', 'Failed', Decimal('94.14'), datetime.date(2026, 3, 26), None)
(47, 'google pay', 'Success', Decimal('37.41'), datetime.date(2026, 2, 11), None)
(48, 'apple pay', 'Success', Decimal('19.88'), datetime.date(2026, 3, 1), None)
(49, 'paypal', 'Failed', Decimal('131.41'), datetime.date(2026, 3, 9), None)
(50, 'credit card', 'Success', Decimal('20.98'), datetime.date(2026, 3, 24), 65)
(51, 'apple pay', 'Success', Decimal('72.31'), datetime.date(2026, 2, 12), None)
(52, 'debit card', 'Success', Decimal('70.76'), datetime.date(2026, 3, 8), 76)
(53, 'credit card', 'Failed', Decimal('95.41'), datetime.date(2026, 3, 17), 80)
(54, 'credit card', 'Success', Decimal('12.54'), datetime.date(2026, 2, 19), 29)
(55, 'google pay', 'Success', Decimal('39.64'), datetime.date(2026, 2, 14), None)
(56, 'credit card', 'Success', Decimal('48.72'), datetime.date(2026, 2, 10), 76)
(57, 'debit card', 'Success', Decimal('7.60'), datetime.date(2026, 2, 8), 2)
(58, 'credit card', 'Success', Decimal('64.13'), datetime.date(2026, 2, 20), 4)
(59, 'debit card', 'Failed', Decimal('13.53'), datetime.date(2026, 3, 26), 53)
(60, 'google pay', 'Success', Decimal('39.25'), datetime.date(2026, 3, 14), None)
(61, 'credit card', 'Success', Decimal('84.03'), datetime.date(2026, 2, 12), 62)
(62, 'credit card', 'Success', Decimal('84.40'), datetime.date(2026, 2, 3), 27)
(63, 'credit card', 'Success', Decimal('11.10'), datetime.date(2026, 3, 7), 14)
(64, 'credit card', 'Success', Decimal('24.90'), datetime.date(2026, 2, 12), 91)
(65, 'debit card', 'Success', Decimal('76.46'), datetime.date(2026, 3, 9), 17)
(66, 'credit card', 'Success', Decimal('24.44'), datetime.date(2026, 2, 3), 51)
(67, 'google pay', 'Success', Decimal('8.46'), datetime.date(2026, 3, 15), None)
(68, 'credit card', 'Success', Decimal('41.74'), datetime.date(2026, 2, 18), 31)
(69, 'credit card', 'Success', Decimal('67.02'), datetime.date(2026, 3, 16), 7)
(70, 'paypal', 'Success', Decimal('12.07'), datetime.date(2026, 3, 19), None)
(71, 'debit card', 'Failed', Decimal('45.09'), datetime.date(2026, 2, 2), 48)
(72, 'debit card', 'Success', Decimal('132.84'), datetime.date(2026, 3, 20), 90)
(73, 'debit card', 'Success', Decimal('37.31'), datetime.date(2026, 3, 13), 85)
(74, 'paypal', 'Success', Decimal('36.23'), datetime.date(2026, 3, 26), None)
(75, 'debit card', 'Success', Decimal('99.36'), datetime.date(2026, 3, 2), 50)
(76, 'debit card', 'Success', Decimal('82.50'), datetime.date(2026, 2, 2), 2)
(77, 'credit card', 'Failed', Decimal('9.18'), datetime.date(2026, 2, 19), 17)
(78, 'debit card', 'Success', Decimal('16.38'), datetime.date(2026, 2, 13), 62)
(79, 'credit card', 'Success', Decimal('14.34'), datetime.date(2026, 3, 19), 78)
(80, 'apple pay', 'Success', Decimal('16.12'), datetime.date(2026, 3, 12), None)
(81, 'debit card', 'Success', Decimal('76.53'), datetime.date(2026, 3, 14), 56)
(82, 'google pay', 'Success', Decimal('86.74'), datetime.date(2026, 3, 1), None)
(83, 'paypal', 'Failed', Decimal('76.43'), datetime.date(2026, 3, 27), None)
(84, 'credit card', 'Success', Decimal('33.15'), datetime.date(2026, 2, 27), 94)
(85, 'credit card', 'Success', Decimal('8.01'), datetime.date(2026, 3, 10), 43)
(86, 'google pay', 'Success', Decimal('44.10'), datetime.date(2026, 3, 1), None)
(87, 'credit card', 'Success', Decimal('36.65'), datetime.date(2026, 2, 2), 72)
(88, 'paypal', 'Success', Decimal('63.04'), datetime.date(2026, 2, 23), None)
(89, 'paypal', 'Success', Decimal('64.93'), datetime.date(2026, 2, 23), None)
(90, 'credit card', 'Success', Decimal('97.69'), datetime.date(2026, 3, 26), 41)
(91, 'paypal', 'Success', Decimal('47.76'), datetime.date(2026, 3, 25), None)
(92, 'debit card', 'Success', Decimal('59.99'), datetime.date(2026, 3, 2), 12)
(93, 'apple pay', 'Success', Decimal('82.10'), datetime.date(2026, 3, 13), None)
(94, 'paypal', 'Success', Decimal('58.04'), datetime.date(2026, 3, 7), None)
(95, 'apple pay', 'Failed', Decimal('7.50'), datetime.date(2026, 3, 18), None)
(96, 'apple pay', 'Success', Decimal('95.29'), datetime.date(2026, 2, 17), None)
(97, 'debit card', 'Success', Decimal('35.69'), datetime.date(2026, 2, 23), 87)
(98, 'paypal', 'Failed', Decimal('42.54'), datetime.date(2026, 3, 28), None)
(99, 'google pay', 'Success', Decimal('56.54'), datetime.date(2026, 3, 24), None)
(100, 'apple pay', 'Success', Decimal('21.59'), datetime.date(2026, 2, 5), None)
(101, 'credit card', 'Success', Decimal('61.80'), datetime.date(2026, 2, 14), 81)
(102, 'apple pay', 'Success', Decimal('51.02'), datetime.date(2026, 3, 27), None)
(103, 'apple pay', 'Failed', Decimal('26.88'), datetime.date(2026, 3, 11), None)
(104, 'apple pay', 'Success', Decimal('45.22'), datetime.date(2026, 2, 11), None)
(105, 'debit card', 'Success', Decimal('114.22'), datetime.date(2026, 2, 25), 51)
(106, 'paypal', 'Success', Decimal('48.05'), datetime.date(2026, 3, 3), None)
(107, 'debit card', 'Success', Decimal('90.95'), datetime.date(2026, 2, 5), 1)
(108, 'debit card', 'Success', Decimal('68.49'), datetime.date(2026, 3, 11), 68)
(109, 'debit card', 'Success', Decimal('55.60'), datetime.date(2026, 2, 16), 59)
(110, 'credit card', 'Success', Decimal('10.59'), datetime.date(2026, 2, 24), 87)
(111, 'debit card', 'Success', Decimal('8.54'), datetime.date(2026, 3, 13), 2)
(112, 'debit card', 'Success', Decimal('29.25'), datetime.date(2026, 2, 1), 97)
(113, 'credit card', 'Success', Decimal('31.77'), datetime.date(2026, 2, 17), 88)
(114, 'apple pay', 'Success', Decimal('44.68'), datetime.date(2026, 3, 22), None)
(115, 'debit card', 'Success', Decimal('25.88'), datetime.date(2026, 3, 5), 45)
(116, 'credit card', 'Success', Decimal('62.30'), datetime.date(2026, 3, 20), 21)
(117, 'credit card', 'Success', Decimal('54.14'), datetime.date(2026, 3, 22), 16)
(118, 'credit card', 'Success', Decimal('31.64'), datetime.date(2026, 3, 12), 96)
(119, 'debit card', 'Success', Decimal('20.92'), datetime.date(2026, 3, 27), 31)
(120, 'debit card', 'Success', Decimal('74.87'), datetime.date(2026, 3, 19), 79)
(121, 'paypal', 'Success', Decimal('56.05'), datetime.date(2026, 3, 23), None)
(122, 'credit card', 'Success', Decimal('26.52'), datetime.date(2026, 3, 24), 99)
(123, 'debit card', 'Failed', Decimal('119.18'), datetime.date(2026, 3, 20), 86)
(124, 'credit card', 'Success', Decimal('48.57'), datetime.date(2026, 3, 5), 7)
(125, 'debit card', 'Success', Decimal('80.17'), datetime.date(2026, 3, 1), 62)
(126, 'google pay', 'Success', Decimal('118.85'), datetime.date(2026, 2, 9), None)
(127, 'debit card', 'Success', Decimal('35.85'), datetime.date(2026, 3, 6), 31)
(128, 'debit card', 'Success', Decimal('8.26'), datetime.date(2026, 2, 1), 57)
(129, 'credit card', 'Success', Decimal('58.37'), datetime.date(2026, 3, 21), 27)
(130, 'apple pay', 'Success', Decimal('47.99'), datetime.date(2026, 2, 12), None)
(131, 'credit card', 'Success', Decimal('77.96'), datetime.date(2026, 3, 17), 63)
(132, 'debit card', 'Success', Decimal('36.54'), datetime.date(2026, 2, 27), 42)
(133, 'debit card', 'Success', Decimal('102.95'), datetime.date(2026, 2, 14), 77)
(134, 'credit card', 'Success', Decimal('87.92'), datetime.date(2026, 2, 11), 1)
(135, 'debit card', 'Failed', Decimal('51.81'), datetime.date(2026, 2, 10), 22)
(136, 'credit card', 'Success', Decimal('44.28'), datetime.date(2026, 3, 7), 85)
(137, 'apple pay', 'Success', Decimal('15.94'), datetime.date(2026, 3, 7), None)
(138, 'debit card', 'Success', Decimal('144.22'), datetime.date(2026, 3, 17), 80)
(139, 'google pay', 'Success', Decimal('19.22'), datetime.date(2026, 2, 5), None)
(140, 'credit card', 'Failed', Decimal('40.68'), datetime.date(2026, 2, 4), 37)
(141, 'debit card', 'Failed', Decimal('7.58'), datetime.date(2026, 2, 23), 1)
(142, 'debit card', 'Success', Decimal('47.47'), datetime.date(2026, 3, 5), 98)
(143, 'credit card', 'Failed', Decimal('44.81'), datetime.date(2026, 3, 14), 46)
(144, 'debit card', 'Failed', Decimal('27.93'), datetime.date(2026, 3, 8), 72)
(145, 'apple pay', 'Success', Decimal('27.08'), datetime.date(2026, 3, 15), None)
(146, 'debit card', 'Failed', Decimal('138.62'), datetime.date(2026, 3, 9), 76)
(147, 'paypal', 'Success', Decimal('18.92'), datetime.date(2026, 2, 19), None)
(148, 'credit card', 'Failed', Decimal('32.80'), datetime.date(2026, 3, 14), 71)
(149, 'google pay', 'Success', Decimal('84.81'), datetime.date(2026, 3, 1), None)
(150, 'paypal', 'Success', Decimal('57.31'), datetime.date(2026, 2, 28), None)
(151, 'apple pay', 'Success', Decimal('103.18'), datetime.date(2026, 3, 20), None)
(152, 'apple pay', 'Failed', Decimal('76.71'), datetime.date(2026, 2, 5), None)
(153, 'paypal', 'Success', Decimal('36.69'), datetime.date(2026, 3, 7), None)
(154, 'debit card', 'Success', Decimal('37.17'), datetime.date(2026, 3, 1), 49)
(155, 'credit card', 'Success', Decimal('55.93'), datetime.date(2026, 3, 4), 16)
(156, 'google pay', 'Success', Decimal('5.10'), datetime.date(2026, 3, 20), None)
(157, 'debit card', 'Failed', Decimal('85.48'), datetime.date(2026, 3, 1), 45)
(158, 'apple pay', 'Success', Decimal('74.25'), datetime.date(2026, 3, 26), None)
(159, 'credit card', 'Success', Decimal('42.20'), datetime.date(2026, 3, 20), 88)
(160, 'credit card', 'Success', Decimal('51.32'), datetime.date(2026, 3, 12), 29)
(161, 'paypal', 'Success', Decimal('19.36'), datetime.date(2026, 3, 2), None)
(162, 'apple pay', 'Success', Decimal('116.53'), datetime.date(2026, 3, 4), None)
(163, 'apple pay', 'Success', Decimal('32.88'), datetime.date(2026, 3, 3), None)
(164, 'apple pay', 'Success', Decimal('86.54'), datetime.date(2026, 3, 13), None)
(165, 'credit card', 'Success', Decimal('55.97'), datetime.date(2026, 2, 18), 25)
(166, 'google pay', 'Failed', Decimal('113.14'), datetime.date(2026, 2, 22), None)
(167, 'google pay', 'Success', Decimal('93.66'), datetime.date(2026, 3, 28), None)
(168, 'debit card', 'Success', Decimal('108.25'), datetime.date(2026, 2, 10), 14)
(169, 'apple pay', 'Success', Decimal('85.84'), datetime.date(2026, 2, 1), None)
(170, 'apple pay', 'Failed', Decimal('31.78'), datetime.date(2026, 3, 1), None)
(171, 'debit card', 'Success', Decimal('93.98'), datetime.date(2026, 3, 19), 68)
(172, 'credit card', 'Success', Decimal('59.06'), datetime.date(2026, 3, 14), 90)
(173, 'credit card', 'Success', Decimal('32.98'), datetime.date(2026, 2, 8), 56)
(174, 'credit card', 'Success', Decimal('75.85'), datetime.date(2026, 2, 18), 33)
(175, 'google pay', 'Failed', Decimal('109.67'), datetime.date(2026, 3, 9), None)
(176, 'credit card', 'Success', Decimal('8.81'), datetime.date(2026, 3, 16), 25)
(177, 'google pay', 'Success', Decimal('3.38'), datetime.date(2026, 3, 2), None)
(178, 'credit card', 'Success', Decimal('12.87'), datetime.date(2026, 3, 20), 77)
(179, 'google pay', 'Success', Decimal('39.90'), datetime.date(2026, 3, 22), None)
(180, 'apple pay', 'Success', Decimal('102.00'), datetime.date(2026, 3, 20), None)
(181, 'debit card', 'Success', Decimal('36.48'), datetime.date(2026, 3, 5), 35)
(182, 'debit card', 'Success', Decimal('140.24'), datetime.date(2026, 3, 17), 92)
(183, 'debit card', 'Success', Decimal('111.06'), datetime.date(2026, 3, 22), 27)
(184, 'credit card', 'Success', Decimal('29.46'), datetime.date(2026, 2, 8), 32)
(185, 'credit card', 'Failed', Decimal('3.34'), datetime.date(2026, 3, 17), 34)
(186, 'paypal', 'Success', Decimal('90.27'), datetime.date(2026, 3, 9), None)
(187, 'debit card', 'Failed', Decimal('27.18'), datetime.date(2026, 3, 19), 30)
(188, 'debit card', 'Success', Decimal('93.12'), datetime.date(2026, 3, 17), 40)
(189, 'debit card', 'Success', Decimal('14.02'), datetime.date(2026, 2, 12), 75)
(190, 'credit card', 'Success', Decimal('8.48'), datetime.date(2026, 3, 16), 40)
(191, 'credit card', 'Success', Decimal('11.76'), datetime.date(2026, 3, 6), 7)
(192, 'debit card', 'Success', Decimal('40.50'), datetime.date(2026, 3, 27), 96)
(193, 'credit card', 'Success', Decimal('47.75'), datetime.date(2026, 2, 8), 96)
(194, 'credit card', 'Failed', Decimal('29.33'), datetime.date(2026, 3, 27), 19)
(195, 'credit card', 'Success', Decimal('77.36'), datetime.date(2026, 2, 23), 34)
(196, 'apple pay', 'Success', Decimal('65.38'), datetime.date(2026, 2, 5), None)
(197, 'google pay', 'Success', Decimal('73.93'), datetime.date(2026, 3, 22), None)
(198, 'debit card', 'Success', Decimal('125.44'), datetime.date(2026, 3, 4), 83)
(199, 'debit card', 'Success', Decimal('56.98'), datetime.date(2026, 2, 8), 15)
(200, 'paypal', 'Success', Decimal('42.17'), datetime.date(2026, 3, 4), None)
(201, 'debit card', 'Success', Decimal('66.81'), datetime.date(2026, 3, 12), 100)
(202, 'debit card', 'Success', Decimal('92.31'), datetime.date(2026, 2, 22), 47)
(203, 'credit card', 'Failed', Decimal('19.75'), datetime.date(2026, 3, 18), 6)
(204, 'credit card', 'Failed', Decimal('23.37'), datetime.date(2026, 3, 7), 39)
(205, 'google pay', 'Success', Decimal('20.56'), datetime.date(2026, 2, 22), None)
(206, 'apple pay', 'Success', Decimal('24.76'), datetime.date(2026, 3, 18), None)
(207, 'credit card', 'Success', Decimal('20.52'), datetime.date(2026, 3, 10), 96)
(208, 'credit card', 'Success', Decimal('8.82'), datetime.date(2026, 3, 3), 75)
(209, 'google pay', 'Success', Decimal('77.70'), datetime.date(2026, 2, 16), None)
(210, 'credit card', 'Success', Decimal('85.74'), datetime.date(2026, 2, 23), 2)
(211, 'debit card', 'Success', Decimal('57.36'), datetime.date(2026, 3, 7), 32)
(212, 'paypal', 'Success', Decimal('113.75'), datetime.date(2026, 3, 25), None)
(213, 'credit card', 'Failed', Decimal('22.81'), datetime.date(2026, 2, 18), 17)
(214, 'debit card', 'Success', Decimal('18.40'), datetime.date(2026, 2, 1), 97)
(215, 'apple pay', 'Success', Decimal('7.22'), datetime.date(2026, 2, 16), None)
(216, 'credit card', 'Failed', Decimal('84.19'), datetime.date(2026, 2, 13), 8)
(217, 'credit card', 'Success', Decimal('41.02'), datetime.date(2026, 3, 9), 72)
(218, 'apple pay', 'Success', Decimal('18.56'), datetime.date(2026, 3, 8), None)
(219, 'paypal', 'Success', Decimal('62.46'), datetime.date(2026, 3, 12), None)
(220, 'apple pay', 'Success', Decimal('135.35'), datetime.date(2026, 3, 1), None)

# Delivery Details

## delivery details

In [71]:
delivery_details

     delivery_id delivery_status delivery_date
0              1   not delivered    2026-02-15
1              2   not delivered    2026-02-06
2              3   not delivered    2026-02-08
3              4       delivered    2026-03-07
4              5   not delivered    2026-02-25
..           ...             ...           ...
128          129   not delivered    2026-03-28
129          130   not delivered    2026-02-15
130          131       delivered    2026-03-10
131          132   not delivered    2026-03-09
132          133       delivered    2026-03-03

[133 rows x 3 columns]

In [72]:
query = "INSERT INTO delivery_details(delivery_id, delivery_status, delivery_date) VALUES (%s,%s,%s)"
data = list(delivery_details.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM delivery_details")
for i in cursor:
    print(i)

(1, 'not delivered', datetime.date(2026, 2, 15))
(2, 'not delivered', datetime.date(2026, 2, 6))
(3, 'not delivered', datetime.date(2026, 2, 8))
(4, 'delivered', datetime.date(2026, 3, 7))
(5, 'not delivered', datetime.date(2026, 2, 25))
(6, 'not delivered', datetime.date(2026, 3, 6))
(7, 'not delivered', datetime.date(2026, 2, 9))
(8, 'not delivered', datetime.date(2026, 2, 22))
(9, 'not delivered', datetime.date(2026, 4, 1))
(10, 'not delivered', datetime.date(2026, 2, 28))
(11, 'not delivered', datetime.date(2026, 3, 22))
(12, 'not delivered', datetime.date(2026, 2, 8))
(13, 'not delivered', datetime.date(2026, 2, 15))
(14, 'delivered', datetime.date(2026, 2, 28))
(15, 'not delivered', datetime.date(2026, 2, 9))
(16, 'not delivered', datetime.date(2026, 3, 28))
(17, 'delivered', datetime.date(2026, 2, 10))
(18, 'not delivered', datetime.date(2026, 2, 16))
(19, 'delivered', datetime.date(2026, 3, 2))
(20, 'not delivered', datetime.date(2026, 3, 1))
(21, 'not delivered', datetime.date(2026, 2, 5))
(22, 'not delivered', datetime.date(2026, 2, 24))
(23, 'not delivered', datetime.date(2026, 2, 4))
(24, 'delivered', datetime.date(2026, 3, 6))
(25, 'not delivered', datetime.date(2026, 2, 13))
(26, 'not delivered', datetime.date(2026, 3, 25))
(27, 'not delivered', datetime.date(2026, 2, 28))
(28, 'not delivered', datetime.date(2026, 3, 28))
(29, 'delivered', datetime.date(2026, 2, 11))
(30, 'not delivered', datetime.date(2026, 3, 2))
(31, 'not delivered', datetime.date(2026, 3, 10))
(32, 'delivered', datetime.date(2026, 3, 25))
(33, 'not delivered', datetime.date(2026, 2, 13))
(34, 'not delivered', datetime.date(2026, 2, 15))
(35, 'not delivered', datetime.date(2026, 2, 13))
(36, 'not delivered', datetime.date(2026, 2, 11))
(37, 'not delivered', datetime.date(2026, 2, 21))
(38, 'not delivered', datetime.date(2026, 3, 29))
(39, 'not delivered', datetime.date(2026, 2, 13))
(40, 'not delivered', datetime.date(2026, 3, 9))
(41, 'not delivered', datetime.date(2026, 2, 14))
(42, 'delivered', datetime.date(2026, 2, 19))
(43, 'not delivered', datetime.date(2026, 3, 21))
(44, 'not delivered', datetime.date(2026, 2, 5))
(45, 'delivered', datetime.date(2026, 3, 22))
(46, 'not delivered', datetime.date(2026, 3, 16))
(47, 'not delivered', datetime.date(2026, 3, 3))
(48, 'not delivered', datetime.date(2026, 2, 4))
(49, 'not delivered', datetime.date(2026, 2, 22))
(50, 'not delivered', datetime.date(2026, 3, 3))
(51, 'not delivered', datetime.date(2026, 3, 30))
(52, 'not delivered', datetime.date(2026, 3, 1))
(53, 'not delivered', datetime.date(2026, 3, 12))
(54, 'delivered', datetime.date(2026, 2, 4))
(55, 'not delivered', datetime.date(2026, 3, 27))
(56, 'not delivered', datetime.date(2026, 3, 14))
(57, 'not delivered', datetime.date(2026, 3, 9))
(58, 'not delivered', datetime.date(2026, 3, 20))
(59, 'not delivered', datetime.date(2026, 3, 30))
(60, 'not delivered', datetime.date(2026, 3, 25))
(61, 'not delivered', datetime.date(2026, 2, 6))
(62, 'not delivered', datetime.date(2026, 3, 14))
(63, 'not delivered', datetime.date(2026, 2, 14))
(64, 'delivered', datetime.date(2026, 2, 26))
(65, 'delivered', datetime.date(2026, 2, 7))
(66, 'not delivered', datetime.date(2026, 2, 27))
(67, 'delivered', datetime.date(2026, 3, 13))
(68, 'not delivered', datetime.date(2026, 2, 2))
(69, 'delivered', datetime.date(2026, 2, 18))
(70, 'not delivered', datetime.date(2026, 3, 8))
(71, 'not delivered', datetime.date(2026, 3, 22))
(72, 'not delivered', datetime.date(2026, 3, 15))
(73, 'delivered', datetime.date(2026, 3, 27))
(74, 'not delivered', datetime.date(2026, 3, 25))
(75, 'not delivered', datetime.date(2026, 3, 3))
(76, 'delivered', datetime.date(2026, 3, 23))
(77, 'delivered', datetime.date(2026, 3, 18))
(78, 'not delivered', datetime.date(2026, 2, 28))
(79, 'not delivered', datetime.date(2026, 2, 16))
(80, 'delivered', datetime.date(2026, 2, 12))
(81, 'not delivered', datetime.date(2026, 2, 12))
(82, 'not delivered', datetime.date(2026, 3, 9))
(83, 'not delivered', datetime.date(2026, 3, 19))
(84, 'not delivered', datetime.date(2026, 3, 8))
(85, 'not delivered', datetime.date(2026, 3, 15))
(86, 'not delivered', datetime.date(2026, 3, 10))
(87, 'not delivered', datetime.date(2026, 3, 18))
(88, 'not delivered', datetime.date(2026, 3, 11))
(89, 'not delivered', datetime.date(2026, 3, 16))
(90, 'not delivered', datetime.date(2026, 3, 3))
(91, 'not delivered', datetime.date(2026, 3, 21))
(92, 'not delivered', datetime.date(2026, 2, 8))
(93, 'not delivered', datetime.date(2026, 3, 3))
(94, 'not delivered', datetime.date(2026, 3, 21))
(95, 'not delivered', datetime.date(2026, 3, 13))
(96, 'not delivered', datetime.date(2026, 3, 6))
(97, 'not delivered', datetime.date(2026, 2, 19))
(98, 'not delivered', datetime.date(2026, 2, 25))
(99, 'not delivered', datetime.date(2026, 2, 3))
(100, 'not delivered', datetime.date(2026, 3, 4))
(101, 'not delivered', datetime.date(2026, 3, 22))
(102, 'not delivered', datetime.date(2026, 2, 21))
(103, 'not delivered', datetime.date(2026, 3, 17))
(104, 'delivered', datetime.date(2026, 3, 4))
(105, 'delivered', datetime.date(2026, 3, 21))
(106, 'delivered', datetime.date(2026, 3, 23))
(107, 'not delivered', datetime.date(2026, 3, 23))
(108, 'delivered', datetime.date(2026, 3, 18))
(109, 'not delivered', datetime.date(2026, 2, 11))
(110, 'not delivered', datetime.date(2026, 3, 12))
(111, 'not delivered', datetime.date(2026, 3, 19))
(112, 'delivered', datetime.date(2026, 3, 17))
(113, 'not delivered', datetime.date(2026, 3, 8))
(114, 'not delivered', datetime.date(2026, 3, 29))
(115, 'not delivered', datetime.date(2026, 2, 11))
(116, 'not delivered', datetime.date(2026, 2, 25))
(117, 'not delivered', datetime.date(2026, 2, 7))
(118, 'not delivered', datetime.date(2026, 3, 24))
(119, 'not delivered', datetime.date(2026, 3, 5))
(120, 'not delivered', datetime.date(2026, 3, 5))
(121, 'not delivered', datetime.date(2026, 3, 15))
(122, 'not delivered', datetime.date(2026, 2, 24))
(123, 'not delivered', datetime.date(2026, 3, 10))
(124, 'not delivered', datetime.date(2026, 2, 25))
(125, 'delivered', datetime.date(2026, 3, 19))
(126, 'not delivered', datetime.date(2026, 2, 18))
(127, 'not delivered', datetime.date(2026, 2, 25))
(128, 'not delivered', datetime.date(2026, 3, 10))
(129, 'not delivered', datetime.date(2026, 3, 28))
(130, 'not delivered', datetime.date(2026, 2, 15))
(131, 'delivered', datetime.date(2026, 3, 10))
(132, 'not delivered', datetime.date(2026, 3, 9))
(133, 'delivered', datetime.date(2026, 3, 3))

## Delivery address

In [73]:
delivery_address

,street,city,state,country,zip_code,delivery_id
0,474 Broadway,Medford,Massachusetts,USA,2155,1
1,640 Oak St,Quincy,Massachusetts,USA,2169,2
2,990 Cedar St,Boston,Massachusetts,USA,2108,3
3,751 Franklin St,Boston,Massachusetts,USA,2108,4
4,447 River St,Brookline,Massachusetts,USA,2445,5
...,...,...,...,...,...,...
128,855 Walnut St,Brookline,Massachusetts,USA,2445,129
129,763 Massachusetts Ave,Salem,Massachusetts,USA,1970,130
130,526 Walnut St,Waltham,Massachusetts,USA,2451,131
131,686 Summer St,Cambridge,Massachusetts,USA,2139,132
132,311 Massachusetts Ave,Cambridge,Massachusetts,USA,2139,133

In [74]:
query = "INSERT INTO delivery_address(street, city, state, country, zip_code, delivery_id) VALUES (%s,%s,%s,%s,%s,%s)"
data = list(delivery_address.itertuples(index=False, name=None))
cursor.executemany(query, data)
cursor.execute("SELECT * FROM delivery_address")
for i in cursor:
    print(i)

('474 Broadway', 'Medford', 'Massachusetts', 'USA', '2155', 1)
('640 Oak St', 'Quincy', 'Massachusetts', 'USA', '2169', 2)
('990 Cedar St', 'Boston', 'Massachusetts', 'USA', '2108', 3)
('751 Franklin St', 'Boston', 'Massachusetts', 'USA', '2108', 4)
('447 River St', 'Brookline', 'Massachusetts', 'USA', '2445', 5)
('377 Pleasant St', 'Brookline', 'Massachusetts', 'USA', '2445', 6)
('371 Massachusetts Ave', 'Medford', 'Massachusetts', 'USA', '2155', 7)
('946 Oak St', 'Somerville', 'Massachusetts', 'USA', '2143', 8)
('402 Prospect St', 'Revere', 'Massachusetts', 'USA', '2151', 9)
('122 School St', 'Malden', 'Massachusetts', 'USA', '2148', 10)
('51 Summer St', 'Salem', 'Massachusetts', 'USA', '1970', 11)
('977 Prospect St', 'Brookline', 'Massachusetts', 'USA', '2445', 12)
('398 Summer St', 'Salem', 'Massachusetts', 'USA', '1970', 13)
('464 Maple St', 'Somerville', 'Massachusetts', 'USA', '2143', 14)
('86 Washington St', 'Revere', 'Massachusetts', 'USA', '2151', 15)
('384 Oak St', 'Malden', 'Massachusetts', 'USA', '2148', 16)
('946 Highland Ave', 'Boston', 'Massachusetts', 'USA', '2108', 17)
('451 Walnut St', 'Somerville', 'Massachusetts', 'USA', '2143', 18)
('110 Elm St', 'Waltham', 'Massachusetts', 'USA', '2451', 19)
('678 Cedar St', 'Quincy', 'Massachusetts', 'USA', '2169', 20)
('215 Summer St', 'Revere', 'Massachusetts', 'USA', '2151', 21)
('953 Franklin St', 'Medford', 'Massachusetts', 'USA', '2155', 22)
('100 Beacon St', 'Boston', 'Massachusetts', 'USA', '2108', 23)
('573 Broadway', 'Salem', 'Massachusetts', 'USA', '1970', 24)
('360 Franklin St', 'Boston', 'Massachusetts', 'USA', '2108', 25)
('938 Beacon St', 'Malden', 'Massachusetts', 'USA', '2148', 26)
('153 Pine St', 'Revere', 'Massachusetts', 'USA', '2151', 27)
('678 Pleasant St', 'Boston', 'Massachusetts', 'USA', '2108', 28)
('810 Beacon St', 'Waltham', 'Massachusetts', 'USA', '2451', 29)
('370 Highland Ave', 'Somerville', 'Massachusetts', 'USA', '2143', 30)
('611 Cedar St', 'Watertown', 'Massachusetts', 'USA', '2472', 31)
('663 Franklin St', 'Watertown', 'Massachusetts', 'USA', '2472', 32)
('996 Franklin St', 'Brookline', 'Massachusetts', 'USA', '2445', 33)
('910 Prospect St', 'Waltham', 'Massachusetts', 'USA', '2451', 34)
('772 Park Ave', 'Malden', 'Massachusetts', 'USA', '2148', 35)
('927 Chestnut St', 'Waltham', 'Massachusetts', 'USA', '2451', 36)
('534 Beacon St', 'Quincy', 'Massachusetts', 'USA', '2169', 37)
('866 Park Ave', 'Cambridge', 'Massachusetts', 'USA', '2139', 38)
('368 Broadway', 'Boston', 'Massachusetts', 'USA', '2108', 39)
('224 Pleasant St', 'Watertown', 'Massachusetts', 'USA', '2472', 40)
('335 Oak St', 'Somerville', 'Massachusetts', 'USA', '2143', 41)
('311 Cedar St', 'Salem', 'Massachusetts', 'USA', '1970', 42)
('988 River St', 'Revere', 'Massachusetts', 'USA', '2151', 43)
('279 Highland Ave', 'Revere', 'Massachusetts', 'USA', '2151', 44)
('886 Massachusetts Ave', 'Malden', 'Massachusetts', 'USA', '2148', 45)
('949 Pleasant St', 'Malden', 'Massachusetts', 'USA', '2148', 46)
('195 Massachusetts Ave', 'Somerville', 'Massachusetts', 'USA', '2143', 47)
('71 River St', 'Newton', 'Massachusetts', 'USA', '2458', 48)
('417 Maple St', 'Malden', 'Massachusetts', 'USA', '2148', 49)
('114 Pine St', 'Quincy', 'Massachusetts', 'USA', '2169', 50)
('116 Massachusetts Ave', 'Somerville', 'Massachusetts', 'USA', '2143', 51)
('620 Pine St', 'Quincy', 'Massachusetts', 'USA', '2169', 52)
('776 Chestnut St', 'Medford', 'Massachusetts', 'USA', '2155', 53)
('351 Cedar St', 'Salem', 'Massachusetts', 'USA', '1970', 54)
('625 River St', 'Revere', 'Massachusetts', 'USA', '2151', 55)
('945 Franklin St', 'Boston', 'Massachusetts', 'USA', '2108', 56)
('722 River St', 'Quincy', 'Massachusetts', 'USA', '2169', 57)
('17 Broadway', 'Quincy', 'Massachusetts', 'USA', '2169', 58)
('75 Walnut St', 'Malden', 'Massachusetts', 'USA', '2148', 59)
('91 Elm St', 'Revere', 'Massachusetts', 'USA', '2151', 60)
('104 Elm St', 'Malden', 'Massachusetts', 'USA', '2148', 61)
('665 River St', 'Watertown', 'Massachusetts', 'USA', '2472', 62)
('331 Cedar St', 'Boston', 'Massachusetts', 'USA', '2108', 63)
('996 Highland Ave', 'Cambridge', 'Massachusetts', 'USA', '2139', 64)
('528 Franklin St', 'Malden', 'Massachusetts', 'USA', '2148', 65)
('433 Summer St', 'Boston', 'Massachusetts', 'USA', '2108', 66)
('624 School St', 'Cambridge', 'Massachusetts', 'USA', '2139', 67)
('108 Highland Ave', 'Quincy', 'Massachusetts', 'USA', '2169', 68)
('816 Walnut St', 'Watertown', 'Massachusetts', 'USA', '2472', 69)
('132 River St', 'Brookline', 'Massachusetts', 'USA', '2445', 70)
('343 Elm St', 'Watertown', 'Massachusetts', 'USA', '2472', 71)
('315 Oak St', 'Watertown', 'Massachusetts', 'USA', '2472', 72)
('272 Park Ave', 'Brookline', 'Massachusetts', 'USA', '2445', 73)
('640 Oak St', 'Waltham', 'Massachusetts', 'USA', '2451', 74)
('996 Washington St', 'Boston', 'Massachusetts', 'USA', '2108', 75)
('205 School St', 'Medford', 'Massachusetts', 'USA', '2155', 76)
('461 Pine St', 'Cambridge', 'Massachusetts', 'USA', '2139', 77)
('219 River St', 'Quincy', 'Massachusetts', 'USA', '2169', 78)
('16 Cedar St', 'Malden', 'Massachusetts', 'USA', '2148', 79)
('556 Chestnut St', 'Revere', 'Massachusetts', 'USA', '2151', 80)
('948 Chestnut St', 'Medford', 'Massachusetts', 'USA', '2155', 81)
('343 Franklin St', 'Medford', 'Massachusetts', 'USA', '2155', 82)
('820 Oak St', 'Malden', 'Massachusetts', 'USA', '2148', 83)
('612 Oak St', 'Quincy', 'Massachusetts', 'USA', '2169', 84)
('101 Washington St', 'Watertown', 'Massachusetts', 'USA', '2472', 85)
('532 Park Ave', 'Boston', 'Massachusetts', 'USA', '2108', 86)
('328 Oak St', 'Malden', 'Massachusetts', 'USA', '2148', 87)
('426 Highland Ave', 'Waltham', 'Massachusetts', 'USA', '2451', 88)
('970 Cedar St', 'Waltham', 'Massachusetts', 'USA', '2451', 89)
('702 Broadway', 'Brookline', 'Massachusetts', 'USA', '2445', 90)
('17 School St', 'Quincy', 'Massachusetts', 'USA', '2169', 91)
('443 Broadway', 'Waltham', 'Massachusetts', 'USA', '2451', 92)
('665 Elm St', 'Cambridge', 'Massachusetts', 'USA', '2139', 93)
('939 Maple St', 'Somerville', 'Massachusetts', 'USA', '2143', 94)
('636 Beacon St', 'Malden', 'Massachusetts', 'USA', '2148', 95)
('637 Broadway', 'Boston', 'Massachusetts', 'USA', '2108', 96)
('878 Cedar St', 'Somerville', 'Massachusetts', 'USA', '2143', 97)
('505 Summer St', 'Newton', 'Massachusetts', 'USA', '2458', 98)
('511 School St', 'Medford', 'Massachusetts', 'USA', '2155', 99)
('319 Beacon St', 'Quincy', 'Massachusetts', 'USA', '2169', 100)
('285 Elm St', 'Newton', 'Massachusetts', 'USA', '2458', 101)
('850 Highland Ave', 'Watertown', 'Massachusetts', 'USA', '2472', 102)
('276 Park Ave', 'Somerville', 'Massachusetts', 'USA', '2143', 103)
('502 Highland Ave', 'Somerville', 'Massachusetts', 'USA', '2143', 104)
('428 Cedar St', 'Brookline', 'Massachusetts', 'USA', '2445', 105)
('953 Beacon St', 'Watertown', 'Massachusetts', 'USA', '2472', 106)
('359 Elm St', 'Revere', 'Massachusetts', 'USA', '2151', 107)
('562 Broadway', 'Revere', 'Massachusetts', 'USA', '2151', 108)
('265 Oak St', 'Medford', 'Massachusetts', 'USA', '2155', 109)
('932 Walnut St', 'Brookline', 'Massachusetts', 'USA', '2445', 110)
('344 Franklin St', 'Revere', 'Massachusetts', 'USA', '2151', 111)
('290 Massachusetts Ave', 'Quincy', 'Massachusetts', 'USA', '2169', 112)
('132 Main St', 'Medford', 'Massachusetts', 'USA', '2155', 113)
('266 Massachusetts Ave', 'Watertown', 'Massachusetts', 'USA', '2472', 114)
('49 Massachusetts Ave', 'Brookline', 'Massachusetts', 'USA', '2445', 115)
('782 Cedar St', 'Somerville', 'Massachusetts', 'USA', '2143', 116)
('361 Washington St', 'Cambridge', 'Massachusetts', 'USA', '2139', 117)
('637 Chestnut St', 'Brookline', 'Massachusetts', 'USA', '2445', 118)
('400 Maple St', 'Watertown', 'Massachusetts', 'USA', '2472', 119)
('883 School St', 'Brookline', 'Massachusetts', 'USA', '2445', 120)
('906 River St', 'Revere', 'Massachusetts', 'USA', '2151', 121)
('326 Highland Ave', 'Medford', 'Massachusetts', 'USA', '2155', 122)
('331 Pleasant St', 'Brookline', 'Massachusetts', 'USA', '2445', 123)
('690 Highland Ave', 'Malden', 'Massachusetts', 'USA', '2148', 124)
('70 Highland Ave', 'Salem', 'Massachusetts', 'USA', '1970', 125)
('478 Prospect St', 'Brookline', 'Massachusetts', 'USA', '2445', 126)
('336 School St', 'Revere', 'Massachusetts', 'USA', '2151', 127)
('667 Highland Ave', 'Malden', 'Massachusetts', 'USA', '2148', 128)
('855 Walnut St', 'Brookline', 'Massachusetts', 'USA', '2445', 129)
('763 Massachusetts Ave', 'Salem', 'Massachusetts', 'USA', '1970', 130)
('526 Walnut St', 'Waltham', 'Massachusetts', 'USA', '2451', 131)
('686 Summer St', 'Cambridge', 'Massachusetts', 'USA', '2139', 132)
('311 Massachusetts Ave', 'Cambridge', 'Massachusetts', 'USA', '2139', 133)

## order confirmation

In [75]:
order_confirmation

     order_id  payment_id  delivery_id confirmation_status
0           1           1          NaN           confirmed
1           2           2          NaN           confirmed
2           3           3          NaN       not confirmed
3           4           4          NaN           confirmed
4           5           5          NaN       not confirmed
..        ...         ...          ...                 ...
215       216         216          NaN       not confirmed
216       217         217          NaN           confirmed
217       218         218          NaN           confirmed
218       219         219          NaN           confirmed
219       220         220          NaN           confirmed

[220 rows x 4 columns]

In [77]:
query = "INSERT INTO order_confirmation(order_id, payment_id, delivery_id, confirmation_status) VALUES (%s,%s,%s,%s)"
data = [
    tuple(None if pd.isna(item) else item for item in row) 
    for row in order_confirmation.itertuples(index=False, name=None)
]
cursor.executemany(query, data)
cursor.execute("SELECT * FROM order_confirmation")
for i in cursor:
    print(i)

(1, 1, None, 'confirmed')
(2, 2, None, 'confirmed')
(3, 3, None, 'not confirmed')
(4, 4, None, 'confirmed')
(5, 5, None, 'not confirmed')
(6, 6, None, 'not confirmed')
(7, 7, None, 'not confirmed')
(8, 8, None, 'confirmed')
(9, 9, None, 'confirmed')
(10, 10, None, 'confirmed')
(11, 11, None, 'confirmed')
(12, 12, None, 'confirmed')
(13, 13, None, 'confirmed')
(14, 14, None, 'confirmed')
(15, 15, None, 'confirmed')
(16, 16, None, 'confirmed')
(17, 17, None, 'confirmed')
(18, 18, None, 'confirmed')
(19, 19, None, 'confirmed')
(20, 20, None, 'confirmed')
(21, 21, None, 'confirmed')
(22, 22, None, 'confirmed')
(23, 23, None, 'confirmed')
(24, 24, None, 'confirmed')
(25, 25, None, 'confirmed')
(26, 26, None, 'confirmed')
(27, 27, None, 'confirmed')
(28, 28, None, 'not confirmed')
(29, 29, None, 'confirmed')
(30, 30, None, 'confirmed')
(31, 31, None, 'confirmed')
(32, 32, None, 'confirmed')
(33, 33, None, 'not confirmed')
(34, 34, None, 'confirmed')
(35, 35, None, 'not confirmed')
(36, 36, None, 'confirmed')
(37, 37, None, 'confirmed')
(38, 38, None, 'confirmed')
(39, 39, None, 'confirmed')
(40, 40, None, 'confirmed')
(41, 41, None, 'confirmed')
(42, 42, None, 'confirmed')
(43, 43, None, 'confirmed')
(44, 44, None, 'confirmed')
(45, 45, None, 'not confirmed')
(46, 46, None, 'not confirmed')
(47, 47, None, 'confirmed')
(48, 48, None, 'confirmed')
(49, 49, None, 'not confirmed')
(50, 50, None, 'confirmed')
(51, 51, None, 'confirmed')
(52, 52, None, 'confirmed')
(53, 53, None, 'not confirmed')
(54, 54, None, 'confirmed')
(55, 55, None, 'confirmed')
(56, 56, None, 'confirmed')
(57, 57, None, 'confirmed')
(58, 58, None, 'confirmed')
(59, 59, None, 'not confirmed')
(60, 60, None, 'confirmed')
(61, 61, None, 'confirmed')
(62, 62, None, 'confirmed')
(63, 63, None, 'confirmed')
(64, 64, None, 'confirmed')
(65, 65, None, 'confirmed')
(66, 66, None, 'confirmed')
(67, 67, None, 'confirmed')
(68, 68, None, 'confirmed')
(69, 69, None, 'confirmed')
(70, 70, None, 'confirmed')
(71, 71, None, 'not confirmed')
(72, 72, None, 'confirmed')
(73, 73, None, 'confirmed')
(74, 74, None, 'confirmed')
(75, 75, None, 'confirmed')
(76, 76, None, 'confirmed')
(77, 77, None, 'not confirmed')
(78, 78, None, 'confirmed')
(79, 79, None, 'confirmed')
(80, 80, None, 'confirmed')
(81, 81, None, 'confirmed')
(82, 82, None, 'confirmed')
(83, 83, None, 'not confirmed')
(84, 84, None, 'confirmed')
(85, 85, None, 'confirmed')
(86, 86, None, 'confirmed')
(87, 87, None, 'confirmed')
(88, 88, None, 'confirmed')
(89, 89, None, 'confirmed')
(90, 90, None, 'confirmed')
(91, 91, None, 'confirmed')
(92, 92, None, 'confirmed')
(93, 93, None, 'confirmed')
(94, 94, None, 'confirmed')
(95, 95, None, 'not confirmed')
(96, 96, None, 'confirmed')
(97, 97, None, 'confirmed')
(98, 98, None, 'not confirmed')
(99, 99, None, 'confirmed')
(100, 100, None, 'confirmed')
(101, 101, None, 'confirmed')
(102, 102, None, 'confirmed')
(103, 103, None, 'not confirmed')
(104, 104, None, 'confirmed')
(105, 105, None, 'confirmed')
(106, 106, None, 'confirmed')
(107, 107, None, 'confirmed')
(108, 108, None, 'confirmed')
(109, 109, None, 'confirmed')
(110, 110, None, 'confirmed')
(111, 111, None, 'confirmed')
(112, 112, None, 'confirmed')
(113, 113, None, 'confirmed')
(114, 114, None, 'confirmed')
(115, 115, None, 'confirmed')
(116, 116, None, 'confirmed')
(117, 117, None, 'confirmed')
(118, 118, None, 'confirmed')
(119, 119, None, 'confirmed')
(120, 120, None, 'confirmed')
(121, 121, None, 'confirmed')
(122, 122, None, 'confirmed')
(123, 123, None, 'not confirmed')
(124, 124, None, 'confirmed')
(125, 125, None, 'confirmed')
(126, 126, None, 'confirmed')
(127, 127, None, 'confirmed')
(128, 128, None, 'confirmed')
(129, 129, None, 'confirmed')
(130, 130, None, 'confirmed')
(131, 131, None, 'confirmed')
(132, 132, None, 'confirmed')
(133, 133, None, 'confirmed')
(134, 134, None, 'confirmed')
(135, 135, None, 'not confirmed')
(136, 136, None, 'confirmed')
(137, 137, None, 'confirmed')
(138, 138, None, 'confirmed')
(139, 139, None, 'confirmed')
(140, 140, None, 'not confirmed')
(141, 141, None, 'not confirmed')
(142, 142, None, 'confirmed')
(143, 143, None, 'not confirmed')
(144, 144, None, 'not confirmed')
(145, 145, None, 'confirmed')
(146, 146, None, 'not confirmed')
(147, 147, None, 'confirmed')
(148, 148, None, 'not confirmed')
(149, 149, None, 'confirmed')
(150, 150, None, 'confirmed')
(151, 151, None, 'confirmed')
(152, 152, None, 'not confirmed')
(153, 153, None, 'confirmed')
(154, 154, None, 'confirmed')
(155, 155, None, 'confirmed')
(156, 156, None, 'confirmed')
(157, 157, None, 'not confirmed')
(158, 158, None, 'confirmed')
(159, 159, None, 'confirmed')
(160, 160, None, 'confirmed')
(161, 161, None, 'confirmed')
(162, 162, None, 'confirmed')
(163, 163, None, 'confirmed')
(164, 164, None, 'confirmed')
(165, 165, None, 'confirmed')
(166, 166, None, 'not confirmed')
(167, 167, None, 'confirmed')
(168, 168, None, 'confirmed')
(169, 169, None, 'confirmed')
(170, 170, None, 'not confirmed')
(171, 171, None, 'confirmed')
(172, 172, None, 'confirmed')
(173, 173, None, 'confirmed')
(174, 174, None, 'confirmed')
(175, 175, None, 'not confirmed')
(176, 176, None, 'confirmed')
(177, 177, None, 'confirmed')
(178, 178, None, 'confirmed')
(179, 179, None, 'confirmed')
(180, 180, None, 'confirmed')
(181, 181, None, 'confirmed')
(182, 182, None, 'confirmed')
(183, 183, None, 'confirmed')
(184, 184, None, 'confirmed')
(185, 185, None, 'not confirmed')
(186, 186, None, 'confirmed')
(187, 187, None, 'not confirmed')
(188, 188, None, 'confirmed')
(189, 189, None, 'confirmed')
(190, 190, None, 'confirmed')
(191, 191, None, 'confirmed')
(192, 192, None, 'confirmed')
(193, 193, None, 'confirmed')
(194, 194, None, 'not confirmed')
(195, 195, None, 'confirmed')
(196, 196, None, 'confirmed')
(197, 197, None, 'confirmed')
(198, 198, None, 'confirmed')
(199, 199, None, 'confirmed')
(200, 200, None, 'confirmed')
(201, 201, None, 'confirmed')
(202, 202, None, 'confirmed')
(203, 203, None, 'not confirmed')
(204, 204, None, 'not confirmed')
(205, 205, None, 'confirmed')
(206, 206, None, 'confirmed')
(207, 207, None, 'confirmed')
(208, 208, None, 'confirmed')
(209, 209, None, 'confirmed')
(210, 210, None, 'confirmed')
(211, 211, None, 'confirmed')
(212, 212, None, 'confirmed')
(213, 213, None, 'not confirmed')
(214, 214, None, 'confirmed')
(215, 215, None, 'confirmed')
(216, 216, None, 'not confirmed')
(217, 217, None, 'confirmed')
(218, 218, None, 'confirmed')
(219, 219, None, 'confirmed')
(220, 220, None, 'confirmed')

# Updating database

In [78]:
database.commit()

In [79]:
database.close()